quoting-CypressTK1/force-app/main/default/objects/Clipboard__e/Clipboard__e.object-meta.xml
<CustomObject>
    <label>Clipboard</label>
    <pluralLabel>Clipboards</pluralLabel>
</CustomObject>

quoting-CypressTK1/force-app/main/default/objects/Clipboard__e/fields/ParentId__c.field-meta.xml
<CustomField>
    <fullName>ParentId__c</fullName>
    <label>Parent Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

quoting-CypressTK1/force-app/main/default/objects/Clipboard__e/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>API name of object referenced by the parent id</description>
    <label>Type</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

quoting-CypressTK1/force-app/main/default/classes/ClipboardService.cls
/**
 *  Provus Services Quoting
 *  ClipboardService
 *  @2022 Provus Inc. All rights reserved.
 */
public with sharing class ClipboardService {
	@AuraEnabled
	public static void copyToClipboard(String parentId, String type) {
		List<Clipboard__e> clipboardEvents = new List<Clipboard__e>();
		clipboardEvents.add(new Clipboard__e(ParentId__c = parentId, Type__c = type));
		EventBus.publish(clipboardEvents);
	}
}