quoting-CypressTK1/force-app/main/default/objects/ProvusProductMapping__mdt/ProvusProductMapping__mdt.object-meta.xml
<CustomObject>
    <description
	>Provus Product Mappings custom metadata object to store the field mapping between Product2 and Product__c object</description>
    <label>Provus Product Mapping</label>
    <pluralLabel>Provus Product Mappings</pluralLabel>
</CustomObject>

quoting-CypressTK1/force-app/main/default/objects/ProvusProductMapping__mdt/fields/FieldName__c.field-meta.xml
<CustomField>
    <fullName>FieldName__c</fullName>
    <description>Provus Product Field Name to map with Product2 field name</description>
    <label>Field Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

quoting-CypressTK1/force-app/main/default/objects/ProvusProductMapping__mdt/fields/Product2FieldName__c.field-meta.xml
<CustomField>
    <fullName>Product2FieldName__c</fullName>
    <description>Product2 Field Name</description>
    <label>Product2 Field Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

quoting-CypressTK1/force-app/main/default/classes/ProvusProductMappingDTO.cls
/**
 *  Provus Services Quoting
 *  ProvusProductMappingDTO
 *  @2022 Provus Inc. All rights reserved.
 */
public with sharing class ProvusProductMappingDTO extends BaseDTO {
	public ProvusProductMapping__mdt sO;
	public String fieldName;
	public String product2FieldName;

	public ProvusProductMappingDTO(ProvusProductMapping__mdt so) {
		this.sO = so;
		this.name = this.sO.DeveloperName;
		this.fieldName = this.sO.FieldName__c;
		this.product2FieldName = this.sO.Product2FieldName__c;
	}

	public override SObject refreshSo() {
		return null;
	}
}