quoting-CypressTK1/force-app/main/default/objects/ColaAdjustment__c/ColaAdjustment__c.object-meta.xml
<CustomObject>
    <label>Cola Adjustment</label>
    <nameField>
        <label>Cola Adjustment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cola Adjustments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

quoting-CypressTK1/force-app/main/default/objects/ColaAdjustment__c/fields/ColaRateId__c.field-meta.xml
<CustomField>
    <fullName>ColaRateId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Cola Rate</label>
    <referenceTo>COLARate__c</referenceTo>
    <relationshipLabel>Cola Adjustments Rate Card</relationshipLabel>
    <relationshipName>ColaAdjustmentsRateCard</relationshipName>
    <type>Lookup</type>
</CustomField>

quoting-CypressTK1/force-app/main/default/objects/ColaAdjustment__c/fields/CostIncrease__c.field-meta.xml
<CustomField>
    <fullName>CostIncrease__c</fullName>
    <label>Cost Increase</label>
    <precision>18</precision>
    <scale>5</scale>
    <type>Number</type>
</CustomField>

quoting-CypressTK1/force-app/main/default/objects/ColaAdjustment__c/fields/CostIncreaseWithOverride__c.field-meta.xml
<CustomField>
    <fullName>CostIncreaseWithOverride__c</fullName>
    <label>Cost Increase with COLA Override</label>
    <precision>18</precision>
    <scale>5</scale>
    <type>Number</type>
</CustomField>

quoting-CypressTK1/force-app/main/default/objects/ColaAdjustment__c/fields/CurrentCost__c.field-meta.xml
<CustomField>
    <fullName>CurrentCost__c</fullName>
    <label>Current Cost</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

quoting-CypressTK1/force-app/main/default/objects/ColaAdjustment__c/fields/CurrentRevenue__c.field-meta.xml
<CustomField>
    <fullName>CurrentRevenue__c</fullName>
    <label>Current Revenue</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

quoting-CypressTK1/force-app/main/default/objects/ColaAdjustment__c/fields/NewCost__c.field-meta.xml
<CustomField>
    <fullName>NewCost__c</fullName>
    <label>New Cost</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

quoting-CypressTK1/force-app/main/default/objects/ColaAdjustment__c/fields/NewCostWithOverride__c.field-meta.xml
<CustomField>
    <fullName>NewCostWithOverride__c</fullName>
    <label>New Cost with COLA Override</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

quoting-CypressTK1/force-app/main/default/objects/ColaAdjustment__c/fields/OriginalCost__c.field-meta.xml
<CustomField>
    <fullName>OriginalCost__c</fullName>
    <label>Original Cost</label>
    <precision>18</precision>
    <scale>5</scale>
    <type>Number</type>
</CustomField>

quoting-CypressTK1/force-app/main/default/objects/ColaAdjustment__c/fields/QuoteId__c.field-meta.xml
<CustomField>
    <fullName>QuoteId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quote</label>
    <referenceTo>Quote__c</referenceTo>
    <relationshipLabel>Cola Adjustments Quote</relationshipLabel>
    <relationshipName>ColaAdjustmentsQuote</relationshipName>
    <type>Lookup</type>
</CustomField>

quoting-CypressTK1/force-app/main/default/objects/COLARate__c/fields/RateOverride__c.field-meta.xml
<CustomField>
    <fullName>RateOverride__c</fullName>
    <label>Rate Override</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Percent</type>
</CustomField>

quoting-CypressTK1/force-app/main/default/classes/ColaAdjustmentDto.cls
/*
 * Provus Services Quoting
 * Copyright (c) 2022 Provus Inc. All rights reserved.
 */
@SuppressWarnings('PMD.ExcessivePublicCount')
public with sharing class ColaAdjustmentDto extends BaseDTO {
	public ColaAdjustment__c colaAdjustmentSO;
	@AuraEnabled
	public String colaRateId { get; set; }
	@AuraEnabled
	public Decimal rateOverride { get; set; }
	@AuraEnabled
	public Decimal costIncrease { get; set; }
	@AuraEnabled
	public Decimal costIncreaseWithOverride { get; set; }
	@AuraEnabled
	public Decimal currentCost { get; set; }
	@AuraEnabled
	public Decimal currentRevenue { get; set; }
	@AuraEnabled
	public Decimal newCost { get; set; }
	@AuraEnabled
	public Decimal newCostWithOverride { get; set; }
	@AuraEnabled
	public Decimal originalCost { get; set; }
	@AuraEnabled
	public Id quoteId { get; set; }

	public ColaAdjustmentDto() {
	}

	public ColaAdjustmentDto(ColaAdjustment__c colaAdjustmentSO) {
		this.colaRateId = colaAdjustmentSO.ColaRateId__c;
		this.costIncrease = colaAdjustmentSO.CostIncrease__c;
		this.costIncreaseWithOverride = colaAdjustmentSO.CostIncreaseWithOverride__c;
		this.currentCost = colaAdjustmentSO.CurrentCost__c;
		this.currentRevenue = colaAdjustmentSO.CurrentRevenue__c;
		this.newCost = colaAdjustmentSO.NewCost__c;
		this.newCostWithOverride = colaAdjustmentSO.NewCostWithOverride__c;
		this.originalCost = colaAdjustmentSO.OriginalCost__c;
		this.quoteId = colaAdjustmentSO.QuoteId__c;
	}

	public override SObject refreshSo() {
		if (this.colaAdjustmentSO == null) {
			this.colaAdjustmentSO = new ColaAdjustment__c();
			this.colaAdjustmentSO.ColaRateId__c = this.colaRateId;
			this.colaAdjustmentSO.ColaRateId__r = new ColaRate__c(
				Id = this.colaRateId,
				RateOverride__c = this.rateOverride
			);
			this.colaAdjustmentSO.CostIncrease__c = this.costIncrease;
			this.colaAdjustmentSO.CostIncreaseWithOverride__c = this.costIncreaseWithOverride;
			this.colaAdjustmentSO.CurrentCost__c = this.currentCost;
			this.colaAdjustmentSO.CurrentRevenue__c = this.currentRevenue;
			this.colaAdjustmentSO.NewCost__c = this.newCost;
			this.colaAdjustmentSO.NewCostWithOverride__c = this.newCostWithOverride;
			this.colaAdjustmentSO.OriginalCost__c = this.originalCost;
			this.colaAdjustmentSO.QuoteId__c = this.quoteId;
		}

		return colaAdjustmentSO;
	}
}