quoting-CypressTK1/force-app/main/default/objects/ColaAdjustment__c/ColaAdjustment__c.object-meta.xml
<CustomObject>
    <label>Cola Adjustment</label>
    <nameField>
        <label>Cola Adjustment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cola Adjustments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

quoting-CypressTK1/force-app/main/default/objects/ColaAdjustment__c/fields/ColaRateId__c.field-meta.xml
<CustomField>
    <fullName>ColaRateId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Cola Rate</label>
    <referenceTo>COLARate__c</referenceTo>
    <relationshipLabel>Cola Adjustments Rate Card</relationshipLabel>
    <relationshipName>ColaAdjustmentsRateCard</relationshipName>
    <type>Lookup</type>
</CustomField>

quoting-CypressTK1/force-app/main/default/objects/ColaAdjustment__c/fields/CostIncrease__c.field-meta.xml
<CustomField>
    <fullName>CostIncrease__c</fullName>
    <label>Cost Increase</label>
    <precision>18</precision>
    <scale>5</scale>
    <type>Number</type>
</CustomField>

quoting-CypressTK1/force-app/main/default/objects/ColaAdjustment__c/fields/CostIncreaseWithOverride__c.field-meta.xml
<CustomField>
    <fullName>CostIncreaseWithOverride__c</fullName>
    <label>Cost Increase with COLA Override</label>
    <precision>18</precision>
    <scale>5</scale>
    <type>Number</type>
</CustomField>

quoting-CypressTK1/force-app/main/default/objects/ColaAdjustment__c/fields/CurrentCost__c.field-meta.xml
<CustomField>
    <fullName>CurrentCost__c</fullName>
    <label>Current Cost</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

quoting-CypressTK1/force-app/main/default/objects/ColaAdjustment__c/fields/CurrentRevenue__c.field-meta.xml
<CustomField>
    <fullName>CurrentRevenue__c</fullName>
    <label>Current Revenue</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

quoting-CypressTK1/force-app/main/default/objects/ColaAdjustment__c/fields/NewCost__c.field-meta.xml
<CustomField>
    <fullName>NewCost__c</fullName>
    <label>New Cost</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

quoting-CypressTK1/force-app/main/default/objects/ColaAdjustment__c/fields/NewCostWithOverride__c.field-meta.xml
<CustomField>
    <fullName>NewCostWithOverride__c</fullName>
    <label>New Cost with COLA Override</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

quoting-CypressTK1/force-app/main/default/objects/ColaAdjustment__c/fields/OriginalCost__c.field-meta.xml
<CustomField>
    <fullName>OriginalCost__c</fullName>
    <label>Original Cost</label>
    <precision>18</precision>
    <scale>5</scale>
    <type>Number</type>
</CustomField>

quoting-CypressTK1/force-app/main/default/objects/ColaAdjustment__c/fields/QuoteId__c.field-meta.xml
<CustomField>
    <fullName>QuoteId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quote</label>
    <referenceTo>Quote__c</referenceTo>
    <relationshipLabel>Cola Adjustments Quote</relationshipLabel>
    <relationshipName>ColaAdjustmentsQuote</relationshipName>
    <type>Lookup</type>
</CustomField>

quoting-CypressTK1/force-app/main/default/objects/COLARate__c/fields/RateOverride__c.field-meta.xml
<CustomField>
    <fullName>RateOverride__c</fullName>
    <label>Rate Override</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Percent</type>
</CustomField>

quoting-CypressTK1/force-app/main/default/classes/ColaAdjustmentService.cls
/*
 * Provus Services Quoting
 * Copyright (c) 2022 Provus Inc. All rights reserved.
 */
public with sharing class ColaAdjustmentService {
	public static List<ColaAdjustment__c> getColaAdjustmentSOs(Id quoteId) {
		return [
			SELECT
				Id,
				ColaRateId__c,
				ColaRateId__r.RateOverride__c,
				CostIncrease__c,
				CostIncreaseWithOverride__c,
				CurrentCost__c,
				CurrentRevenue__c,
				NewCost__c,
				NewCostWithOverride__c,
				OriginalCost__c,
				QuoteId__c
			FROM ColaAdjustment__c
			WHERE QuoteId__c = :quoteId
			WITH SECURITY_ENFORCED
		];
	}

	public static List<ColaAdjustmentDto> getColaAdjustments(Id quoteId) {
		List<ColaAdjustmentDto> colaAdjustmentDtos = new List<ColaAdjustmentDto>();
		for (ColaAdjustment__c colaAdjustmentSO : getColaAdjustmentSOs(quoteId)) {
			colaAdjustmentDtos.add(new ColaAdjustmentDto(colaAdjustmentSO));
		}
		return colaAdjustmentDtos;
	}

	public static void saveColaAdjustments(List<ColaAdjustmentDto> colaAdjustmentDtos) {
		List<ColaAdjustment__c> colaAdjustments = new List<ColaAdjustment__c>();
		for (ColaAdjustmentDto colaAdjustmentDto : colaAdjustmentDtos) {
			colaAdjustments.add((ColaAdjustment__c) colaAdjustmentDto.refreshSo());
		}
		CRUDUtility.upsertRecords(colaAdjustments);
	}

	public static void deleteColaAdjustments(Id quoteId) {
		List<ColaAdjustment__c> colaAdjustmentSOs = getColaAdjustmentSOs(quoteId);
		CRUDUtility.deleteRecords(colaAdjustmentSOs);
	}
}