quoting-CypressTK1/force-app/main/default/objects/ResourceAvailability__c/ResourceAvailability__c.object-meta.xml
<CustomObject>
    <description
	>Captures the maximum time a resource is available to work for a given period</description>
    <label>Resource Availability</label>
    <nameField>
        <displayFormat>RA-{00000}</displayFormat>
        <label>Resource Availability</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Resource Availabilities</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

quoting-CypressTK1/force-app/main/default/objects/ResourceAvailability__c/fields/FullTimeTotalEstimatedDuration__c.field-meta.xml
<CustomField>
    <fullName>FullTimeTotalEstimatedDuration__c</fullName>
    <formula
	>IF(AvailabilityPercentage__c == NULL, TaskRoleSummaryId__r.TotalEstimatedDuration__c, IF(AvailabilityPercentage__c == 0, 0, TaskRoleSummaryId__r.TotalEstimatedDuration__c * (1 / AvailabilityPercentage__c)))</formula>
    <label>Full Time Total Estimated Duration</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

quoting-CypressTK1/force-app/main/default/objects/ResourceAvailability__c/fields/TaskRoleSummaryId__c.field-meta.xml
<CustomField>
    <fullName>TaskRoleSummaryId__c</fullName>
    <label>Task Role Summary</label>
    <referenceTo>TaskRoleSummary__c</referenceTo>
    <relationshipLabel>Resource Availabilities</relationshipLabel>
    <relationshipName>ResourceAvailabilities</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

quoting-CypressTK1/force-app/main/default/objects/ResourceSplit__c/ResourceSplit__c.object-meta.xml
<CustomObject>
    <label>Resource Split</label>
    <nameField>
        <label>Resource Split Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Resource Splits</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

quoting-CypressTK1/force-app/main/default/objects/ResourceSplit__c/fields/SplitPercentage__c.field-meta.xml
<CustomField>
    <fullName>SplitPercentage__c</fullName>
    <label>Split Percentage</label>
    <precision>18</precision>
    <scale>15</scale>
    <type>Percent</type>
</CustomField>

quoting-CypressTK1/force-app/main/default/objects/ResourceSplit__c/fields/TaskRoleSummaryId__c.field-meta.xml
<CustomField>
    <fullName>TaskRoleSummaryId__c</fullName>
    <label>Task Role Summary</label>
    <referenceTo>TaskRoleSummary__c</referenceTo>
    <relationshipLabel>Resource Splits</relationshipLabel>
    <relationshipName>ResourceSplits</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

quoting-CypressTK1/force-app/main/default/objects/ResourceSplit__c/fields/TotalEstimatedDuration__c.field-meta.xml
<CustomField>
    <fullName>TotalEstimatedDuration__c</fullName>
    <formula>TaskRoleSummaryId__r.TotalEstimatedDuration__c  *  SplitPercentage__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total Estimated Duration</label>
    <precision>18</precision>
    <scale>5</scale>
    <type>Number</type>
</CustomField>

quoting-CypressTK1/force-app/main/default/objects/TaskRoleSummary__c/fields/ResourceRoleId__c.field-meta.xml
<CustomField>
    <fullName>ResourceRoleId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Resource Role</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Product__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Resource Role</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Product__c</referenceTo>
    <relationshipName>LevelSummaries</relationshipName>
    <type>Lookup</type>
</CustomField>

quoting-CypressTK1/force-app/main/default/objects/TaskRoleSummary__c/fields/SummaryLevel__c.field-meta.xml
<CustomField>
    <fullName>SummaryLevel__c</fullName>
    <label>Summary Level</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Estimate</fullName>
            </value>
            <value>
                <fullName>Activity Group</fullName>
            </value>
            <value>
                <fullName>Activity</fullName>
            </value>
            <value>
                <fullName>Phase</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

quoting-CypressTK1/force-app/main/default/objects/TaskRoleSummary__c/fields/TotalEstimatedDuration__c.field-meta.xml
<CustomField>
    <fullName>TotalEstimatedDuration__c</fullName>
    <formula>TotalCalculatedDuration__c + TotalAdjustments__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total estimated duration</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

quoting-CypressTK1/force-app/main/default/classes/TaskRoleSummary.cls
public with sharing class TaskRoleSummary extends ManagedObject {
	public static final String NAME = 'TaskRoleSummary__c';
	public static final String RESOURCE_ROLE_ID = 'ResourceRoleId__c';
	public static final String ROLLEDUP_ESTIMATED_DURATION = 'RolledUpEstimatedDuration__c';
	public static final String ACTIVITY_GROUP_ID = 'ActivityGroupId__c';
	public static final String RELATED_ACTIVITY_GROUP_NAME = 'ActivityGroupId__r.Name';
	public static final String RELATED_ACTIVITY_GROUP_SEQUENCE = 'ActivityGroupId__r.Sequence__c';
	public static final String RELATED_ACTIVITY_GROUP_ESTIMATE_ID = 'ActivityGroupId__r.EstimateId__c';
	public static final String SUMMARY_LEVEL = 'SummaryLevel__c';
	public static final String ESTIMATE_ID = 'EstimateId__c';
	public static final String SUMMARYLEVEL_ESTIMATE = 'Estimate';
	public static final String SUMMARYLEVEL_ACTIVITY_GROUP = 'Activity Group';

	public TaskRoleSummary(TaskRoleSummary__c taskRoleSummarySo) {
		super(taskRoleSummarySo);
	}

	public static List<TaskRoleSummary> toTaskRoleSummary(
		List<TaskRoleSummary__c> taskRoleSummaries
	) {
		List<TaskRoleSummary> taskRoleSummariesMos = new List<TaskRoleSummary>();
		for (TaskRoleSummary__c taskRoleSummarySo : taskRoleSummaries) {
			taskRoleSummariesMos.add(new TaskRoleSummary(taskRoleSummarySo));
		}

		return taskRoleSummariesMos;
	}

	public Decimal maxEstimatedDuration() {
		TaskRoleSummary__c taskRoleSummary = (TaskRoleSummary__c) getSObject();
		Decimal maxDuration = taskRoleSummary.TotalEstimatedDuration__c;
		ResourceSplit__c maxSplit = maxResourceSplit(taskRoleSummary.ResourceSplits__r);
		ResourceAvailability__c maxAvailability = maxAvailability(
			taskRoleSummary.ResourceAvailabilities__r
		);
		// assumes that the avilability percentage applies to the entire summary
		if (maxAvailability != null) {
			maxDuration = maxAvailability.FullTimeTotalEstimatedDuration__c;
		}

		if (maxSplit != null) {
			maxDuration *= (maxSplit.SplitPercentage__c / 100);
		}

		return maxDuration;
	}

	private ResourceSplit__c maxResourceSplit(List<ResourceSplit__c> resourceSplits) {
		ResourceSplit__c maxSplit;
		for (ResourceSplit__c resourceSplit : resourceSplits) {
			if (maxSplit == null || resourceSplit.SplitPercentage__c > maxSplit.SplitPercentage__c) {
				maxSplit = resourceSplit;
			}
		}
		return maxSplit;
	}

	private ResourceAvailability__c maxAvailability(
		List<ResourceAvailability__c> resourceAvailabilities
	) {
		ResourceAvailability__c maxAvailability;
		for (ResourceAvailability__c resourceAvailability : resourceAvailabilities) {
			if (
				maxAvailability == null ||
				resourceAvailability.FullTimeTotalEstimatedDuration__c >
				maxAvailability.FullTimeTotalEstimatedDuration__c
			) {
				maxAvailability = resourceAvailability;
			}
		}

		return maxAvailability;
	}
}