quoting-CypressTK1/force-app/main/default/objects/ResourceAvailability__c/ResourceAvailability__c.object-meta.xml
<CustomObject>
    <description
	>Captures the maximum time a resource is available to work for a given period</description>
    <label>Resource Availability</label>
    <nameField>
        <displayFormat>RA-{00000}</displayFormat>
        <label>Resource Availability</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Resource Availabilities</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

quoting-CypressTK1/force-app/main/default/objects/ResourceAvailability__c/fields/AvailabilityPercentage__c.field-meta.xml
<CustomField>
    <fullName>AvailabilityPercentage__c</fullName>
    <label>Availability Percentage</label>
    <precision>6</precision>
    <scale>3</scale>
    <type>Percent</type>
</CustomField>

quoting-CypressTK1/force-app/main/default/objects/ResourceAvailability__c/fields/TaskRoleSummaryId__c.field-meta.xml
<CustomField>
    <fullName>TaskRoleSummaryId__c</fullName>
    <label>Task Role Summary</label>
    <referenceTo>TaskRoleSummary__c</referenceTo>
    <relationshipLabel>Resource Availabilities</relationshipLabel>
    <relationshipName>ResourceAvailabilities</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

quoting-CypressTK1/force-app/main/default/objects/ResourceSplit__c/ResourceSplit__c.object-meta.xml
<CustomObject>
    <label>Resource Split</label>
    <nameField>
        <label>Resource Split Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Resource Splits</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

quoting-CypressTK1/force-app/main/default/objects/ResourceSplit__c/fields/LevelAdjustment__c.field-meta.xml
<CustomField>
    <fullName>LevelAdjustment__c</fullName>
    <formula>TaskRoleSummaryId__r.LevelAdjustment__c  *  SplitPercentage__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Level Adjustment</label>
    <precision>18</precision>
    <scale>5</scale>
    <type>Number</type>
</CustomField>

quoting-CypressTK1/force-app/main/default/objects/ResourceSplit__c/fields/SplitPercentage__c.field-meta.xml
<CustomField>
    <fullName>SplitPercentage__c</fullName>
    <label>Split Percentage</label>
    <precision>18</precision>
    <scale>15</scale>
    <type>Percent</type>
</CustomField>

quoting-CypressTK1/force-app/main/default/objects/ResourceSplit__c/fields/TaskRoleSummaryId__c.field-meta.xml
<CustomField>
    <fullName>TaskRoleSummaryId__c</fullName>
    <label>Task Role Summary</label>
    <referenceTo>TaskRoleSummary__c</referenceTo>
    <relationshipLabel>Resource Splits</relationshipLabel>
    <relationshipName>ResourceSplits</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

quoting-CypressTK1/force-app/main/default/objects/TaskRoleSummary__c/fields/LevelAdjustment__c.field-meta.xml
<CustomField>
    <fullName>LevelAdjustment__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Level adjustment</label>
    <precision>18</precision>
    <scale>5</scale>
    <type>Number</type>
</CustomField>

quoting-CypressTK1/force-app/main/default/classes/EstimateServiceTest.cls
/*
 * Provus Services Quoting
 * Copyright (c) 2022 Provus Inc. All rights reserved.
 */

@IsTest
private class EstimateServiceTest extends EstimateTestBase {
	@IsTest
	static void shouldCalculateADateBasedOn640Hours() {
		Estimate__c estimateSo = newEstimate();
		ActivityGroup__c groupSo = createNewActivityGroup(estimateSo.Id);
		TaskRoleSummary__c roleSummary1 = TaskRoleSummaryTestBase.newTaskRoleSummary();
		roleSummary1.ActivityGroupId__c = groupSo.Id;
		roleSummary1.EstimateId__c = estimateSo.Id;
		roleSummary1.LevelAdjustment__c = 400;
		TaskRoleSummary__c roleSummary2 = TaskRoleSummaryTestBase.newTaskRoleSummary();
		roleSummary1.ActivityGroupId__c = groupSo.Id;
		roleSummary1.EstimateId__c = estimateSo.Id;
		roleSummary1.LevelAdjustment__c = 1280;
		CRUDUtility.updateRecords(new List<TaskRoleSummary__c>{ roleSummary1, roleSummary2 });

		ResourceSplit__c split1 = new ResourceSplit__c(
			TaskRoleSummaryId__c = roleSummary1.Id,
			SplitPercentage__c = 50
		);
		ResourceSplit__c split2 = new ResourceSplit__c(
			TaskRoleSummaryId__c = roleSummary1.Id,
			SplitPercentage__c = 50
		);
		CRUDUtility.insertRecords(new List<ResourceSplit__c>{ split1, split2 });

		Test.startTest();
		{
			EndDateArgs args = new EndDateArgs();
			args.calendarAlignment = 'User Defined Calendar';
			args.serviceStartDate = Date.valueOf('2022-08-01');
			args.timePeriods = TimePeriodMonth.NAME_PLURAL;
			EstimateService.getServiceEndDate(estimateSo.Id, args);
			System.assertEquals(
				Date.valueOf('2022-11-30'),
				EstimateService.getServiceEndDate(estimateSo.Id, args),
				'it should calculate an end date of 2022-11-30'
			);
		}
		Test.stopTest();
	}

	@IsTest
	static void shouldCalculate160HoursWhenSplit() {
		Estimate__c estimateSo = newEstimate();
		ActivityGroup__c groupSo = createNewActivityGroup(estimateSo.Id);
		TaskRoleSummary__c roleSummary1 = TaskRoleSummaryTestBase.newTaskRoleSummary();
		roleSummary1.ActivityGroupId__c = groupSo.Id;
		roleSummary1.EstimateId__c = estimateSo.Id;
		roleSummary1.LevelAdjustment__c = 160;
		TaskRoleSummary__c roleSummary2 = TaskRoleSummaryTestBase.newTaskRoleSummary();
		roleSummary1.ActivityGroupId__c = groupSo.Id;
		roleSummary1.EstimateId__c = estimateSo.Id;
		roleSummary1.LevelAdjustment__c = 320;
		CRUDUtility.updateRecords(new List<TaskRoleSummary__c>{ roleSummary1, roleSummary2 });

		ResourceSplit__c split = new ResourceSplit__c(
			TaskRoleSummaryId__c = roleSummary1.Id,
			SplitPercentage__c = 50
		);
		CRUDUtility.insertRecords(new List<ResourceSplit__c>{ split });

		Test.startTest();
		{
			Map<Id, Decimal> activityGroupMaxByIds = EstimateService.getActivityGroupMaxDurations(
				estimateSo.Id
			);
			System.assertEquals(
				160,
				activityGroupMaxByIds.get(groupSo.Id),
				'it should calculate 160 hours'
			);
		}
		Test.stopTest();
	}

	@IsTest
	static void shouldCalculate160HoursWhenSplitAndParttime() {
		Estimate__c estimateSo = newEstimate();
		ActivityGroup__c groupSo = createNewActivityGroup(estimateSo.Id);
		TaskRoleSummary__c roleSummary1 = TaskRoleSummaryTestBase.newTaskRoleSummary();
		roleSummary1.ActivityGroupId__c = groupSo.Id;
		roleSummary1.EstimateId__c = estimateSo.Id;
		roleSummary1.LevelAdjustment__c = 400;

		CRUDUtility.updateRecords(new List<TaskRoleSummary__c>{ roleSummary1 });

		ResourceSplit__c split1 = new ResourceSplit__c(
			TaskRoleSummaryId__c = roleSummary1.Id,
			SplitPercentage__c = 20
		);
		ResourceSplit__c split2 = new ResourceSplit__c(
			TaskRoleSummaryId__c = roleSummary1.Id,
			SplitPercentage__c = 20
		);
		ResourceSplit__c split3 = new ResourceSplit__c(
			TaskRoleSummaryId__c = roleSummary1.Id,
			SplitPercentage__c = 20
		);
		ResourceSplit__c split4 = new ResourceSplit__c(
			TaskRoleSummaryId__c = roleSummary1.Id,
			SplitPercentage__c = 20
		);
		ResourceSplit__c split5 = new ResourceSplit__c(
			TaskRoleSummaryId__c = roleSummary1.Id,
			SplitPercentage__c = 20
		);
		ResourceAvailability__c availability = new ResourceAvailability__c(
			TaskRoleSummaryId__c = roleSummary1.Id,
			AvailabilityPercentage__c = 50
		);

		CRUDUtility.insertRecords(new List<ResourceSplit__c>{ split1, split2, split3, split4, split5 });
		CRUDUtility.insertRecords(new List<ResourceAvailability__c>{ availability });

		Test.startTest();
		{
			Map<Id, Decimal> activityGroupMaxByIds = EstimateService.getActivityGroupMaxDurations(
				estimateSo.Id
			);
			System.assertEquals(
				160,
				activityGroupMaxByIds.get(groupSo.Id),
				'it should calculate 160 hours'
			);
		}
		Test.stopTest();
	}
}