quoting-CypressTK1/force-app/main/default/objects/ResourceAvailability__c/ResourceAvailability__c.object-meta.xml
<CustomObject>
    <description
	>Captures the maximum time a resource is available to work for a given period</description>
    <label>Resource Availability</label>
    <nameField>
        <displayFormat>RA-{00000}</displayFormat>
        <label>Resource Availability</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Resource Availabilities</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

quoting-CypressTK1/force-app/main/default/objects/ResourceAvailability__c/fields/AvailabilityPercentage__c.field-meta.xml
<CustomField>
    <fullName>AvailabilityPercentage__c</fullName>
    <label>Availability Percentage</label>
    <precision>6</precision>
    <scale>3</scale>
    <type>Percent</type>
</CustomField>

quoting-CypressTK1/force-app/main/default/objects/ResourceAvailability__c/fields/TaskRoleSummaryId__c.field-meta.xml
<CustomField>
    <fullName>TaskRoleSummaryId__c</fullName>
    <label>Task Role Summary</label>
    <referenceTo>TaskRoleSummary__c</referenceTo>
    <relationshipLabel>Resource Availabilities</relationshipLabel>
    <relationshipName>ResourceAvailabilities</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

quoting-CypressTK1/force-app/main/default/classes/ResourceAvailabilityService.cls
/*
 * Provus Services Quoting
 * Copyright (c) 2022 Provus Inc. All rights reserved.
 */
public with sharing class ResourceAvailabilityService {
	public static ResourceAvailability__c getResourceAvailability(Id taskRoleSummaryId) {
		List<ResourceAvailability__c> availabilitySos = [
			SELECT TaskRoleSummaryId__c, AvailabilityPercentage__c
			FROM ResourceAvailability__c
			WHERE TaskRoleSummaryId__c = :taskRoleSummaryId
			WITH SECURITY_ENFORCED
			LIMIT 1
		];

		ResourceAvailability__c availabilitySo;
		if (!availabilitySos.isEmpty()) {
			availabilitySo = availabilitySos[0];
		}

		return availabilitySo;
	}

	public static void saveResourceAvailability(ResourceAvailabilityDto resourceAvailabilityDto) {
		ResourceAvailability__c resourceAvailabilitySo = (ResourceAvailability__c) resourceAvailabilityDto.refreshSo();
		CRUDUtility.upsertRecords(resourceAvailabilitySo);
	}
}