quoting-CypressTK1/force-app/main/default/objects/ResourceAvailability__c/ResourceAvailability__c.object-meta.xml
<CustomObject>
    <description
	>Captures the maximum time a resource is available to work for a given period</description>
    <label>Resource Availability</label>
    <nameField>
        <displayFormat>RA-{00000}</displayFormat>
        <label>Resource Availability</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Resource Availabilities</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

quoting-CypressTK1/force-app/main/default/objects/ResourceAvailability__c/fields/AvailabilityPercentage__c.field-meta.xml
<CustomField>
    <fullName>AvailabilityPercentage__c</fullName>
    <label>Availability Percentage</label>
    <precision>6</precision>
    <scale>3</scale>
    <type>Percent</type>
</CustomField>

quoting-CypressTK1/force-app/main/default/objects/ResourceAvailability__c/fields/TaskRoleSummaryId__c.field-meta.xml
<CustomField>
    <fullName>TaskRoleSummaryId__c</fullName>
    <label>Task Role Summary</label>
    <referenceTo>TaskRoleSummary__c</referenceTo>
    <relationshipLabel>Resource Availabilities</relationshipLabel>
    <relationshipName>ResourceAvailabilities</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

quoting-CypressTK1/force-app/main/default/classes/ResourceAvailabilityControllerTest.cls
/*
 * Provus Services Quoting
 * Copyright (c) 2022 Provus Inc. All rights reserved.
 */
@IsTest
public with sharing class ResourceAvailabilityControllerTest extends TestBase {
	@IsTest
	static void shouldReturnFullAvailability() {
		TaskRoleSummary__c summarySo = TaskRoleSummaryTestBase.newTaskRoleSummary();
		Test.startTest();
		{
			ResourceAvailabilityDto availabilityDto = ResourceAvailabilityController.getResourceAvailability(
				summarySo.Id
			);
			System.assertEquals(100, availabilityDto.availabilityPercentage);
		}
		Test.stopTest();
	}

	@IsTest
	static void shouldReturnPartAvailability() {
		TaskRoleSummary__c summarySo = TaskRoleSummaryTestBase.newTaskRoleSummary();
		ResourceAvailability__c availabilitySo = new ResourceAvailability__c(
			TaskRoleSummaryId__c = summarySo.Id,
			AvailabilityPercentage__c = 50
		);
		Test.startTest();
		{
			insert availabilitySo;

			ResourceAvailabilityDto availabilityDto = ResourceAvailabilityController.getResourceAvailability(
				summarySo.Id
			);
			System.assertEquals(50, availabilityDto.availabilityPercentage);
		}
		Test.stopTest();
	}

	@IsTest
	static void shouldSaveResourceAvailability() {
		TaskRoleSummary__c summarySo = TaskRoleSummaryTestBase.newTaskRoleSummary();
		ResourceAvailability__c availabilitySo = new ResourceAvailability__c(
			TaskRoleSummaryId__c = summarySo.Id,
			AvailabilityPercentage__c = 25
		);
		Test.startTest();
		{
			ResourceAvailabilityDto availabilityDto = new ResourceAvailabilityDto(availabilitySo);
			ResourceAvailabilityService.saveResourceAvailability(availabilityDto);

			availabilityDto = ResourceAvailabilityController.getResourceAvailability(summarySo.Id);
			System.assertNotEquals(null, availabilityDto.id);
			System.assertEquals(25, availabilityDto.availabilityPercentage);
		}
		Test.stopTest();
	}
}