quoting-CypressTK1/force-app/main/default/objects/ResourceAvailability__c/ResourceAvailability__c.object-meta.xml
<CustomObject>
    <description
	>Captures the maximum time a resource is available to work for a given period</description>
    <label>Resource Availability</label>
    <nameField>
        <displayFormat>RA-{00000}</displayFormat>
        <label>Resource Availability</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Resource Availabilities</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

quoting-CypressTK1/force-app/main/default/objects/ResourceAvailability__c/fields/AvailabilityPercentage__c.field-meta.xml
<CustomField>
    <fullName>AvailabilityPercentage__c</fullName>
    <label>Availability Percentage</label>
    <precision>6</precision>
    <scale>3</scale>
    <type>Percent</type>
</CustomField>

quoting-CypressTK1/force-app/main/default/objects/ResourceAvailability__c/fields/TaskRoleSummaryId__c.field-meta.xml
<CustomField>
    <fullName>TaskRoleSummaryId__c</fullName>
    <label>Task Role Summary</label>
    <referenceTo>TaskRoleSummary__c</referenceTo>
    <relationshipLabel>Resource Availabilities</relationshipLabel>
    <relationshipName>ResourceAvailabilities</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

quoting-CypressTK1/force-app/main/default/classes/ResourceAvailabilityDtoTest.cls
/*
 * Provus Services Quoting
 * Copyright (c) 2022 Provus Inc. All rights reserved.
 */

@IsTest
private class ResourceAvailabilityDtoTest extends TestBase {
	@IsTest
	static void shouldCreateANewDtoWithTheGivenSObject() {
		TaskRoleSummary__c summarySo = TaskRoleSummaryTestBase.newTaskRoleSummary();
		ResourceAvailability__c availabilitySo = new ResourceAvailability__c(
			TaskRoleSummaryId__c = summarySo.Id,
			AvailabilityPercentage__c = 0.5
		);
		Test.startTest();
		{
			ResourceAvailabilityDto availabilityDto = new ResourceAvailabilityDto(availabilitySo);
			System.assertEquals(0.5, availabilityDto.availabilityPercentage);
			System.assertEquals(summarySo.Id, availabilityDto.taskRoleSummaryId);
		}
		Test.stopTest();
	}
}