quoting-CypressTK1/force-app/main/default/objects/AdjustmentVolumeDiscountTier__c/AdjustmentVolumeDiscountTier__c.object-meta.xml
<CustomObject>
    <description
	>Junction object linking adjustment record to active volume discount tier record</description>
    <label>Adjustment Volume Discount Tier</label>
    <nameField>
        <displayFormat>AVDT-{00000}</displayFormat>
        <label>Adjustment Volume Discount Tier Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Adjustment Volume Discount Tiers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

quoting-CypressTK1/force-app/main/default/objects/AdjustmentVolumeDiscountTier__c/fields/AdjustmentId__c.field-meta.xml
<CustomField>
    <fullName>AdjustmentId__c</fullName>
    <description>Id of related adjustment record</description>
    <inlineHelpText>Id of related adjustment record</inlineHelpText>
    <label>Adjustment Id</label>
    <referenceTo>Adjustment__c</referenceTo>
    <relationshipLabel>Adjustment Volume Discount Tiers</relationshipLabel>
    <relationshipName>AdjustmentVolumeDiscountTiers</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

quoting-CypressTK1/force-app/main/default/objects/AdjustmentVolumeDiscountTier__c/fields/VolumeDiscountTierId__c.field-meta.xml
<CustomField>
    <fullName>VolumeDiscountTierId__c</fullName>
    <description>Id of related volume discount tier record</description>
    <inlineHelpText>Id of related volume discount tier record</inlineHelpText>
    <label>Volume Discount Tier Id</label>
    <referenceTo>VolumeDiscountTier__c</referenceTo>
    <relationshipLabel>Adjustment Volume Discount Tiers</relationshipLabel>
    <relationshipName>AdjustmentVolumeDiscountTiers</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

quoting-CypressTK1/force-app/main/default/objects/NamedRangeTotal__c/fields/AdjustedBaseAmount__c.field-meta.xml
<CustomField>
    <fullName>AdjustedBaseAmount__c</fullName>
    <description>Adjusted base amount</description>
    <label>Adjusted Base Amount</label>
    <precision>18</precision>
    <scale>5</scale>
    <type>Currency</type>
</CustomField>

quoting-CypressTK1/force-app/main/default/objects/VolumeDiscount__c/VolumeDiscount__c.object-meta.xml
<CustomObject>
    <description>Contains volume discount record</description>
    <label>Volume Discount</label>
    <nameField>
        <displayFormat>QVD-{00000}</displayFormat>
        <label>Volume Discount</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Volume Discounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

quoting-CypressTK1/force-app/main/default/objects/VolumeDiscount__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <description>Picklist of available category selections for quote volume discount</description>
    <inlineHelpText>Choose your quote volume discount category</inlineHelpText>
    <label>Category</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Headcount</fullName>
                <label>Headcount Discount</label>
            </value>
            <value>
                <fullName>Labor Revenue</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

quoting-CypressTK1/force-app/main/default/objects/VolumeDiscount__c/fields/QuoteId__c.field-meta.xml
<CustomField>
    <fullName>QuoteId__c</fullName>
    <description>Relationship to parent Quote record</description>
    <inlineHelpText>Relationship to parent Quote record</inlineHelpText>
    <label>Quote</label>
    <referenceTo>Quote__c</referenceTo>
    <relationshipLabel>Volume Discounts</relationshipLabel>
    <relationshipName>VolumeDiscounts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

quoting-CypressTK1/force-app/main/default/objects/VolumeDiscount__c/fields/TotalBy__c.field-meta.xml
<CustomField>
    <fullName>TotalBy__c</fullName>
    <description
	>Selection indicating at what level to apply tier discount details to total whether at the overall quote level, quote period or period group level.</description>
    <inlineHelpText>Choose which level to apply the volume discount</inlineHelpText>
    <label>Total by</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Quote</fullName>
            </value>
            <value>
                <fullName>Period</fullName>
            </value>
            <value>
                <fullName>Period Group</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

quoting-CypressTK1/force-app/main/default/objects/VolumeDiscountTier__c/VolumeDiscountTier__c.object-meta.xml
<CustomObject>
    <description>Object holding volume discount tier details</description>
    <label>Volume Discount Tier</label>
    <nameField>
        <displayFormat>QVDT-{00000}</displayFormat>
        <label>Volume Discount Tier</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Volume Discount Tiers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

quoting-CypressTK1/force-app/main/default/objects/VolumeDiscountTier__c/fields/Discount__c.field-meta.xml
<CustomField>
    <fullName>Discount__c</fullName>
    <description>Quote volume discount tier percentage amount</description>
    <inlineHelpText>Quote volume discount tier percentage amount</inlineHelpText>
    <label>Discount</label>
    <precision>6</precision>
    <scale>3</scale>
    <type>Percent</type>
</CustomField>

quoting-CypressTK1/force-app/main/default/objects/VolumeDiscountTier__c/fields/From__c.field-meta.xml
<CustomField>
    <fullName>From__c</fullName>
    <description>Quote volume discount tier from numeric value</description>
    <inlineHelpText>Quote volume discount tier from numeric value</inlineHelpText>
    <label>From</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

quoting-CypressTK1/force-app/main/default/objects/VolumeDiscountTier__c/fields/Sequence__c.field-meta.xml
<CustomField>
    <fullName>Sequence__c</fullName>
    <description>Tier number indicating order within set of sibling records</description>
    <inlineHelpText>Tier number</inlineHelpText>
    <label>Sequence</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

quoting-CypressTK1/force-app/main/default/objects/VolumeDiscountTier__c/fields/To__c.field-meta.xml
<CustomField>
    <fullName>To__c</fullName>
    <description>Quote volume discount tier to numeric value</description>
    <inlineHelpText>Quote volume discount tier to numeric value</inlineHelpText>
    <label>To</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

quoting-CypressTK1/force-app/main/default/objects/VolumeDiscountTier__c/fields/VolumeDiscountId__c.field-meta.xml
<CustomField>
    <fullName>VolumeDiscountId__c</fullName>
    <description>Relationship to parent object Volume Discount</description>
    <inlineHelpText>Relationship to parent object Volume Discount</inlineHelpText>
    <label>Volume Discount</label>
    <referenceTo>VolumeDiscount__c</referenceTo>
    <relationshipLabel>Volume Discount Tiers</relationshipLabel>
    <relationshipName>VolumeDiscountTiers</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

quoting-CypressTK1/force-app/main/default/classes/VolumeDiscountControllerTest.cls
/**
 *  Provus Services Quoting
 *  VolumeDiscountControllerTest
 *  @2022 Provus Inc. All rights reserved.
 */
@IsTest
public with sharing class VolumeDiscountControllerTest extends TestBase {
	private static String quoteNameNo1 = 'Volume Discount Quote #1';

	@TestSetup
	static void setup() {
		Quote__c quoteSo = TestBase.newQuote(quoteNameNo1);
		QuotePeriod__c periodSo = newQuotePeriod(quoteSo.Id);
		periodSo.Name = 'Test Period';
		CRUDUtility.updateRecords(periodSo);

		VolumeDiscount__c[] volumeDiscountSOs = new VolumeDiscount__c[0];
		VolumeDiscount__c volumeDiscountSo1 = new VolumeDiscount__c(
			QuoteId__c = quoteSo.Id,
			Category__c = 'Headcount',
			TotalBy__c = 'Quote'
		);
		volumeDiscountSOs.add(volumeDiscountSo1);

		VolumeDiscount__c volumeDiscountSo2 = new VolumeDiscount__c(
			QuoteId__c = quoteSo.Id,
			Category__c = 'Labor Revenue',
			TotalBy__c = 'Quote'
		);
		volumeDiscountSOs.add(volumeDiscountSo2);

		insert volumeDiscountSOs;

		VolumeDiscountTier__c[] volumeDiscountTierSOs = new VolumeDiscountTier__c[0];
		volumeDiscountTierSOs.add(
			new VolumeDiscountTier__c(
				VolumeDiscountId__c = volumeDiscountSo1.Id,
				From__c = 0,
				To__c = 10,
				Discount__c = 5,
				Sequence__c = 1
			)
		);

		volumeDiscountTierSOs.add(
			new VolumeDiscountTier__c(
				VolumeDiscountId__c = volumeDiscountSo1.Id,
				From__c = 11,
				To__c = 27,
				Discount__c = 10,
				Sequence__c = 2
			)
		);

		volumeDiscountTierSOs.add(
			new VolumeDiscountTier__c(
				VolumeDiscountId__c = volumeDiscountSo2.Id,
				From__c = 0,
				To__c = 100000,
				Discount__c = 5,
				Sequence__c = 1
			)
		);

		volumeDiscountTierSOs.add(
			new VolumeDiscountTier__c(
				VolumeDiscountId__c = volumeDiscountSo2.Id,
				From__c = 100001,
				To__c = 200000,
				Discount__c = 10,
				Sequence__c = 1
			)
		);

		insert volumeDiscountTierSOs;

		NamedRangeTotal__c totalSo = new NamedRangeTotal__c(
			QuoteId__c = quoteSo.Id,
			AdjustedBaseAmount__c = 100
		);
		CRUDUtility.insertRecords(totalSo);
		NamedRange__c namedRangeSo = new NamedRange__c(
			Name = 'Test',
			QuoteId__c = quoteSo.Id,
			NamedRangeTotalId__c = totalSo.Id,
			QuotePeriodId__c = periodSo.Id
		);
		CRUDUtility.insertRecords(namedRangeSo);
		Adjustment__c adjustmentSo = new Adjustment__c(
			NamedRangeId__c = namedRangeSo.Id,
			Amount__c = 100
		);
		CRUDUtility.insertRecords(adjustmentSo);
		AdjustmentVolumeDiscountTier__c discountTier = new AdjustmentVolumeDiscountTier__c(
			AdjustmentId__c = adjustmentSo.Id,
			VolumeDiscountTierId__c = volumeDiscountTierSOs[0].Id
		);
		CRUDUtility.insertRecords(discountTier);
	}

	@IsTest
	static void shouldRetrieveAllVolumeDiscountsForQuote() {
		Quote__c quoteSO = [SELECT Id FROM Quote__c WHERE Name = :quoteNameNo1];
		Test.startTest();
		{
			VolumeDiscountDto[] volumeDiscountDtos = VolumeDiscountController.getVolumeDiscounts(
				quoteSO.Id
			);
			System.assertEquals(2, volumeDiscountDtos.size());
		}
		Test.stopTest();
	}

	@IsTest
	static void shouldUpdateVolumeDiscountTierDiscountAmountQuote() {
		Quote__c quoteSO = [SELECT Id FROM Quote__c WHERE Name = :quoteNameNo1];
		VolumeDiscountDto[] volumeDiscountDtos = VolumeDiscountController.getVolumeDiscounts(
			quoteSO.Id
		);
		// set discount amount from 5 -> 20
		volumeDiscountDtos[0].tiers[0].discount = 20;

		Test.startTest();
		{
			volumeDiscountDtos = VolumeDiscountController.saveVolumeDiscounts(volumeDiscountDtos);
			System.assertEquals(20, volumeDiscountDtos[0].tiers[0].discount);
		}
		Test.stopTest();
	}

	@IsTest
	static void shouldDeleteAllVolumeDiscountsButTheFirstForQuote() {
		Quote__c quoteSO = [SELECT Id FROM Quote__c WHERE Name = :quoteNameNo1];
		VolumeDiscountDto[] volumeDiscountDtos = VolumeDiscountController.getVolumeDiscounts(
			quoteSO.Id
		);

		for (Integer i = 0; i < volumeDiscountDtos.size(); i++) {
			if (i > 0) {
				volumeDiscountDtos[i].operationType = 'delete';
			}
		}

		Test.startTest();
		{
			volumeDiscountDtos = VolumeDiscountController.saveVolumeDiscounts(volumeDiscountDtos);
			System.assertEquals(1, volumeDiscountDtos.size());
		}
		Test.stopTest();
	}

	@IsTest
	static void shouldReturnSummaryDtos() {
		Quote__c quoteSO = [SELECT Id FROM Quote__c WHERE Name = :quoteNameNo1];
		Test.startTest();
		{
			List<VolumeDiscountSummaryDto> summaryDtos = VolumeDiscountController.getVolumeDiscountSummary(
				quoteSO.Id
			);
			System.assertEquals(1, summaryDtos[0].appliedTierSummaries.size());
		}
		Test.stopTest();
	}
}