quoting-CypressTK1/force-app/main/default/objects/AdjustmentVolumeDiscountTier__c/AdjustmentVolumeDiscountTier__c.object-meta.xml
<CustomObject>
    <description
	>Junction object linking adjustment record to active volume discount tier record</description>
    <label>Adjustment Volume Discount Tier</label>
    <nameField>
        <displayFormat>AVDT-{00000}</displayFormat>
        <label>Adjustment Volume Discount Tier Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Adjustment Volume Discount Tiers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

quoting-CypressTK1/force-app/main/default/objects/AdjustmentVolumeDiscountTier__c/fields/AdjustmentId__c.field-meta.xml
<CustomField>
    <fullName>AdjustmentId__c</fullName>
    <description>Id of related adjustment record</description>
    <inlineHelpText>Id of related adjustment record</inlineHelpText>
    <label>Adjustment Id</label>
    <referenceTo>Adjustment__c</referenceTo>
    <relationshipLabel>Adjustment Volume Discount Tiers</relationshipLabel>
    <relationshipName>AdjustmentVolumeDiscountTiers</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

quoting-CypressTK1/force-app/main/default/objects/AdjustmentVolumeDiscountTier__c/fields/VolumeDiscountTierId__c.field-meta.xml
<CustomField>
    <fullName>VolumeDiscountTierId__c</fullName>
    <description>Id of related volume discount tier record</description>
    <inlineHelpText>Id of related volume discount tier record</inlineHelpText>
    <label>Volume Discount Tier Id</label>
    <referenceTo>VolumeDiscountTier__c</referenceTo>
    <relationshipLabel>Adjustment Volume Discount Tiers</relationshipLabel>
    <relationshipName>AdjustmentVolumeDiscountTiers</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

quoting-CypressTK1/force-app/main/default/objects/VolumeDiscount__c/VolumeDiscount__c.object-meta.xml
<CustomObject>
    <description>Contains volume discount record</description>
    <label>Volume Discount</label>
    <nameField>
        <displayFormat>QVD-{00000}</displayFormat>
        <label>Volume Discount</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Volume Discounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

quoting-CypressTK1/force-app/main/default/objects/VolumeDiscount__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <description>Picklist of available category selections for quote volume discount</description>
    <inlineHelpText>Choose your quote volume discount category</inlineHelpText>
    <label>Category</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Headcount</fullName>
                <label>Headcount Discount</label>
            </value>
            <value>
                <fullName>Labor Revenue</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

quoting-CypressTK1/force-app/main/default/objects/VolumeDiscount__c/fields/QuoteId__c.field-meta.xml
<CustomField>
    <fullName>QuoteId__c</fullName>
    <description>Relationship to parent Quote record</description>
    <inlineHelpText>Relationship to parent Quote record</inlineHelpText>
    <label>Quote</label>
    <referenceTo>Quote__c</referenceTo>
    <relationshipLabel>Volume Discounts</relationshipLabel>
    <relationshipName>VolumeDiscounts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

quoting-CypressTK1/force-app/main/default/objects/VolumeDiscount__c/fields/TotalBy__c.field-meta.xml
<CustomField>
    <fullName>TotalBy__c</fullName>
    <description
	>Selection indicating at what level to apply tier discount details to total whether at the overall quote level, quote period or period group level.</description>
    <inlineHelpText>Choose which level to apply the volume discount</inlineHelpText>
    <label>Total by</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Quote</fullName>
            </value>
            <value>
                <fullName>Period</fullName>
            </value>
            <value>
                <fullName>Period Group</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

quoting-CypressTK1/force-app/main/default/objects/VolumeDiscountTier__c/VolumeDiscountTier__c.object-meta.xml
<CustomObject>
    <description>Object holding volume discount tier details</description>
    <label>Volume Discount Tier</label>
    <nameField>
        <displayFormat>QVDT-{00000}</displayFormat>
        <label>Volume Discount Tier</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Volume Discount Tiers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

quoting-CypressTK1/force-app/main/default/objects/VolumeDiscountTier__c/fields/Discount__c.field-meta.xml
<CustomField>
    <fullName>Discount__c</fullName>
    <description>Quote volume discount tier percentage amount</description>
    <inlineHelpText>Quote volume discount tier percentage amount</inlineHelpText>
    <label>Discount</label>
    <precision>6</precision>
    <scale>3</scale>
    <type>Percent</type>
</CustomField>

quoting-CypressTK1/force-app/main/default/objects/VolumeDiscountTier__c/fields/From__c.field-meta.xml
<CustomField>
    <fullName>From__c</fullName>
    <description>Quote volume discount tier from numeric value</description>
    <inlineHelpText>Quote volume discount tier from numeric value</inlineHelpText>
    <label>From</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

quoting-CypressTK1/force-app/main/default/objects/VolumeDiscountTier__c/fields/Sequence__c.field-meta.xml
<CustomField>
    <fullName>Sequence__c</fullName>
    <description>Tier number indicating order within set of sibling records</description>
    <inlineHelpText>Tier number</inlineHelpText>
    <label>Sequence</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

quoting-CypressTK1/force-app/main/default/objects/VolumeDiscountTier__c/fields/To__c.field-meta.xml
<CustomField>
    <fullName>To__c</fullName>
    <description>Quote volume discount tier to numeric value</description>
    <inlineHelpText>Quote volume discount tier to numeric value</inlineHelpText>
    <label>To</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

quoting-CypressTK1/force-app/main/default/objects/VolumeDiscountTier__c/fields/VolumeDiscountId__c.field-meta.xml
<CustomField>
    <fullName>VolumeDiscountId__c</fullName>
    <description>Relationship to parent object Volume Discount</description>
    <inlineHelpText>Relationship to parent object Volume Discount</inlineHelpText>
    <label>Volume Discount</label>
    <referenceTo>VolumeDiscount__c</referenceTo>
    <relationshipLabel>Volume Discount Tiers</relationshipLabel>
    <relationshipName>VolumeDiscountTiers</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

quoting-CypressTK1/force-app/main/default/classes/VolumeDiscountService.cls
/**
 *  Provus Services Quoting
 *  VolumeDiscountService
 *  @2022 Provus Inc. All rights reserved.
 */
public with sharing class VolumeDiscountService {
	public static List<VolumeDiscountDto> saveVolumeDiscounts(
		List<VolumeDiscountDto> volumeDiscountDtos
	) {
		List<VolumeDiscount__c> volumeDiscountSOs = new List<VolumeDiscount__c>();

		for (Integer i = 0; i < volumeDiscountDtos.size(); i++) {
			VolumeDiscountDto volumeDiscountDto = volumeDiscountDtos[i];
			VolumeDiscount__c volumeDiscountSO = (VolumeDiscount__c) volumeDiscountDto.refreshSo();
			volumeDiscountSOs.add(volumeDiscountSO);
		}

		CRUDUtility.upsertRecords(volumeDiscountSOs);

		List<VolumeDiscountTier__c> volumeDiscountTierSOs = new List<VolumeDiscountTier__c>();
		for (Integer i = 0; i < volumeDiscountDtos.size(); i++) {
			VolumeDiscountDto volumeDiscountDto = volumeDiscountDtos[i];
			if (volumeDiscountDto.isNew) {
				Id parentVolumeDiscountId = volumeDiscountSOs[i].Id;
				for (VolumeDiscountTierDto volumeDiscountTierDto : volumeDiscountDto.tiers) {
					VolumeDiscountTier__c volDiscountTierSO = (VolumeDiscountTier__c) volumeDiscountTierDto.refreshSo();
					// associate to parent record since is new
					volDiscountTierSO.VolumeDiscountId__c = parentVolumeDiscountId;
					volumeDiscountTierSOs.add(volDiscountTierSO);
				}
			} else {
				for (VolumeDiscountTierDto volumeDiscountTierDto : volumeDiscountDto.tiers) {
					volumeDiscountTierSOs.add((VolumeDiscountTier__c) volumeDiscountTierDto.refreshSo());
				}
			}
		}

		CRUDUtility.upsertRecords(volumeDiscountTierSOs);

		// update DTO object Ids
		Integer volumeDiscountTierCount = 0;

		for (Integer i = 0; i < volumeDiscountDtos.size(); i++) {
			VolumeDiscountDto volumeDiscountDto = volumeDiscountDtos[i];
			volumeDiscountDto.id = volumeDiscountSOs[i].Id;

			for (Integer k = 0; k < volumeDiscountDto.tiers.size(); k++) {
				VolumeDiscountTierDto volumeDiscountTierDto = volumeDiscountDto.tiers[k];
				volumeDiscountTierDto.id = volumeDiscountTierSOs[volumeDiscountTierCount].Id;
				volumeDiscountTierCount++;
			}
		}

		return volumeDiscountDtos;
	}

	public static void deleteVolumeDiscounts(VolumeDiscountDto[] volumeDiscountDtos) {
		VolumeDiscount__c[] volumeDiscountSOs = new VolumeDiscount__c[0];

		for (VolumeDiscountDto volumeDiscountDto : volumeDiscountDtos) {
			// MD relationship will delete all tiers
			volumeDiscountSOs.add((VolumeDiscount__c) volumeDiscountDto.refreshSo());
		}

		CRUDUtility.deleteRecords(volumeDiscountSOs);
	}

	public static List<VolumeDiscountDto> getVolumeDiscounts(Id quoteId) {
		List<VolumeDiscountDto> volumeDiscountDtos = new List<VolumeDiscountDto>();

		List<VolumeDiscount__c> volumeDiscountSOs = [
			SELECT Id, QuoteId__c, Category__c, TotalBy__c
			FROM VolumeDiscount__c
			WHERE QuoteId__c = :quoteId
			WITH SECURITY_ENFORCED
			ORDER BY CreatedDate ASC
		];

		Set<Id> volumeDiscountIds = new Set<Id>();

		for (VolumeDiscount__c volumeDiscountSO : volumeDiscountSOs) {
			volumeDiscountIds.add(volumeDiscountSO.Id);
			volumeDiscountDtos.add(new VolumeDiscountDto(volumeDiscountSO));
		}

		List<VolumeDiscountTier__c> volumeDiscountTierSOs = [
			SELECT Id, VolumeDiscountId__c, From__c, To__c, Discount__c, Sequence__c
			FROM VolumeDiscountTier__c
			WHERE VolumeDiscountId__c IN :volumeDiscountIds
			WITH SECURITY_ENFORCED
			ORDER BY Sequence__c ASC
		];

		Map<Id, List<VolumeDiscountTierDto>> volumeDiscountTierMap = new Map<Id, List<VolumeDiscountTierDto>>();

		for (VolumeDiscountTier__c volumeDiscountTierSO : volumeDiscountTierSOs) {
			Id volumeDiscountId = volumeDiscountTierSO.VolumeDiscountId__c;

			if (!volumeDiscountTierMap.containsKey(volumeDiscountId)) {
				volumeDiscountTierMap.put(volumeDiscountId, new List<VolumeDiscountTierDto>());
			}

			volumeDiscountTierMap.get(volumeDiscountId)
				.add(new VolumeDiscountTierDto(volumeDiscountTierSO));
		}

		for (VolumeDiscountDto volumeDiscountDto : volumeDiscountDtos) {
			Id volumeDiscountId = volumeDiscountDto.id;
			if (volumeDiscountTierMap.containsKey(volumeDiscountDto.id)) {
				volumeDiscountDto.tiers = volumeDiscountTierMap.get(volumeDiscountId);
			}
		}

		return volumeDiscountDtos;
	}

	public static List<VolumeDiscountSummaryDto> getVolumeDiscountSummary(Id quoteId) {
		Map<Id, VolumeDiscountSummaryDto> discountSummaryDtosByIds = new Map<Id, VolumeDiscountSummaryDto>();

		Map<String, String> picklistValueLabelPair = new Map<String, String>();
		Schema.DescribeFieldResult fieldResult = VolumeDiscount__c.Category__c.getDescribe();
		List<Schema.PicklistEntry> ple = fieldResult.getPicklistValues();
		for (Schema.PicklistEntry pickListVal : ple) {
			picklistValueLabelPair.put(pickListVal.value, pickListVal.label);
		}

		for (AdjustmentVolumeDiscountTier__c discountTier : [
			SELECT
				Id,
				AdjustmentId__c,
				AdjustmentId__r.NamedRangeId__r.NamedRangeTotalId__r.AdjustedBaseAmount__c,
				AdjustmentId__r.NamedRangeId__r.NamedRangeTotalId__r.BaseExtendedCost__c,
				AdjustmentId__r.NamedRangeId__r.QuotePeriodGroupId__r.Name,
				AdjustmentId__r.NamedRangeId__r.QuotePeriodId__r.Name,
				AdjustmentId__r.Amount__c,
				VolumeDiscountTierId__r.From__c,
				VolumeDiscountTierId__r.To__c,
				VolumeDiscountTierId__r.Discount__c,
				VolumeDiscountTierId__r.Sequence__c,
				VolumeDiscountTierId__r.Id,
				VolumeDiscountTierId__r.VolumeDiscountId__c,
				VolumeDiscountTierId__r.VolumeDiscountId__r.Category__c,
				VolumeDiscountTierId__r.VolumeDiscountId__r.TotalBy__c,
				VolumeDiscountTierId__c
			FROM AdjustmentVolumeDiscountTier__c
			WHERE AdjustmentId__r.NamedRangeId__r.QuoteId__c = :quoteId
			WITH SECURITY_ENFORCED
			ORDER BY
				AdjustmentId__r.NamedRangeId__r.QuotePeriodGroupId__r.Sequence__c,
				AdjustmentId__r.NamedRangeId__r.QuotePeriodId__r.Sequence__c
			LIMIT :SOQLConstants.SOQL_QUERY_LIMIT
		]) {
			VolumeDiscountSummaryDto discountSummaryDto = discountSummaryDtosByIds.get(
				discountTier.VolumeDiscountTierId__r.VolumeDiscountId__c
			);
			if (discountSummaryDto == null) {
				discountSummaryDto = new VolumeDiscountSummaryDto(
					discountTier.VolumeDiscountTierId__r.VolumeDiscountId__r,
					picklistValueLabelPair
				);
			}

			discountSummaryDtosByIds.put(
				discountTier.VolumeDiscountTierId__r.VolumeDiscountId__c,
				discountSummaryDto
			);
			discountSummaryDto.appliedTierSummaries.add(
				new VolumeDiscountAppliedTierSummaryDto(discountTier)
			);
		}

		return discountSummaryDtosByIds.values();
	}
}