quoting-CypressTK1/force-app/main/default/objects/RateCardAttributeOption__c/RateCardAttributeOption__c.object-meta.xml
<CustomObject>
    <label>Rate Card Attribute Option</label>
    <nameField>
        <displayFormat>RCAO-{00000}</displayFormat>
        <label>Rate Card Attribute Option Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Rate Card Attribute Options</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

quoting-CypressTK1/force-app/main/default/objects/RateCardAttributeOption__c/fields/AttributeGroupId__c.field-meta.xml
<CustomField>
    <fullName>AttributeGroupId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Attribute Group</label>
    <referenceTo>RateCardAttributeGroup__c</referenceTo>
    <relationshipLabel>Rate Card Attribute Options</relationshipLabel>
    <relationshipName>RateCardAttributeOptions</relationshipName>
    <type>Lookup</type>
</CustomField>

quoting-CypressTK1/force-app/main/default/objects/RateCardAttributeOption__c/fields/RateCardAttributeId__c.field-meta.xml
<CustomField>
    <fullName>RateCardAttributeId__c</fullName>
    <label>Rate Card Attribute</label>
    <referenceTo>RateCardAttribute__c</referenceTo>
    <relationshipLabel>Rate Card Attribute Options</relationshipLabel>
    <relationshipName>RateCardAttributeOptions</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

quoting-CypressTK1/force-app/main/default/objects/RateCardAttributeOption__c/fields/RateCardAttributeOptionKey__c.field-meta.xml
<CustomField>
    <fullName>RateCardAttributeOptionKey__c</fullName>
    <externalId>true</externalId>
    <label>Rate Card Attribute Option Key</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

quoting-CypressTK1/force-app/main/default/objects/RateCardAttributeOption__c/fields/RateCardId__c.field-meta.xml
<CustomField>
    <fullName>RateCardId__c</fullName>
    <label>Rate Card</label>
    <referenceTo>RateCard__c</referenceTo>
    <relationshipLabel>Rate Card Attribute Options</relationshipLabel>
    <relationshipName>RateCardAttributeOptions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

quoting-CypressTK1/force-app/main/default/objects/RateCardAttributeOption__c/fields/TextValue__c.field-meta.xml
<CustomField>
    <fullName>TextValue__c</fullName>
    <label>Text Value</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

quoting-CypressTK1/force-app/main/default/objects/RateCardItemAttributeOption__c/RateCardItemAttributeOption__c.object-meta.xml
<CustomObject>
    <label>Rate Card Item Attribute Option</label>
    <nameField>
        <displayFormat>RCIAO-{00000}</displayFormat>
        <label>Rate Card Item Attribute Option</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Rate Card Item Attribute Options</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

quoting-CypressTK1/force-app/main/default/objects/RateCardItemAttributeOption__c/fields/AttributeOptionId__c.field-meta.xml
<CustomField>
    <fullName>AttributeOptionId__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Attribute Option</label>
    <referenceTo>RateCardAttributeOption__c</referenceTo>
    <relationshipLabel>Rate Card Items Attribute Options</relationshipLabel>
    <relationshipName>RateCardItemAttributeOptions</relationshipName>
    <type>Lookup</type>
</CustomField>

quoting-CypressTK1/force-app/main/default/objects/RateCardItemAttributeOption__c/fields/RateCardItemAttributeKey__c.field-meta.xml
<CustomField>
    <fullName>RateCardItemAttributeKey__c</fullName>
    <externalId>true</externalId>
    <label>Rate Card Item Attribute Key</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

quoting-CypressTK1/force-app/main/default/objects/RateCardItemAttributeOption__c/fields/RateCardItemId__c.field-meta.xml
<CustomField>
    <fullName>RateCardItemId__c</fullName>
    <label>Rate Card Item</label>
    <referenceTo>RateCardItem__c</referenceTo>
    <relationshipLabel>Rate Card Item Attribute Options</relationshipLabel>
    <relationshipName>RateCardItemAttributeOptions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

quoting-CypressTK1/force-app/main/default/classes/RateCardItemTriggers.cls
/**
 *  Provus Services Quoting
 *  RateCardItemTriggers
 *  @2022 Provus Inc. All rights reserved.
 *
 */
public with sharing class RateCardItemTriggers extends TriggerHandler {
	public static void processTrigger(
		Map<Id, RateCardItem__c> oldMap,
		List<RateCardItem__c> newObjs,
		Boolean isBefore
	) {
		final RateCardItemTriggers myTrigger = new RateCardItemTriggers(oldMap, newObjs, isBefore);
		if (isBefore) {
			myTrigger.setLocationDisplayName();
		} else {
			// save the available options in this rate card to be used for filter
			// searches in the future
			myTrigger.saveRateCardAttributeOptions();
		}
	}

	public RateCardItemTriggers(
		Map<Id, RateCardItem__c> oldMap,
		List<RateCardItem__c> newObjs,
		Boolean isBefore
	) {
		super(oldMap, newObjs, isBefore);
	}

	public void setLocationDisplayName() {
		if (isDelete) {
			return;
		}

		for (RateCardItem__c rateCardItem : (List<RateCardItem__c>) newObjs) {
			rateCardItem.LocationDisplayName__c = rateCardItem.LocationCountry__c;
			if (String.isNotBlank(rateCardItem.LocationStateProvince__c)) {
				// location state is dependent on location country. so if state is populated, the country
				// is also populated with a value
				rateCardItem.LocationDisplayName__c += '/' + rateCardItem.LocationStateProvince__c;
			}

			if (
				String.isNotBlank(rateCardItem.LocationDisplayName__c) &&
				String.isNotBlank(rateCardItem.LocationCity__c)
			) {
				rateCardItem.LocationDisplayName__c += '/' + rateCardItem.LocationCity__c;
			} else if (String.isNotBlank(rateCardItem.LocationCity__c)) {
				rateCardItem.LocationDisplayName__c = rateCardItem.LocationCity__c;
			}
		}
	}

	private void saveRateCardAttributeOptions() {
		if (isDelete) {
			return;
		}

		Set<Id> ctxRateCardIds = new Set<Id>();
		for (RateCardItem__c existingItem : (List<RateCardItem__c>) newObjs) {
			ctxRateCardIds.add(existingItem.RateCardId__c);
		}

		Map<Id, Id> rateCardToAttributeGroupId = RateCardService.getAttributeGroupIdsForRateCards(
			ctxRateCardIds
		);
		Map<Id, List<RateCardAttribute__c>> attributesByGroupId = RateCardAttributeGroupService.getAttributesForGroups(
			rateCardToAttributeGroupId.values()
		);

		associateRateCardItemsToAttributeOptions(
			newObjs,
			rateCardToAttributeGroupId,
			attributesByGroupId
		);
	}

	private void associateRateCardItemsToAttributeOptions(
		List<RateCardItem__c> ctxRateCardItems,
		Map<Id, Id> rateCardToAttributeGroupId,
		Map<Id, List<RateCardAttribute__c>> attributesByGroupId
	) {
		Map<String, RateCardAttributeOption__c> rateCardAttributeOptionsToUpsert = new Map<String, RateCardAttributeOption__c>();
		List<RateCardItemAttributeOption__c> rateCardItemAttributeOptionsToUpsert = new List<RateCardItemAttributeOption__c>();
		Set<String> rateCardItemOptionsToDelete = new Set<String>();
		for (RateCardItem__c existingItem : ctxRateCardItems) {
			Id attributeGroupId = rateCardToAttributeGroupId.get(existingItem.RateCardId__c);
			List<RateCardAttribute__c> rateCardAttributes = attributesByGroupId.get(attributeGroupId);

			if (rateCardAttributes == null) {
				continue;
			}

			for (RateCardAttribute__c attribute : rateCardAttributes) {
				Object attributeValue = existingItem.get(attribute.FieldAPIName__c);
				String attributeItemKey = existingItem.Id + attribute.FieldAPIName__c;
				if (attributeValue == null) {
					rateCardItemOptionsToDelete.add(attributeItemKey);
				} else {
					String attributeOptionKey =
						existingItem.RateCardId__c +
						':' +
						attribute.FieldAPIName__c +
						':' +
						attributeValue;
					RateCardAttributeOption__c attributeOption = new RateCardAttributeOption__c(
						RateCardAttributeOptionKey__c = attributeOptionKey,
						TextValue__c = String.valueOf(attributeValue),
						AttributeGroupId__c = attribute.AttributeGroupId__c,
						RateCardAttributeId__c = attribute.Id,
						RateCardId__c = existingItem.RateCardId__c
					);
					rateCardAttributeOptionsToUpsert.put(attributeOptionKey, attributeOption);

					RateCardItemAttributeOption__c rateCardItemOption = new RateCardItemAttributeOption__c(
						AttributeOptionId__r = new RateCardAttributeOption__c(
							RateCardAttributeOptionKey__c = attributeOptionKey
						),
						RateCardItemId__c = existingItem.Id,
						RateCardItemAttributeKey__c = attributeItemKey
					);
					rateCardItemAttributeOptionsToUpsert.add(rateCardItemOption);
				}
			}
		}

		CRUDUtility.upsertRecords(
			rateCardAttributeOptionsToUpsert.values(),
			RateCardAttributeOption__c.RateCardAttributeOptionKey__c
		);
		CRUDUtility.upsertRecords(
			rateCardItemAttributeOptionsToUpsert,
			RateCardItemAttributeOption__c.RateCardItemAttributeKey__c
		);
	}
}