quoting-CypressTK1/force-app/main/default/objects/ScopeParameter__c/ScopeParameter__c.object-meta.xml
<CustomObject>
    <label>Scope Parameter</label>
    <nameField>
        <label>Scope Parameter Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Scope Parameters</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

quoting-CypressTK1/force-app/main/default/objects/ScopeParameter__c/fields/EstimateId__c.field-meta.xml
<CustomField>
    <fullName>EstimateId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Estimate</label>
    <referenceTo>Estimate__c</referenceTo>
    <relationshipLabel>Scope Parameters</relationshipLabel>
    <relationshipName>ScopeParameters</relationshipName>
    <type>Lookup</type>
</CustomField>

quoting-CypressTK1/force-app/main/default/classes/ScopeParameterTestBase.cls
/*
 * Provus Services Quoting
 * Copyright (c) 2022 Provus Inc. All rights reserved.
 */
@IsTest
public class ScopeParameterTestBase {
	public static ScopeParameter__c newIntegerScopeParameter(Id estimateId) {
		ScopeParameter__c scopeParameterSo = new ScopeParameter__c(
			EstimateId__c = estimateId,
			DataType__c = ScopeParameterService.DATATYPE_INTEGER
		);
		CRUDUtility.insertRecords(scopeParameterSo);
		return scopeParameterSo;
	}
}