quoting-CypressTK1/force-app/main/default/objects/ScopeParameter__c/ScopeParameter__c.object-meta.xml
<CustomObject>
    <label>Scope Parameter</label>
    <nameField>
        <label>Scope Parameter Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Scope Parameters</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

quoting-CypressTK1/force-app/main/default/objects/ScopeParameter__c/fields/TemplateId__c.field-meta.xml
<CustomField>
    <fullName>TemplateId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Scope Parameter Template</label>
    <referenceTo>ScopeParameterTemplate__c</referenceTo>
    <relationshipName>ScopeParameters</relationshipName>
    <type>Lookup</type>
</CustomField>

quoting-CypressTK1/force-app/main/default/objects/TaskParameterValue__c/fields/ScopeParameterId__c.field-meta.xml
<CustomField>
    <fullName>ScopeParameterId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Scope Parameter</label>
    <referenceTo>ScopeParameter__c</referenceTo>
    <relationshipLabel>Task Parameter Values</relationshipLabel>
    <relationshipName>TaskParameterValues</relationshipName>
    <type>Lookup</type>
</CustomField>

quoting-CypressTK1/force-app/main/default/classes/ScopeParameterServiceTest.cls
/*
 * Provus Services Quoting
 * Copyright (c) 2022 Provus Inc. All rights reserved.
 */

@IsTest
private class ScopeParameterServiceTest {
	@IsTest
	static void shouldUpdateScopeParamTextValue() {
		ScopeParameter__c paramSo = new ScopeParameter__c();
		paramSo.Sequence__c = 1;
		paramSo.DeveloperName__c = 'test';
		paramSo.TextValue__c = 'test';
		paramSo.DataType__c = EstimatorConstants.PICKLIST;
		CRUDUtility.insertRecords(paramSo);

		ScopeParameterValueDto paramDto = new ScopeParameterValueDto(paramSo);
		paramDto.textValue = 'new value';

		ActivityGroupTemplate__c activityGroupSo = new ActivityGroupTemplate__c();
		CRUDUtility.insertRecords(activityGroupSo);

		ActivityTemplate__c activityTemplateSo = new ActivityTemplate__c(
			ActivityGroupTemplateId__c = activityGroupSo.Id
		);
		CRUDUtility.insertRecords(activityTemplateSo);

		TaskTemplate__c taskTemplateSo = new TaskTemplate__c(
			ActivityTemplateId__c = activityTemplateSo.Id
		);
		CRUDUtility.insertRecords(taskTemplateSo);

		TaskParameterTemplate__c parameterTemplateSo = new TaskParameterTemplate__c(
			TaskTemplateId__c = taskTemplateSo.Id,
			IsActive__c = true
		);
		CRUDUtility.insertRecords(parameterTemplateSo);

		TaskParameterValue__c paramValueSo = new TaskParameterValue__c(
			ScopeParameterId__c = paramSo.Id,
			TemplateId__c = parameterTemplateSo.Id
		);
		CRUDUtility.insertRecords(paramValueSo);

		Test.startTest();
		{
			ScopeParameterService.saveScopeParameters(new List<ScopeParameterValueDto>{ paramDto });
			ScopeParameter__c updatedParamSo = [
				SELECT TextValue__c
				FROM ScopeParameter__c
				WHERE Id = :paramSo.Id
			];
			System.assertEquals('new value', updatedParamSo.TextValue__c);
		}
		Test.stopTest();
	}
}