quoting-CypressTK1/force-app/main/default/objects/COLARate__c/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <label>City</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

quoting-CypressTK1/force-app/main/default/objects/COLARate__c/fields/PassthroughPercentage__c.field-meta.xml
<CustomField>
    <fullName>PassthroughPercentage__c</fullName>
    <label>Pass-through Percentage</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Percent</type>
</CustomField>

quoting-CypressTK1/force-app/main/default/objects/COLARate__c/fields/PassthroughRateOverride__c.field-meta.xml
<CustomField>
    <fullName>PassthroughRateOverride__c</fullName>
    <label>Pass-through Rate Override</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Percent</type>
</CustomField>

quoting-CypressTK1/force-app/main/default/objects/COLARate__c/fields/RateMatch__c.field-meta.xml
<CustomField>
    <fullName>RateMatch__c</fullName>
    <formula>IF(NOT(ISBLANK(City__c)), &apos;City&apos;,
IF(NOT(ISBLANK(TEXT(State__c))), &apos;State&apos;,
IF(NOT(ISBLANK(TEXT(Country__c))), &apos;Country&apos;,
&apos;Global&apos;)))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Rate Match</label>
    <type>Text</type>
</CustomField>

quoting-CypressTK1/force-app/main/default/objects/COLARate__c/fields/RateOverride__c.field-meta.xml
<CustomField>
    <fullName>RateOverride__c</fullName>
    <label>Rate Override</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Percent</type>
</CustomField>

quoting-CypressTK1/force-app/main/default/objects/COLARate__c/fields/ServiceYear__c.field-meta.xml
<CustomField>
    <fullName>ServiceYear__c</fullName>
    <label>Service Year</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

quoting-CypressTK1/force-app/main/default/objects/COLARate__c/fields/YearOverYearRate__c.field-meta.xml
<CustomField>
    <fullName>YearOverYearRate__c</fullName>
    <label>Year Over Year Rate</label>
    <precision>18</precision>
    <required>true</required>
    <scale>5</scale>
    <type>Percent</type>
</CustomField>

quoting-CypressTK1/force-app/main/default/classes/ColaRateDtoTest.cls
/*
 * Provus Services Quoting
 * Copyright (c) 2022 Provus Inc. All rights reserved.
 */
@IsTest
private class ColaRateDtoTest extends ColaRateSheetTestBase {
	@IsTest
	static void shouldCreateGlobalRate() {
		ColaRateSheet__c rateSheet = newColaRateSheet();
		ColaRate__c rateSo = new ColaRate__c(
			RateSheetId__c = rateSheet.Id,
			ServiceYear__c = Date.today().year(),
			YearOverYearRate__c = 1
		);
		CRUDUtility.insertRecords(rateSo);

		Test.startTest();
		ColaRateDto rateDto = new ColaRateDto(
			[
				SELECT
					ServiceYear__c,
					Country__c,
					State__c,
					City__c,
					RateMatch__c,
					YearOverYearRate__c,
					RateOverride__c,
					PassthroughPercentage__c,
					PassthroughRateOverride__c
				FROM ColaRate__c
				WHERE Id = :rateSo.Id
			]
		);
		System.assert(rateDto.serviceYear == Date.today().year(), 'should have the current year');
		System.assert(
			rateDto.rateMatch == ColaRate.RATE_MATCH_GLOBAL,
			'should have a global rate match'
		);
		Test.stopTest();
	}

	@IsTest
	static void shouldCreateCountryRate() {
		ColaRateSheet__c rateSheet = newColaRateSheet();
		ColaRate__c rateSo = new ColaRate__c(
			RateSheetId__c = rateSheet.Id,
			ServiceYear__c = Date.today().year(),
			Country__c = 'United States',
			YearOverYearRate__c = 1
		);
		CRUDUtility.insertRecords(rateSo);

		Test.startTest();
		ColaRateDto rateDto = new ColaRateDto(
			[
				SELECT
					ServiceYear__c,
					Country__c,
					State__c,
					City__c,
					RateMatch__c,
					YearOverYearRate__c,
					RateOverride__c,
					PassthroughPercentage__c,
					PassthroughRateOverride__c
				FROM ColaRate__c
				WHERE Id = :rateSo.Id
			]
		);
		System.assert(rateDto.serviceYear == Date.today().year(), 'should have the current year');
		System.assert(
			rateDto.rateMatch == ColaRate.RATE_MATCH_COUNTRY,
			'should have a country rate match'
		);
		Test.stopTest();
	}

	@IsTest
	static void shouldCreateStateRate() {
		ColaRateSheet__c rateSheet = newColaRateSheet();
		ColaRate__c rateSo = new ColaRate__c(
			RateSheetId__c = rateSheet.Id,
			ServiceYear__c = Date.today().year(),
			Country__c = 'United States',
			State__c = 'California',
			YearOverYearRate__c = 1
		);
		CRUDUtility.insertRecords(rateSo);

		Test.startTest();
		ColaRateDto rateDto = new ColaRateDto(
			[
				SELECT
					ServiceYear__c,
					Country__c,
					State__c,
					City__c,
					RateMatch__c,
					YearOverYearRate__c,
					RateOverride__c,
					PassthroughPercentage__c,
					PassthroughRateOverride__c
				FROM ColaRate__c
				WHERE Id = :rateSo.Id
			]
		);
		System.assert(rateDto.serviceYear == Date.today().year(), 'should have the current year');
		System.assert(rateDto.rateMatch == ColaRate.RATE_MATCH_STATE, 'should have a state rate match');
		Test.stopTest();
	}

	@IsTest
	static void shouldCreateCityRate() {
		ColaRateSheet__c rateSheet = newColaRateSheet();
		ColaRate__c rateSo = new ColaRate__c(
			RateSheetId__c = rateSheet.Id,
			ServiceYear__c = Date.today().year(),
			Country__c = 'United States',
			State__c = 'California',
			City__c = 'San Jose',
			YearOverYearRate__c = 1
		);
		CRUDUtility.insertRecords(rateSo);

		Test.startTest();
		ColaRateDto rateDto = new ColaRateDto(
			[
				SELECT
					ServiceYear__c,
					Country__c,
					State__c,
					City__c,
					RateMatch__c,
					YearOverYearRate__c,
					RateOverride__c,
					PassthroughPercentage__c,
					PassthroughRateOverride__c
				FROM ColaRate__c
				WHERE Id = :rateSo.Id
			]
		);
		System.assert(rateDto.serviceYear == Date.today().year(), 'should have the current year');
		System.assert(rateDto.rateMatch == ColaRate.RATE_MATCH_CITY, 'should have a city rate match');
		Test.stopTest();
	}
}