quoting-CypressTK1/force-app/main/default/objects/COLARate__c/fields/ServiceYear__c.field-meta.xml
<CustomField>
    <fullName>ServiceYear__c</fullName>
    <label>Service Year</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

quoting-CypressTK1/force-app/main/default/objects/COLARate__c/fields/YearOverYearRate__c.field-meta.xml
<CustomField>
    <fullName>YearOverYearRate__c</fullName>
    <label>Year Over Year Rate</label>
    <precision>18</precision>
    <required>true</required>
    <scale>5</scale>
    <type>Percent</type>
</CustomField>

quoting-CypressTK1/force-app/main/default/classes/ColaRateTestBase.cls
/*
 * Provus Services Quoting
 * Copyright (c) 2022 Provus Inc. All rights reserved.
 */
@IsTest
public with sharing class ColaRateTestBase extends TestBase {
	public static ColaRate__c newColaRate(Id rateSheetId) {
		ColaRate__c rate = new ColaRate__c(
			RateSheetId__c = rateSheetId,
			ServiceYear__c = Date.today().year(),
			YearOverYearRate__c = 1
		);
		CRUDUtility.insertRecords(rate);
		return rate;
	}
}