quoting-CypressTK1/force-app/main/default/objects/COLARate__c/fields/YearOverYearRate__c.field-meta.xml
<CustomField>
    <fullName>YearOverYearRate__c</fullName>
    <label>Year Over Year Rate</label>
    <precision>18</precision>
    <required>true</required>
    <scale>5</scale>
    <type>Percent</type>
</CustomField>

quoting-CypressTK1/force-app/main/default/objects/COLARateSheet__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Quote</fullName>
                <default>true</default>
                <label>Quote</label>
            </value>
            <value>
                <fullName>Global</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

quoting-CypressTK1/force-app/main/default/classes/ColaRateServiceTest.cls
/*
 * Provus Services Quoting
 * Copyright (c) 2022 Provus Inc. All rights reserved.
 */

@IsTest
private class ColaRateServiceTest extends ColaRateSheetTestBase {
	@IsTest
	static void shouldAllowZeroRateForNonGlobalRate() {
		ColaRateSheet__c rateSheet = newColaRateSheet();
		rateSheet.Type__c = ColaRateSheet.TYPE_QUOTE;
		CRUDUtility.upsertRecords(rateSheet);

		ColaRate__c rate = ColaRateTestBase.newColaRate(rateSheet.Id);
		ColaRateDto rateDto = new ColaRateDto(rate);
		Test.startTest();
		{
			rateDto.yearOverYearRate = 0;
			ColaRateService.saveColaRates(new List<ColaRateDto>{ rateDto });
			ColaRate__c updatedRate = [SELECT YearOverYearRate__c FROM ColaRate__c WHERE Id = :rate.Id];

			System.assertEquals(0, updatedRate.YearOverYearRate__c);
		}
		Test.stopTest();
	}

	@IsTest
	static void shouldNotAllowNegativeRateForNonGlobalRate() {
		ColaRateSheet__c rateSheet = newColaRateSheet();
		rateSheet.Type__c = ColaRateSheet.TYPE_QUOTE;
		CRUDUtility.upsertRecords(rateSheet);

		ColaRate__c rate = ColaRateTestBase.newColaRate(rateSheet.Id);
		ColaRateDto rateDto = new ColaRateDto(rate);
		Test.startTest();
		{
			rateDto.yearOverYearRate = -1;
			try {
				ColaRateService.saveColaRates(new List<ColaRateDto>{ rateDto });
			} catch (Exception e) {
			}
			ColaRate__c updatedRate = [SELECT YearOverYearRate__c FROM ColaRate__c WHERE Id = :rate.Id];

			System.assertEquals(1, updatedRate.YearOverYearRate__c);
		}
		Test.stopTest();
	}
}