quoting-CypressTK1/force-app/main/default/objects/Activity__c/fields/Path__c.field-meta.xml
<CustomField>
    <fullName>Path__c</fullName>
    <formula
	>IF(TEXT(ActivityGroupId__r.PhaseId__r.Sequence__c)&lt;&gt; &apos;0&apos; &amp;&amp;  ActivityGroupId__r.EstimateId__r.UseProjectPhases__c == true,  
TEXT(ActivityGroupId__r.PhaseId__r.Sequence__c) + &apos;.&apos;, '') + TEXT(ActivityGroupId__r.Sequence__c)+&apos;.&apos;+ TEXT(Sequence__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Path</label>
    <type>Text</type>
</CustomField>

quoting-CypressTK1/force-app/main/default/objects/ActivityGroup__c/fields/PhaseId__c.field-meta.xml
<CustomField>
    <fullName>PhaseId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Phase</label>
    <referenceTo>Phase__c</referenceTo>
    <relationshipLabel>Phases</relationshipLabel>
    <relationshipName>Phases</relationshipName>
    <type>Lookup</type>
</CustomField>

quoting-CypressTK1/force-app/main/default/objects/Estimate__c/fields/UseProjectPhases__c.field-meta.xml
<CustomField>
    <fullName>UseProjectPhases__c</fullName>
    <defaultValue>false</defaultValue>
    <description
	>When enabled, Estimate will use Project Phases as their top level grouping item rather than Activity Groups</description>
    <label>Use Project Phases</label>
    <type>Checkbox</type>
</CustomField>

quoting-CypressTK1/force-app/main/default/objects/Phase__c/Phase__c.object-meta.xml
<CustomObject>
    <label>Phase</label>
    <nameField>
        <label>Phase Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Phases</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

quoting-CypressTK1/force-app/main/default/objects/Phase__c/fields/EstimateId__c.field-meta.xml
<CustomField>
    <fullName>EstimateId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Estimate</label>
    <referenceTo>Estimate__c</referenceTo>
    <relationshipLabel>Phases</relationshipLabel>
    <relationshipName>Phases</relationshipName>
    <type>Lookup</type>
</CustomField>

quoting-CypressTK1/force-app/main/default/objects/Product__c/Product__c.object-meta.xml
<CustomObject>
	<description>Provus Product object</description>
	<label>Product</label>
	<nameField>
		<label>Product Name</label>
		<type>Text</type>
	</nameField>
	<pluralLabel>Products</pluralLabel>
	<sharingModel>ReadWrite</sharingModel>
</CustomObject>

quoting-CypressTK1/force-app/main/default/objects/Product__c/fields/Description__c.field-meta.xml
<CustomField>
	<fullName>Description__c</fullName>
	<label>Product Description</label>
	<type>TextArea</type>
</CustomField>

quoting-CypressTK1/force-app/main/default/objects/Product__c/fields/IsActive__c.field-meta.xml
<CustomField>
	<fullName>IsActive__c</fullName>
	<defaultValue>true</defaultValue>
	<description>Product Active</description>
	<label>Active</label>
	<type>Checkbox</type>
</CustomField>

quoting-CypressTK1/force-app/main/default/objects/Product__c/recordTypes/ResourceRole.recordType-meta.xml
<RecordType>
	<fullName>ResourceRole</fullName>
	<active>true</active>	
	<label>Resource Role</label>
</RecordType>

quoting-CypressTK1/force-app/main/default/objects/Task__c/fields/Path__c.field-meta.xml
<CustomField>
    <fullName>Path__c</fullName>
    <formula
	>IF(TEXT(ActivityGroupId__r.PhaseId__r.Sequence__c)&lt;&gt; &apos;0&apos; &amp;&amp;  ActivityGroupId__r.EstimateId__r.UseProjectPhases__c == true,  
TEXT(ActivityGroupId__r.PhaseId__r.Sequence__c) + &apos;.&apos;, '') + TEXT(ActivityId__r.ActivityGroupId__r.Sequence__c) +&apos;.&apos; + TEXT(ActivityId__r.Sequence__c) +&apos;.&apos; +  TEXT(Sequence__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Path</label>
    <type>Text</type>
</CustomField>

quoting-CypressTK1/force-app/main/default/objects/Task__c/fields/PhaseId__c.field-meta.xml
<CustomField>
    <fullName>PhaseId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Phase</label>
    <referenceTo>Phase__c</referenceTo>
    <relationshipLabel>Tasks</relationshipLabel>
    <relationshipName>Tasks</relationshipName>
    <type>Lookup</type>
</CustomField>

quoting-CypressTK1/force-app/main/default/objects/Task__c/fields/ResourceRoleId__c.field-meta.xml
<CustomField>
    <fullName>ResourceRoleId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Resource Role</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Product__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Resource Role</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Product__c</referenceTo>
    <relationshipLabel>Tasks</relationshipLabel>
    <relationshipName>Tasks</relationshipName>
    <type>Lookup</type>
</CustomField>

quoting-CypressTK1/force-app/main/default/objects/TaskRoleSummary__c/fields/EstimatedDuration__c.field-meta.xml
<CustomField>
    <fullName>EstimatedDuration__c</fullName>
    <label>Estimated duration</label>
    <summarizedField>Task__c.EstimatedDuration__c</summarizedField>
    <summaryForeignKey>Task__c.RoleSummaryId__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

quoting-CypressTK1/force-app/main/default/objects/TaskRoleSummary__c/fields/LevelAdjustment__c.field-meta.xml
<CustomField>
    <fullName>LevelAdjustment__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Level adjustment</label>
    <precision>18</precision>
    <scale>5</scale>
    <type>Number</type>
</CustomField>

quoting-CypressTK1/force-app/main/default/objects/TaskRoleSummary__c/fields/PhaseId__c.field-meta.xml
<CustomField>
    <fullName>PhaseId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Phase</label>
    <referenceTo>Phase__c</referenceTo>
    <relationshipLabel>Role Summaries</relationshipLabel>
    <relationshipName>RoleSummaries</relationshipName>
    <type>Lookup</type>
</CustomField>

quoting-CypressTK1/force-app/main/default/objects/TaskRoleSummary__c/fields/ResourceRoleId__c.field-meta.xml
<CustomField>
    <fullName>ResourceRoleId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Resource Role</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Product__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Resource Role</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Product__c</referenceTo>
    <relationshipName>LevelSummaries</relationshipName>
    <type>Lookup</type>
</CustomField>

quoting-CypressTK1/force-app/main/default/objects/TaskRoleSummary__c/fields/TotalAdjustments__c.field-meta.xml
<CustomField>
    <fullName>TotalAdjustments__c</fullName>
    <formula>RolledUpAdjustments__c + LevelAdjustments__c + LevelAdjustment__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total adjustments</label>
    <precision>18</precision>
    <scale>5</scale>
    <type>Number</type>
</CustomField>

quoting-CypressTK1/force-app/main/default/objects/TaskRoleSummary__c/fields/TotalCalculatedDuration__c.field-meta.xml
<CustomField>
    <fullName>TotalCalculatedDuration__c</fullName>
    <formula>RolledUpCalculatedDuration__c + CalculatedDuration__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total calculated duration</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

quoting-CypressTK1/force-app/main/default/objects/TaskRoleSummary__c/fields/TotalEstimatedDuration__c.field-meta.xml
<CustomField>
    <fullName>TotalEstimatedDuration__c</fullName>
    <formula>TotalCalculatedDuration__c + TotalAdjustments__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total estimated duration</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

quoting-CypressTK1/force-app/main/default/classes/EstimateTreeController.cls
/*
 * Provus Services Quoting
 * Copyright (c) 2022 Provus Inc. All rights reserved.
 */
public with sharing class EstimateTreeController {
	//This method is used for fetching the tree structure..
	@AuraEnabled(Cacheable=true)
	public static Object getRecords(String estimateId) {
		Estimate__c estimate = [
			SELECT Id, Name, UseProjectPhases__c
			FROM Estimate__c
			WHERE Id = :estimateId
			WITH SECURITY_ENFORCED
		];

		if (estimate.UseProjectPhases__c) {
			return getPhases(estimateId);
		} else {
			return getActivityGroups(estimateId);
		}
	}

	private static Object getActivityGroups(String estimateId) {
		Map<String, List<ActivityGroup__c>> estimateToActivityGroupMap = new Map<String, List<ActivityGroup__c>>();
		List<ActivityGroup__c> activityGroups = [
			SELECT
				Id,
				Name,
				Sequence__c,
				TotalCalculatedDuration__c,
				TotalAdjustments__c,
				TotalEstimatedDuration__c,
				TotalLevelAdjustments__c,
				IsNotApplicable__c
			FROM ActivityGroup__c
			WHERE EstimateId__c = :estimateId
			WITH SECURITY_ENFORCED
			ORDER BY Sequence__c ASC
		];
		estimateToActivityGroupMap.put(estimateId, activityGroups);
		return getActivityGroups(estimateToActivityGroupMap, null, new List<String>());
	}

	private static Object getActivityGroups(
		Map<String, List<ActivityGroup__c>> estimateToActivityGroupMap,
		Phase__c phase,
		List<String> gridExpandedIds
	) {
		String estimateId;
		List<ActivityGroup__c> activityGroups = new List<ActivityGroup__c>();

		for (String estId : estimateToActivityGroupMap.keyset()) {
			estimateId = estId;
			activityGroups = estimateToActivityGroupMap.get(estId);
		}

		//Querying the Activity, Tasks..
		Map<Id, List<Activity__c>> activityGroupActivityMap = mapActivitiesByGroupId(activityGroups);

		//Querying the Summary role records at the Activitygroup level for the Resources..
		Map<Id, String> roleSumMp = roleSummaryMap(estimateId);

		//Forming the JSON structure.
		List<Object> objlst = new List<Object>();
		for (ActivityGroup__c ag : activityGroups) {
			//Building the Activity Groups
			Map<String, Object> aGmp = new Map<String, Object>();
			aGmp.put('Type', EstimateTreeSupport.ACTIVITY_GROUP);
			String sequence = ag.Sequence__c + ' ';
			if (phase != null) {
				sequence = phase.Sequence__c + '.' + ag.Sequence__c + ' ';
			}
			aGmp.put(EstimateTreeSupport.ACTIVITY_GROUP, sequence + ag.Name);
			aGmp.put('ActivityGroupName', ag.Name);
			aGmp.put('ActivityGroupId', ag.Id);
			aGmp.put('EstimatedDuration', ag.TotalEstimatedDuration__c);
			aGmp.put('AdjustedDuration', ag.TotalAdjustments__c);
			aGmp.put('LevelAdjustments', ag.TotalLevelAdjustments__c);
			aGmp.put('CalculatedDuration', ag.TotalCalculatedDuration__c);
			aGmp.put('IconType', 'standard:work_type_group');
			aGmp.put('NotApplicable', ag.IsNotApplicable__c);
			aGmp.put('ActionbuttonTitle', 'Resource Summary');
			aGmp.put('ActionIcon', 'action:share_poll');
			gridExpandedIds.add(ag.Id);
			if (activityGroupActivityMap.containsKey(ag.Id)) {
				aGmp.put(
					'_children',
					EstimateTreeSupport.createActivityAndTask(
						activityGroupActivityMap.get(ag.Id),
						gridExpandedIds,
						roleSumMp
					)
				);
			}
			if (roleSumMp.containsKey(ag.Id)) {
				aGmp.put('Resourcerole', roleSumMp.get(ag.Id));
			}
			objlst.add(aGmp);
		}

		if (phase == null) {
			return finalValues(objlst, gridExpandedIds);
		}
		return objlst;
	}

	private static List<Object> finalValues(List<Object> objlst, List<String> gridExpandedIds) {
		for (object obj : objlst) {
			Map<String, Object> mapRecord = (Map<String, Object>) obj;
			mapRecord.put('gridExpandedIds', gridExpandedIds);
			break;
		}
		return objlst;
	}

	private static Object getPhases(Id estimateId) {
		List<Phase__c> phases = [
			SELECT
				Id,
				Name,
				Description__c,
				Guidance__c,
				Sequence__c,
				IsNotApplicable__c,
				TotalEstimatedDuration__c,
				TotalAdjustments__c,
				TotalLevelAdjustments__c,
				TotalCalculatedDuration__c
			FROM Phase__c
			WHERE EstimateId__c = :estimateId AND IsActive__c = TRUE
			WITH SECURITY_ENFORCED
		];

		Map<Id, List<ActivityGroup__c>> activityGroupByPhaseId = new Map<Id, List<ActivityGroup__c>>();
		for (ActivityGroup__c activityGroup : [
			SELECT
				Id,
				Name,
				Sequence__c,
				PhaseId__c,
				TotalCalculatedDuration__c,
				TotalAdjustments__c,
				TotalEstimatedDuration__c,
				TotalLevelAdjustments__c,
				IsNotApplicable__c
			FROM ActivityGroup__c
			WHERE EstimateId__c = :estimateId
			WITH SECURITY_ENFORCED
			ORDER BY PhaseId__c, Sequence__c ASC
		]) {
			if (!activityGroupByPhaseId.containsKey(activityGroup.PhaseId__c)) {
				activityGroupByPhaseId.put(activityGroup.PhaseId__c, new List<ActivityGroup__c>());
			}

			activityGroupByPhaseId.get(activityGroup.PhaseId__c).add(activityGroup);
		}

		//Querying the Summary role records at the Activitygroup level for the Resources.
		List<String> gridExpandedIds = new List<String>();
		List<Object> objlst = new List<Object>();
		for (Phase__c phase : phases) {
			//Building the Phases
			Map<String, Object> aGmp = new Map<String, Object>();
			aGmp.put('Type', EstimateTreeSupport.PHASE);
			aGmp.put(EstimateTreeSupport.ACTIVITY_GROUP, phase.Sequence__c + ' ' + phase.Name);
			aGmp.put('ActivityGroupName', phase.Name);
			aGmp.put('ActivityGroupId', phase.Id);
			aGmp.put('EstimatedDuration', phase.TotalEstimatedDuration__c);
			aGmp.put('AdjustedDuration', phase.TotalAdjustments__c);
			aGmp.put('LevelAdjustments', phase.TotalLevelAdjustments__c);
			aGmp.put('CalculatedDuration', phase.TotalCalculatedDuration__c);
			aGmp.put('IconType', 'standard:event');
			aGmp.put('NotApplicable', phase.IsNotApplicable__c);
			aGmp.put('ActionbuttonTitle', 'Resource Summary');
			aGmp.put('ActionIcon', 'action:share_poll');
			gridExpandedIds.add(phase.Id);
			Map<string, List<ActivityGroup__c>> estimateToActivityGroupMap = new Map<string, List<ActivityGroup__c>>();
			estimateToActivityGroupMap.put(estimateId, activityGroupByPhaseId.get(phase.Id));
			if (activityGroupByPhaseId.containsKey(phase.Id)) {
				aGmp.put(
					'_children',
					getActivityGroups(estimateToActivityGroupMap, phase, gridExpandedIds)
				);
			}
			objlst.add(aGmp);
		}
		return finalValues(objlst, gridExpandedIds);
	}

	@TestVisible
	private static Map<Id, List<Activity__c>> mapActivitiesByGroupId(
		List<ActivityGroup__c> activityGroups
	) {
		Map<Id, List<Activity__c>> activityGroupActivityMap = new Map<Id, List<Activity__c>>();

		for (Activity__c activity : [
			SELECT
				Id,
				ActivityGroupId__r.Name,
				Path__c,
				IsNotApplicable__c,
				TotalCalculatedDuration__c,
				TotalLevelAdjustments__c,
				TotalAdjustments__c,
				TotalEstimatedDuration__c,
				Name,
				(
					SELECT
						Id,
						Name,
						TemplateId__c,
						Path__c,
						AdjustmentReason__c,
						IsNotApplicable__c,
						LevelAdjustment__c,
						CalculatedDuration__c,
						EstimatedDuration__c,
						ResourceRoleId__r.Name
					FROM Tasks__r
					WHERE IsActive__c = TRUE
					ORDER BY Sequence__c ASC
				)
			FROM Activity__c
			WHERE ActivityGroupId__c IN :activityGroups
			WITH SECURITY_ENFORCED
			ORDER BY Sequence__c ASC
		]) {
			List<Activity__c> activities = activityGroupActivityMap.get(activity.ActivityGroupId__r.Id);
			if (activities == null) {
				activities = new List<Activity__c>();
				activityGroupActivityMap.put(activity.ActivityGroupId__r.Id, activities);
			}

			activities.add(activity);
		}

		return activityGroupActivityMap;
	}

	@TestVisible
	private static Map<Id, String> roleSummaryMap(Id estimateId) {
		Map<Id, String> roleByGroupId = new Map<Id, String>();

		for (TaskRoleSummary__c summary : [
			SELECT Id, ActivityGroupId__c, ActivityId__c, ResourceRoleId__r.Name
			FROM TaskRoleSummary__c
			WHERE EstimateId__c = :estimateId
			WITH SECURITY_ENFORCED
		]) {
			putRoleActivityGroup(roleByGroupId, summary);
			putRoleActivity(roleByGroupId, summary);
		}

		return roleByGroupId;
	}

	private static void putRoleActivityGroup(
		Map<Id, String> roleByGroupId,
		TaskRoleSummary__c summary
	) {
		if (!roleByGroupId.containsKey(summary.ActivityGroupId__c)) {
			roleByGroupId.put(summary.ActivityGroupId__c, summary.ResourceRoleId__r.Name);
		} else {
			roleByGroupId.put(
				summary.ActivityGroupId__c,
				roleByGroupId.get(summary.ActivityGroupId__c) +
				',' +
				summary.ResourceRoleId__r.Name
			);
		}
	}

	private static void putRoleActivity(Map<Id, String> roleSumMap, TaskRoleSummary__c rlsum) {
		if (!roleSumMap.containsKey(rlsum.ActivityId__c)) {
			roleSumMap.put(rlsum.ActivityId__c, rlsum.ResourceRoleId__r.Name);
		} else {
			roleSumMap.put(
				rlsum.ActivityId__c,
				roleSumMap.get(rlsum.ActivityId__c) +
				',' +
				rlsum.ResourceRoleId__r.Name
			);
		}
	}

	@AuraEnabled
	public static void updateTasks(List<Task__c> tasks) {
		CRUDUtility.updateRecords(tasks);
	}

	//This method is used for Updating of Task and Value record..
	@AuraEnabled
	public static void updateTask(Task__c tsk, List<TaskParameterValue__c> taskParams) {
		CRUDUtility.updateRecords(tsk);
		if (taskParams != null) {
			CRUDUtility.updateRecords(taskParams);
		}
	}
	//This method is used for getting the Summary by role records at the estimate,Activitygroup and activity level..
	@AuraEnabled
	public static Object getSummaryRecords(String recordId, String type) {
		return EstimateTreeSummarySupport.getSummaryRecords(recordId, type);
	}

	//Query the Scope of the Estimate..
	@AuraEnabled
	public static List<TaskParameterValue__c> getSourceSummary(String estimateId) {
		List<TaskParameterValue__c> tpvLst = [
			SELECT
				Id,
				BooleanValue__c,
				IntegerValue__c,
				TextValue__c,
				TemplateId__r.Name,
				TemplateId__r.DataType__c,
				TaskId__c,
				TaskId__r.IsNotApplicable__c,
				TaskId__r.Name,
				TaskId__r.ActivityId__r.Name,
				TaskId__r.ActivityId__r.ActivityGroupId__r.Name,
				TaskId__r.ActivityGroupId__r.PhaseId__r.Name,
				TaskId__r.EstimatedDuration__c,
				Name
			FROM TaskParameterValue__c
			WHERE TaskId__r.EstimateId__c = :estimateId
			WITH SECURITY_ENFORCED
			ORDER BY TaskId__r.Path__c ASC
		];
		return tpvLst;
	}
	//When UpdateNotApplicable is checked at the ActivityGroup or Activity Level..
	@AuraEnabled
	public static void updateNotApplicableField(String recordId, Boolean notApplicable, String type) {
		if (type == EstimateTreeSupport.ACTIVITY_GROUP) {
			EstimateTreeService.notApplicableForActivityGroup(recordId, notApplicable);
		} else if (type == 'Activity') {
			EstimateTreeService.notApplicableForActivity(recordId, notApplicable);
		} else if (type == EstimateTreeSupport.PHASE) {
			EstimateTreeService.notApplicableForPhase(recordId, notApplicable);
		}
	}

	//This method is invoked when Edit task is invoked from the task row.
	@AuraEnabled
	public static Map<String, Object> getTaskDetails(String taskId) {
		return EstimateTreeTaskSupport.getTaskDetails(taskId);
	}

	//Create a level Summary Record..
	@AuraEnabled
	public static void createSummaryRecords(TaskRoleSummary__c summaryRecord, String typeof) {
		EstimateTreeSummarySupport.createSummaryRecords(summaryRecord, typeof);
	}
}