quoting-CypressTK1/force-app/main/default/objects/ActivityGroupTemplate__c/fields/Path__c.field-meta.xml
<CustomField>
    <fullName>Path__c</fullName>
    <formula
	>IF(TEXT(PhaseTemplateId__r.Sequence__c)&lt;&gt; &apos;0&apos; &amp;&amp;  EstimateTemplateId__r.UseProjectPhases__c == true,TEXT(PhaseTemplateId__r.Sequence__c)+&apos;.&apos;+ TEXT(Sequence__c),TEXT(Sequence__c))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Path</label>
    <type>Text</type>
</CustomField>

quoting-CypressTK1/force-app/main/default/objects/ActivityTemplate__c/fields/Path__c.field-meta.xml
<CustomField>
    <fullName>Path__c</fullName>
    <formula
	>IF(TEXT(ActivityGroupTemplateId__r.PhaseTemplateId__r.Sequence__c)&lt;&gt; &apos;0&apos; &amp;&amp;  ActivityGroupTemplateId__r.EstimateTemplateId__r.UseProjectPhases__c == true,  
TEXT(ActivityGroupTemplateId__r.PhaseTemplateId__r.Sequence__c) +&apos;.&apos; + TEXT(ActivityGroupTemplateId__r.Sequence__c) +&apos;.&apos; + TEXT(Sequence__c),TEXT(ActivityGroupTemplateId__r.Sequence__c)+&apos;.&apos;+ TEXT(Sequence__c))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Path</label>
    <type>Text</type>
</CustomField>

quoting-CypressTK1/force-app/main/default/objects/Product__c/Product__c.object-meta.xml
<CustomObject>
	<description>Provus Product object</description>
	<label>Product</label>
	<nameField>
		<label>Product Name</label>
		<type>Text</type>
	</nameField>
	<pluralLabel>Products</pluralLabel>
	<sharingModel>ReadWrite</sharingModel>
</CustomObject>

quoting-CypressTK1/force-app/main/default/objects/TaskTemplate__c/fields/Path__c.field-meta.xml
<CustomField>
    <fullName>Path__c</fullName>
    <formula
	>IF(TEXT(ActivityTemplateId__r.ActivityGroupTemplateId__r.PhaseTemplateId__r.Sequence__c)&lt;&gt; &apos;0&apos; &amp;&amp;  ActivityTemplateId__r.ActivityGroupTemplateId__r.EstimateTemplateId__r.UseProjectPhases__c == true,
TEXT(ActivityTemplateId__r.ActivityGroupTemplateId__r.PhaseTemplateId__r.Sequence__c) +&apos;.&apos;+ TEXT(ActivityTemplateId__r.ActivityGroupTemplateId__r.Sequence__c) +&apos;.&apos; + TEXT(ActivityTemplateId__r.Sequence__c) +&apos;.&apos; + TEXT(Sequence__c),TEXT(ActivityTemplateId__r.ActivityGroupTemplateId__r.Sequence__c) +&apos;.&apos; + TEXT(ActivityTemplateId__r.Sequence__c) +&apos;.&apos; + TEXT(Sequence__c))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Path</label>
    <type>Text</type>
</CustomField>

quoting-CypressTK1/force-app/main/default/objects/TaskTemplate__c/fields/ResourceRoleId__c.field-meta.xml
<CustomField>
    <fullName>ResourceRoleId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Resource Role</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Product__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Resource Role</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Product__c</referenceTo>
    <relationshipLabel>Task Templates</relationshipLabel>
    <relationshipName>TaskTemplates</relationshipName>
    <type>Lookup</type>
</CustomField>

quoting-CypressTK1/force-app/main/default/classes/TemplateElementDto.cls
/*
 * Provus Services Quoting
 * Copyright (c) 2022 Provus Inc. All rights reserved.
 */

@SuppressWarnings(
	'PMD.FieldNamingConventions'
) // TODO: remove this when we correct the property names
public with sharing class TemplateElementDto {
	@AuraEnabled
	public Id id;
	@AuraEnabled
	public String Type;
	@AuraEnabled
	public String ActivityGroup;
	@AuraEnabled
	public String ActivityGroupName;
	@AuraEnabled
	public String ActivityGroupId;
	@AuraEnabled
	public String ActionIcon;
	@AuraEnabled
	public String IconType;
	@AuraEnabled
	public String Actionlabel;
	@AuraEnabled
	public List<TemplateElementDto> children;
	@AuraEnabled
	public String ResourceName;
	@AuraEnabled
	public String ParentLabel;
	@AuraEnabled
	public List<String> gridExpandedIds;
	@AuraEnabled
	public String scopeParamCss;

	public TemplateElementDto(ActivityGroupTemplate__c activityGroupTemplate) {
		this.id = activityGroupTemplate.Id;
		this.ActivityGroup = activityGroupTemplate.Path__c + ' ' + activityGroupTemplate.Name;

		this.ActivityGroupName = activityGroupTemplate.Name;
		this.ActivityGroupId = activityGroupTemplate.Id;
		this.Type = 'ActivityGroupTemplate';
		this.ActionIcon = 'standard:work_type';
		this.IconType = 'standard:work_type_group';
		this.Actionlabel = System.Label.AddEditActivities;
	}

	public TemplateElementDto(TaskTemplate__c taskTemplate) {
		this.id = taskTemplate.Id;
		this.ActivityGroup = taskTemplate.Path__c + ' ' + taskTemplate.Name;
		this.ActivityGroupName = taskTemplate.Name;
		this.ActivityGroupId = taskTemplate.Id;
		this.ResourceName = taskTemplate.ResourceRoleId__r.Name;
		this.Type = 'TaskTemplate';
		this.ActionIcon = 'action:edit';
		this.IconType = 'standard:task';
		this.Actionlabel = System.Label.AddEditTaskParameters;
		this.scopeParamCss = 'slds-hide';
	}

	public TemplateElementDto(ActivityTemplate__c activityTemplate) {
		this.id = activityTemplate.Id;
		this.ActivityGroup = activityTemplate.Path__c + ' ' + activityTemplate.Name;
		this.ActivityGroupName = activityTemplate.Name;
		this.ActivityGroupId = activityTemplate.Id;
		this.Type = 'ActivityTemplate';
		this.ActionIcon = 'standard:task';
		this.IconType = 'standard:work_type';
		this.Actionlabel = System.Label.AddEditTasks;
	}

	public TemplateElementDto(PhaseTemplate__c phaseTemplate) {
		this.id = phaseTemplate.Id;
		this.ActivityGroup = phaseTemplate.Sequence__c + ' ' + phaseTemplate.Name;
		this.ActivityGroupName = phaseTemplate.Name;
		this.ActivityGroupId = phaseTemplate.Id;
		this.Type = 'PhaseTemplate';
		this.ActionIcon = 'standard:work_type';
		this.IconType = 'standard:event';
		this.Actionlabel = System.Label.AddEditActivityGroups;
	}
}