quoting-CypressTK1/force-app/main/default/objects/Quote__c/fields/LaborUnits__c.field-meta.xml
<CustomField>
    <fullName>LaborUnits__c</fullName>
    <defaultValue>&apos;Headcount&apos;</defaultValue>
    <label>Labor Units</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Headcount</fullName>
            </value>
            <value>
                <fullName>Hours</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

quoting-CypressTK1/force-app/main/default/objects/Quote__c/fields/TimePeriodsAlignment__c.field-meta.xml
<CustomField>
    <fullName>TimePeriodsAlignment__c</fullName>
    <label>Time Periods Alignment</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>User Defined Calendar</fullName>
            </value>            
            <value>
                <fullName>Weekday Calendar</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

quoting-CypressTK1/force-app/main/default/objects/QuoteItem__c/fields/ProductId__c.field-meta.xml
<CustomField>
    <fullName>ProductId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product__c</referenceTo>
    <relationshipLabel>Quote Items</relationshipLabel>
    <relationshipName>QuoteItems</relationshipName>
    <type>Lookup</type>
</CustomField>

quoting-CypressTK1/force-app/main/default/objects/QuoteSection__c/fields/ActivityGroupId__c.field-meta.xml
<CustomField>
    <fullName>ActivityGroupId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Activity Group</label>
    <referenceTo>ActivityGroup__c</referenceTo>
    <relationshipName>QuoteSections</relationshipName>
    <type>Lookup</type>
</CustomField>

quoting-CypressTK1/force-app/main/default/objects/RateCardItem__c/fields/ProductId__c.field-meta.xml
<CustomField>
    <fullName>ProductId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product__c</referenceTo>
    <relationshipLabel>Rate Card Items</relationshipLabel>
    <relationshipName>RateCardItems</relationshipName>
    <type>Lookup</type>
</CustomField>

quoting-CypressTK1/force-app/main/default/objects/ResourceAvailability__c/ResourceAvailability__c.object-meta.xml
<CustomObject>
    <description
	>Captures the maximum time a resource is available to work for a given period</description>
    <label>Resource Availability</label>
    <nameField>
        <displayFormat>RA-{00000}</displayFormat>
        <label>Resource Availability</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Resource Availabilities</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

quoting-CypressTK1/force-app/main/default/objects/ResourceAvailability__c/fields/AvailabilityPercentage__c.field-meta.xml
<CustomField>
    <fullName>AvailabilityPercentage__c</fullName>
    <label>Availability Percentage</label>
    <precision>6</precision>
    <scale>3</scale>
    <type>Percent</type>
</CustomField>

quoting-CypressTK1/force-app/main/default/objects/ResourceAvailability__c/fields/FullTimeTotalEstimatedDuration__c.field-meta.xml
<CustomField>
    <fullName>FullTimeTotalEstimatedDuration__c</fullName>
    <formula
	>IF(AvailabilityPercentage__c == NULL, TaskRoleSummaryId__r.TotalEstimatedDuration__c, IF(AvailabilityPercentage__c == 0, 0, TaskRoleSummaryId__r.TotalEstimatedDuration__c * (1 / AvailabilityPercentage__c)))</formula>
    <label>Full Time Total Estimated Duration</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

quoting-CypressTK1/force-app/main/default/objects/ResourceAvailability__c/fields/TaskRoleSummaryId__c.field-meta.xml
<CustomField>
    <fullName>TaskRoleSummaryId__c</fullName>
    <label>Task Role Summary</label>
    <referenceTo>TaskRoleSummary__c</referenceTo>
    <relationshipLabel>Resource Availabilities</relationshipLabel>
    <relationshipName>ResourceAvailabilities</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

quoting-CypressTK1/force-app/main/default/objects/ResourceSplit__c/ResourceSplit__c.object-meta.xml
<CustomObject>
    <label>Resource Split</label>
    <nameField>
        <label>Resource Split Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Resource Splits</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

quoting-CypressTK1/force-app/main/default/objects/ResourceSplit__c/fields/SplitPercentage__c.field-meta.xml
<CustomField>
    <fullName>SplitPercentage__c</fullName>
    <label>Split Percentage</label>
    <precision>18</precision>
    <scale>15</scale>
    <type>Percent</type>
</CustomField>

quoting-CypressTK1/force-app/main/default/objects/ResourceSplit__c/fields/TaskRoleSummaryId__c.field-meta.xml
<CustomField>
    <fullName>TaskRoleSummaryId__c</fullName>
    <label>Task Role Summary</label>
    <referenceTo>TaskRoleSummary__c</referenceTo>
    <relationshipLabel>Resource Splits</relationshipLabel>
    <relationshipName>ResourceSplits</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

quoting-CypressTK1/force-app/main/default/objects/ResourceSplit__c/fields/TotalEstimatedDuration__c.field-meta.xml
<CustomField>
    <fullName>TotalEstimatedDuration__c</fullName>
    <formula>TaskRoleSummaryId__r.TotalEstimatedDuration__c  *  SplitPercentage__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total Estimated Duration</label>
    <precision>18</precision>
    <scale>5</scale>
    <type>Number</type>
</CustomField>

quoting-CypressTK1/force-app/main/default/objects/TaskRoleSummary__c/fields/RateCardItemId__c.field-meta.xml
<CustomField>
    <fullName>RateCardItemId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Rate Card Item</label>
    <referenceTo>RateCardItem__c</referenceTo>
    <relationshipLabel>Task Role Summaries</relationshipLabel>
    <relationshipName>TaskRoleSummaries</relationshipName>
    <type>Lookup</type>
</CustomField>

quoting-CypressTK1/force-app/main/default/objects/TaskRoleSummary__c/fields/ResourceRoleId__c.field-meta.xml
<CustomField>
    <fullName>ResourceRoleId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Resource Role</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Product__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Resource Role</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Product__c</referenceTo>
    <relationshipName>LevelSummaries</relationshipName>
    <type>Lookup</type>
</CustomField>

quoting-CypressTK1/force-app/main/default/objects/TaskRoleSummary__c/fields/TotalEstimatedDuration__c.field-meta.xml
<CustomField>
    <fullName>TotalEstimatedDuration__c</fullName>
    <formula>TotalCalculatedDuration__c + TotalAdjustments__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total estimated duration</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

quoting-CypressTK1/force-app/main/default/classes/EstimateService.cls
public with sharing class EstimateService {
	public static Date getServiceEndDate(Id estimateId, EndDateArgs endDateArgs) {
		Decimal totalDuration = 0;

		Map<Id, Decimal> maxTotalByGroupId = getActivityGroupMaxDurations(estimateId);
		for (Decimal groupResult : maxTotalByGroupId.values()) {
			totalDuration += groupResult;
		}

		if (endDateArgs.calendarAlignment == QuoteService.TIMEPERIODSALIGNMENT_WEEKDAY_CALENDAR) {
			return DurationCalcs.weekdayEndDate(totalDuration, endDateArgs.serviceStartDate);
		}

		return DurationCalcs.endDate(totalDuration, endDateArgs.quoteId, endDateArgs.serviceStartDate);
	}

	/**
	 * Get the maximum duration of each activity group
	 *
	 * @param estimateId  the context estimate id
	 * @return max duration of each activity group
	 */
	@TestVisible
	private static Map<Id, Decimal> getActivityGroupMaxDurations(Id estimateId) {
		Map<Id, Decimal> maxTotalByGroupId = new Map<Id, Decimal>();
		List<TaskRoleSummary__c> taskRoleSummaries = [
			SELECT
				Id,
				ActivityGroupId__c,
				TotalEstimatedDuration__c,
				(SELECT Id, FullTimeTotalEstimatedDuration__c FROM ResourceAvailabilities__r LIMIT 1),
				(SELECT Id, SplitPercentage__c, TotalEstimatedDuration__c FROM ResourceSplits__r)
			FROM TaskRoleSummary__c
			WHERE ActivityGroupId__r.EstimateId__c = :estimateId AND TotalEstimatedDuration__c > 0
			WITH SECURITY_ENFORCED
		];

		for (TaskRoleSummary taskRoleSummary : TaskRoleSummary.toTaskRoleSummary(taskRoleSummaries)) {
			TaskRoleSummary__c taskRoleSummarySo = (TaskRoleSummary__c) taskRoleSummary.getSObject();
			Id activityGroupId = taskRoleSummarySo.ActivityGroupId__c;
			Decimal maxDuration = taskRoleSummary.maxEstimatedDuration();
			Decimal maxDurationForActivityGroup = maxTotalByGroupId.get(activityGroupId);
			if (maxDurationForActivityGroup == null) {
				maxDurationForActivityGroup = maxDuration;
			} else {
				maxDurationForActivityGroup = Math.max(maxDurationForActivityGroup, maxDuration);
			}
			maxTotalByGroupId.put(activityGroupId, maxDurationForActivityGroup);
		}

		return maxTotalByGroupId;
	}

	public static Set<Id> filterOrderedRoles(Set<Id> orderedRoleIds, Set<Id> toFilter) {
		Set<Id> sortedApplicableRoleIds = new Set<Id>();
		for (Id roleId : orderedRoleIds) {
			if (toFilter.contains(roleId)) {
				sortedApplicableRoleIds.add(roleId);
			}
		}

		return sortedApplicableRoleIds;
	}

	public static Decimal getAvailabilityPercentage(TaskRoleSummary__c taskRoleSummary) {
		Decimal availabilityPercentage = 100;
		if (!taskRoleSummary.ResourceAvailabilities__r.isEmpty()) {
			// we onlny support 1 availbility percentage per role, per group
			availabilityPercentage = taskRoleSummary.ResourceAvailabilities__r[0]
				.AvailabilityPercentage__c;
		}

		return availabilityPercentage;
	}

	public static QuoteItem__c createQuoteItem(
		CreateQuoteFromEstimateService.CreateQuoteItemRequest createQuoteItemReq,
		Map<Id, RateCardItem__c> rateCardItemByRoleId
	) {
		QuoteSection__c section = createQuoteItemReq.section;
		QuoteItem__c item = new QuoteItem__c();
		item.QuoteId__c = section.QuoteId__c;
		item.QuoteSectionId__c = section.Id;
		item.Sequence__c = createQuoteItemReq.sequence++;
		item.SectionSequence__c = createQuoteItemReq.sectionSequence; // sequence of quote item within its section
		item.DisplaySequence__c = section.DisplaySequence__c; // inherit display sequence of section
		item.ProductId__c = createQuoteItemReq.roleId;
		item.RateCardItemId__c = rateCardItemByRoleId.get(createQuoteItemReq.roleId)?.Id;
		item.SkillLevel__c = rateCardItemByRoleId.get(createQuoteItemReq.roleId)?.SkillLevel__c;
		item.LocationDisplayName__c = rateCardItemByRoleId.get(createQuoteItemReq.roleId)
			?.LocationDisplayName__c;
		return item;
	}

	public static String quoteItemSplitRolesKey(QuoteItem__c quoteItem) {
		return quoteItem.ProductId__c +
			'-' +
			quoteItem.Sequence__c +
			'-' +
			quoteItem.SectionSequence__c;
	}

	public static void createQuoteItemCells(
		Quote__c quoteSO,
		CreateQuoteFromEstimateService.CreateQuoteItemsResponse quoteItemsResponse,
		Map<String, Decimal> durationByRole
	) {
		List<QuoteItem__c> quoteItems = quoteItemsResponse.quoteItems;
		List<QuoteItemCell__c> itemCells = new List<QuoteItemCell__c>();
		Integer sectionStartCellIndex = 1;
		Integer sectionEndCellIndex = 1;
		Id currentSectionId = quoteItems.get(0).QuoteSectionId__c;

		Map<Decimal, PeriodDetails> termByPeriodSequence = getTermByPeriodSequence(quoteSO);
		Decimal minimumCarryoverHours = termByPeriodSequence.get(sectionEndCellIndex).workableHours;

		for (QuoteItem__c quoteItemSO : quoteItems) {
			String roleSequenceKey = generateRoleSequenceKey(quoteItemSO);
			if (currentSectionId != quoteItemSO.QuoteSectionId__c) {
				sectionStartCellIndex = sectionEndCellIndex + 1; // new section starts at the farthest found cell index of the previous section
				if (minimumCarryoverHours > 0) {
					sectionStartCellIndex -= 1; // start in the same starting period as the previous section end
					termByPeriodSequence.get(sectionStartCellIndex).workableHours = minimumCarryoverHours; // reduce the workable hours to the smallest carryover we're allowed
				} else {
					minimumCarryoverHours = termByPeriodSequence.get(sectionStartCellIndex).workableHours;
				}

				currentSectionId = quoteItemSO.QuoteSectionId__c;
			}

			Decimal availabilityPercentage = quoteItemsResponse.availabilityPercentageByRoleKey.get(
				roleSequenceKey
			);
			Decimal itemDuration = durationByRole.get(roleSequenceKey);
			Decimal splitPercent = quoteItemsResponse.quoteItemSplitsById.get(
				quoteItemSplitRolesKey(quoteItemSO)
			);
			// if no corresponding split value we assume no split and set to 1
			splitPercent = splitPercent == null ? 1 : splitPercent / 100;
			// reduce period span by the equivalent of the splint percentage
			itemDuration = itemDuration * splitPercent;

			QuoteItemCellService.QuoteItemCellRequest itemCellRequest = new QuoteItemCellService.QuoteItemCellRequest();
			itemCellRequest.itemDurationHours = itemDuration;
			itemCellRequest.startCellIndex = sectionStartCellIndex;
			itemCellRequest.availabilityPercentage = availabilityPercentage;
			itemCellRequest.isLaborUnitsInHours = quoteSO.LaborUnits__c == QuoteService.LABORUNITS_HOURS;

			QuoteItemCellService.QuoteItemCellResponse itemCellResp = QuoteItemCellService.createQuoteItemCell(
				itemCellRequest,
				termByPeriodSequence
			);

			itemCellResp.quoteItemCell.QuoteItemId__c = quoteItemSO.Id;
			itemCells.add(itemCellResp.quoteItemCell);

			if (itemCellResp.endCellIndex > sectionEndCellIndex) {
				// we're in a new period, reset the minimum
				sectionEndCellIndex = itemCellResp.endCellIndex;
				minimumCarryoverHours =
					termByPeriodSequence.get(sectionEndCellIndex).workableHours - itemCellResp.endCellHours;
			}

			if (itemCellResp.endCellIndex == sectionEndCellIndex) {
				// compare against same column index
				minimumCarryoverHours = Math.min(
					minimumCarryoverHours,
					termByPeriodSequence.get(sectionEndCellIndex).workableHours - itemCellResp.endCellHours
				);
			}
		}
		CRUDUtility.insertRecords(itemCells);
	}

	public class PeriodDetails {
		public Decimal workableHours;
		public Decimal periodHours;
	}

	public static Map<Decimal, PeriodDetails> getTermByPeriodSequence(Quote__c quoteSo) {
		Map<Decimal, PeriodDetails> termByPeriodSequence = new Map<Decimal, PeriodDetails>();
		Decimal standardHours = DurationCalcs.numberOfHoursInPeriod(quoteSo.TimePeriod__c);
		IWeekdayTimePeriod timePeriodCalc = WeekdayTimePeriodFactory.newTimePeriod(
			quoteSo.TimePeriod__c
		);
		List<QuotePeriod> periods = QuotePeriodService.getQuotePeriods(quoteSo.Id);
		for (QuotePeriod period : periods) {
			PeriodDetails details = new PeriodDetails();
			if (quoteSo.TimePeriodsAlignment__c == QuoteService.TIMEPERIODSALIGNMENT_WEEKDAY_CALENDAR) {
				details.workableHours =
					SettingsService.getScheduleSettings().standardDayHours *
					Calendar.weekdaysIn(period.startDate, period.endDate);
				details.periodHours = timePeriodCalc.periodHours(period.startDate);
			} else {
				details.workableHours = standardHours;
				details.periodHours = standardHours;
			}

			termByPeriodSequence.put(period.sequence, details);
		}

		return termByPeriodSequence;
	}

	public static String generateRoleSequenceKey(QuoteItem__c quoteItem) {
		return quoteItem.ProductId__c + '-' + quoteItem.DisplaySequence__c;
	}

	public static String generateRoleSequenceKey(Id roleId, QuoteSection__c quoteSection) {
		return roleId + '-' + quoteSection.DisplaySequence__c;
	}

	public static Set<Id> getOrderedResourceRoles(Id estimateId) {
		Set<Id> orderedResources = new Set<Id>();
		List<ActivityGroup__c> groups = [
			SELECT
				Id,
				(SELECT ResourceRoleId__c FROM RoleSummaries__r WHERE TotalEstimatedDuration__c > 0)
			FROM ActivityGroup__c
			WHERE EstimateId__c = :estimateId
			WITH SECURITY_ENFORCED
			ORDER BY Sequence__c
		];

		for (ActivityGroup__c grp : groups) {
			for (TaskRoleSummary__c summary : grp.RoleSummaries__r) {
				orderedResources.add(summary.ResourceRoleId__c);
			}
		}

		return orderedResources;
	}

	public static Map<Id, RateCardItem__c> getRateCardItemPreferences(Id estimateId) {
		Map<Id, RateCardItem__c> rateCardItemByRoleId = new Map<Id, RateCardItem__c>();
		for (TaskRoleSummary__c roleSummary : [
			SELECT
				ResourceRoleId__c,
				RateCardItemId__r.Id,
				RateCardItemId__r.SkillLevel__c,
				RateCardItemId__r.LocationDisplayName__c
			FROM TaskRoleSummary__c
			WHERE EstimateId__c = :estimateId AND RateCardItemId__c != NULL
			WITH SECURITY_ENFORCED
		]) {
			rateCardItemByRoleId.put(roleSummary.ResourceRoleId__c, roleSummary.RateCardItemId__r);
		}

		return rateCardItemByRoleId;
	}
}