quoting-CypressTK1/force-app/main/default/objects/Quote__c/fields/RateCardId__c.field-meta.xml
<CustomField>
    <fullName>RateCardId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Rate Card</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(6 OR 7) AND (3 OR 1) AND (4 OR 2) AND 5</booleanFilter>
        <errorMessage
		>The Rate Card is expired/inactive during the selected service start date</errorMessage>
        <filterItems>
            <field>$Source.ServiceStartDate__c</field>
            <operation>greaterOrEqual</operation>
            <valueField>RateCard__c.EffectiveDate__c</valueField>
        </filterItems>
        <filterItems>
            <field>$Source.ServiceStartDate__c</field>
            <operation>lessOrEqual</operation>
            <valueField>RateCard__c.ExpirationDate__c</valueField>
        </filterItems>
        <filterItems>
            <field>RateCard__c.EffectiveDate__c</field>
            <operation>equals</operation>
            <value />
        </filterItems>
        <filterItems>
            <field>RateCard__c.ExpirationDate__c</field>
            <operation>equals</operation>
            <value />
        </filterItems>
        <filterItems>
            <field>RateCard__c.IsActive__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>$Source.AccountId__c</field>
            <operation>equals</operation>
            <valueField>RateCard__c.AssignedToAccountId__c</valueField>
        </filterItems>
        <filterItems>
            <field>RateCard__c.AssignedToAccountId__c</field>
            <operation>equals</operation>
            <value />
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>RateCard__c</referenceTo>
    <relationshipLabel>Quotes</relationshipLabel>
    <relationshipName>Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

quoting-CypressTK1/force-app/main/default/objects/RateCardAttributeGroup__c/RateCardAttributeGroup__c.object-meta.xml
<CustomObject>
    <label>Rate Card Attribute Group</label>
    <nameField>
        <label>Rate Card Attribute Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Rate Card Attribute Groups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

quoting-CypressTK1/force-app/main/default/objects/RateCardAttributeOption__c/RateCardAttributeOption__c.object-meta.xml
<CustomObject>
    <label>Rate Card Attribute Option</label>
    <nameField>
        <displayFormat>RCAO-{00000}</displayFormat>
        <label>Rate Card Attribute Option Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Rate Card Attribute Options</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

quoting-CypressTK1/force-app/main/default/objects/RateCardAttributeOption__c/fields/AttributeGroupId__c.field-meta.xml
<CustomField>
    <fullName>AttributeGroupId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Attribute Group</label>
    <referenceTo>RateCardAttributeGroup__c</referenceTo>
    <relationshipLabel>Rate Card Attribute Options</relationshipLabel>
    <relationshipName>RateCardAttributeOptions</relationshipName>
    <type>Lookup</type>
</CustomField>

quoting-CypressTK1/force-app/main/default/objects/RateCardAttributeOption__c/fields/RateCardAttributeId__c.field-meta.xml
<CustomField>
    <fullName>RateCardAttributeId__c</fullName>
    <label>Rate Card Attribute</label>
    <referenceTo>RateCardAttribute__c</referenceTo>
    <relationshipLabel>Rate Card Attribute Options</relationshipLabel>
    <relationshipName>RateCardAttributeOptions</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

quoting-CypressTK1/force-app/main/default/objects/RateCardAttributeOption__c/fields/RateCardAttributeOptionKey__c.field-meta.xml
<CustomField>
    <fullName>RateCardAttributeOptionKey__c</fullName>
    <externalId>true</externalId>
    <label>Rate Card Attribute Option Key</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

quoting-CypressTK1/force-app/main/default/objects/RateCardAttributeOption__c/fields/RateCardId__c.field-meta.xml
<CustomField>
    <fullName>RateCardId__c</fullName>
    <label>Rate Card</label>
    <referenceTo>RateCard__c</referenceTo>
    <relationshipLabel>Rate Card Attribute Options</relationshipLabel>
    <relationshipName>RateCardAttributeOptions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

quoting-CypressTK1/force-app/main/default/objects/RateCardAttributeOption__c/fields/TextValue__c.field-meta.xml
<CustomField>
    <fullName>TextValue__c</fullName>
    <label>Text Value</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

quoting-CypressTK1/force-app/main/default/classes/RateCardServiceTest.cls
/**
 *  Provus Services Quoting
 *  RateCardServiceTest
 *  @2021 Provus Inc. All rights reserved.
 */
@isTest
private class RateCardServiceTest extends TestBase {
	@testSetup
	static void setup() {
		RateCardAttributeGroup__c rateCardAttributeGroup = newRateCardAttributeGroup();
		newRateCardAttribute(rateCardAttributeGroup.Id); // create attribute and related it to attribute group
		RateCard__c rateCard = newRateCard();
		rateCard.AttributeGroupId__c = rateCardAttributeGroup.Id;
		update rateCard;
	}

	@IsTest
	static void itShouldGetRateCard() {
		Test.startTest();
		RateCard__c rateCardSO = [
			SELECT Id
			FROM RateCard__c
			WHERE Name = 'Skill & Resource Location'
			LIMIT 1
		];
		RateCardService rateCardService = new RateCardService(rateCardSO.Id);
		System.assertNotEquals(rateCardService, null, 'should not be null');
		Test.stopTest();
	}

	@IsTest
	static void itShouldGetRateCardAttributes() {
		Test.startTest();
		RateCard__c rateCardSO = [
			SELECT Id
			FROM RateCard__c
			WHERE Name = 'Skill & Resource Location'
			WITH SECURITY_ENFORCED
			LIMIT 1
		];
		RateCardService rateCardService = new RateCardService(rateCardSO.Id);
		Set<String> attributes = rateCardService.getAttributes();
		System.assert(
			attributes.contains(Schema.RateCardItem__c.SkillLevel__c + ''),
			'should contain skill level as an attribute'
		);
		Test.stopTest();
	}

	@IsTest
	static void itShouldGetRateCardWithSequence() {
		Test.startTest();
		RateCard__c rateCardSO = [
			SELECT Id
			FROM RateCard__c
			WHERE Name = 'Skill & Resource Location'
			LIMIT 1
		];
		RateCardService rateCardService = new RateCardService(rateCardSO.Id);
		Map<String, Decimal> attributesWithSequence = rateCardService.getAttributesWithSequence();
		System.assertEquals(
			attributesWithSequence.get(Schema.RateCardItem__c.SkillLevel__c + ''),
			1,
			'should be the first attribute'
		);
		Test.stopTest();
	}

	@IsTest
	static void itShouldcheckIfRateCardIsExpired() {
		Test.startTest();
		RateCard__c rateCardSO = [
			SELECT Id
			FROM RateCard__c
			WHERE Name = 'Skill & Resource Location'
			LIMIT 1
		];

		Quote__c quoteSO = newQuote();
		quoteSO.RateCardId__c = rateCardSO.Id;
		Map<Boolean, String> rateCardStatusMap = RateCardService.checkIfRateCardIsExpired(quoteSO.Id);
		System.assertEquals(rateCardStatusMap.size(), 1, 'size should be one');
		Test.stopTest();
	}

	@IsTest
	static void itShouldReturnFiltersForRateCard() {
		RateCard__c rateCardSO = newRateCard();
		RateCardAttributeGroup__c testAtributeGroup = newRateCardAttributeGroup();
		RateCardAttribute__c testAttribute = newRateCardAttribute(testAtributeGroup.Id);
		String skillLevelAPIName = Schema.RateCardItem__c.SkillLevel__c + '';

		RateCardAttributeOption__c attributeOption = new RateCardAttributeOption__c(
			RateCardAttributeOptionKey__c = 'TestKey',
			TextValue__c = 'Some Option',
			AttributeGroupId__c = testAtributeGroup.Id,
			RateCardAttributeId__c = testAttribute.Id,
			RateCardId__c = rateCardSO.Id
		);
		insert attributeOption;

		List<SObjectUtility.SObjectFieldInfo> rateCardItemFields = SObjectUtility.getSObjectFields(
			new Map<Schema.SObjectType, Set<String>>{
				RateCardItem__c.SObjectType => new Set<String>{ skillLevelAPIName }
			}
		);
		SObjectUtility.SObjectFieldInfo skillLevelFieldInfo = rateCardItemFields[0];

		Test.startTest();
		List<RateCardAttributeOptionDto> rateCardAttributeOptions = RateCardService.getRateCardFilters(
			rateCardSO.Id
		);
		System.assertEquals(rateCardAttributeOptions.size(), 1, 'should return 1 attribute option');
		System.assertEquals(
			rateCardAttributeOptions[0].name,
			skillLevelAPIName,
			'the api name should match'
		);
		System.assertEquals(
			rateCardAttributeOptions[0].label,
			skillLevelFieldInfo.fieldLabel,
			'the field label should match'
		);
		System.assertEquals(rateCardAttributeOptions[0].options.size(), 1, 'it should have one option');
		System.assertEquals(
			rateCardAttributeOptions[0].options[0],
			attributeOption.TextValue__c,
			'the option should match'
		);
		Test.stopTest();
	}

	static void itShouldNotReturnFiltersForRateCard() {
		RateCard__c rateCardSO = newRateCard();

		Test.startTest();
		List<RateCardAttributeOptionDto> rateCardAttributeOptions = RateCardService.getRateCardFilters(
			rateCardSO.Id
		);
		System.assertEquals(rateCardAttributeOptions.size(), 0, 'should return empty array');
		Test.stopTest();
	}
}