quoting-CypressTK1/force-app/main/default/objects/ResourceDefault__c/fields/ProductId__c.field-meta.xml
<CustomField>
    <fullName>ProductId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product__c</referenceTo>
    <relationshipLabel>Resource Defaults</relationshipLabel>
    <relationshipName>ResourceDefaults</relationshipName>
    <type>Lookup</type>
</CustomField>

quoting-CypressTK1/force-app/main/default/objects/ResourceDefault__c/fields/RateCardItemId__c.field-meta.xml
<CustomField>
    <fullName>RateCardItemId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Rate Card Item</label>
    <referenceTo>RateCardItem__c</referenceTo>
    <relationshipLabel>Resource Defaults</relationshipLabel>
    <relationshipName>ResourceDefaults</relationshipName>
    <type>Lookup</type>
</CustomField>

quoting-CypressTK1/force-app/main/default/classes/ResourceDefaultTestBase.cls
/*
 * Provus Services Quoting
 * Copyright (c) 2022 Provus Inc. All rights reserved.
 */

@IsTest
public class ResourceDefaultTestBase {
	public static ResourceDefault__c newResourceDefault(Id productId, Id rateCardItemId) {
		ResourceDefault__c defaultSo = new ResourceDefault__c(
			ProductId__c = productId,
			RateCardItemId__c = rateCardItemId
		);
		CRUDUtility.insertRecords(defaultSo);
		return defaultSo;
	}
}