quoting-CypressTK1/force-app/main/default/objects/ResourceDefault__c/fields/RateCardItemId__c.field-meta.xml
<CustomField>
    <fullName>RateCardItemId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Rate Card Item</label>
    <referenceTo>RateCardItem__c</referenceTo>
    <relationshipLabel>Resource Defaults</relationshipLabel>
    <relationshipName>ResourceDefaults</relationshipName>
    <type>Lookup</type>
</CustomField>

quoting-CypressTK1/force-app/main/default/classes/ResourceDefaultDto.cls
/*
 * Provus Services Quoting
 * Copyright (c) 2022 Provus Inc. All rights reserved.
 */
public with sharing class ResourceDefaultDto {
	public ResourceDefault__c defaultSo;
	@AuraEnabled
	public Id id { get; set; }
	@AuraEnabled
	public String rateCardItemId { get; set; }

	public ResourceDefault__c updateSo() {
		if (this.defaultSo == null) {
			this.defaultSo = new ResourceDefault__c();
		}

		defaultSo.Id = this.id;
		defaultSo.RateCardItemId__c = this.rateCardItemId;

		return this.defaultSo;
	}
}