quoting-CypressTK1/force-app/main/default/objects/ProjectMilestone__c/fields/ActivityDate__c.field-meta.xml
<CustomField>
    <fullName>ActivityDate__c</fullName>
    <formula>CASE(Type__c,
&quot;Occurs on a Date&quot;, AlignmentDate__c,
&quot;Aligned to Project Activity&quot;, CASE(Alignment__c,
&quot;Start of Project&quot;, QuoteId__r.ServiceStartDate__c,
&quot;End of Project&quot;, QuoteId__r.ServiceEndDate__c,
&quot;Start of Phase&quot;, ProjectPhase__r.StartDate__c,
&quot;End of Phase&quot;, ProjectPhase__r.EndDate__c,
&quot;Start of Section&quot;, QuoteSection__r.StartDate__c,
&quot;End of Section&quot;, QuoteSection__r.EndDate__c,
&quot;Start of Period&quot;, QuotePeriod__r.StartDate__c,
&quot;End of Period&quot;, QuotePeriod__r.EndDate__c,
&quot;Start of Period Group&quot;, QuotePeriodGroup__r.StartDate__c,
&quot;End of Period Group&quot;, QuotePeriodGroup__r.EndDate__c,
null),
&quot;Aligned to another Milestone&quot;, MilestoneId__r.AlignmentDate__c,
null)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Activity Date</label>
    <type>Date</type>
</CustomField>

quoting-CypressTK1/force-app/main/default/objects/ProjectMilestone__c/fields/ActivityName__c.field-meta.xml
<CustomField>
    <fullName>ActivityName__c</fullName>
    <formula>IF(NOT(ISBLANK(ProjectPhase__c)),ProjectPhase__r.Name,
IF( NOT(ISBLANK(QuoteSection__c)),QuoteSection__r.Name,
IF( NOT(ISBLANK(QuotePeriodGroup__c)),QuotePeriodGroup__r.Name,
IF( NOT(ISBLANK(QuotePeriod__c)),QuotePeriod__r.Name,&quot;N/A&quot;))))</formula>
    <label>Activity Name</label>
    <type>Text</type>
</CustomField>

quoting-CypressTK1/force-app/main/default/objects/ProjectMilestone__c/fields/AlignToActivityOrMilestone__c.field-meta.xml
<CustomField>
    <fullName>AlignToActivityOrMilestone__c</fullName>
    <formula>IF(ISPICKVAL(Type__c,&apos;Occurs on a Date&apos;),&quot;N/A&quot;,
IF(ISPICKVAL(Type__c,&apos;Aligned to Project Activity&apos;), MilestoneId__r.Name,
IF(ISPICKVAL(Type__c,&apos;Aligned to another Milestone&apos;),MilestoneId__r.Name,&quot;N/A&quot;)))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Align to Activity or Milestone</label>
    <type>Text</type>
</CustomField>

quoting-CypressTK1/force-app/main/default/objects/ProjectMilestone__c/fields/EstimatedOccurrenceDate__c.field-meta.xml
<CustomField>
    <fullName>EstimatedOccurrenceDate__c</fullName>
    <formula>IF(NOT(ISBLANK(Offset__c)),
CASE(OffsetUnit__c ,
&quot;Days&quot;,  ActivityDate__c +  Offset__c ,
&quot;Weeks&quot;, ActivityDate__c + (Offset__c * 7),
&quot;Months&quot;, ADDMONTHS(ActivityDate__c, Offset__c) ,
&quot;Quarters&quot;, ADDMONTHS(ActivityDate__c, (Offset__c * 3)),
&quot;Years&quot;, ADDMONTHS(ActivityDate__c, (Offset__c * 12)),
ActivityDate__c),
ActivityDate__c
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Estimated Occurrence Date</label>
    <type>Date</type>
</CustomField>

quoting-CypressTK1/force-app/main/default/objects/ProjectMilestone__c/fields/Offset__c.field-meta.xml
<CustomField>
    <fullName>Offset__c</fullName>
    <label>Offset</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

quoting-CypressTK1/force-app/main/default/objects/ProjectMilestone__c/fields/OffsetUnit__c.field-meta.xml
<CustomField>
    <fullName>OffsetUnit__c</fullName>
    <label>Offset Unit</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>TimePeriods</valueSetName>
    </valueSet>
</CustomField>

quoting-CypressTK1/force-app/main/default/objects/ProjectMilestone__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Occurs on a Date</fullName>
            </value>
            <value>
                <fullName>Aligned to Project Activity</fullName>
            </value>
            <value>
                <fullName>Aligned to another Milestone</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

quoting-CypressTK1/force-app/main/default/globalValueSets/TimePeriods.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Days</fullName>
    </customValue>
    <customValue>
        <fullName>Weeks</fullName>
    </customValue>
    <customValue>
        <fullName>Months</fullName>
    </customValue>
    <customValue>
        <fullName>Quarters</fullName>
    </customValue>
    <customValue>
        <fullName>Years</fullName>
    </customValue>
    <masterLabel>Time Periods</masterLabel>
</GlobalValueSet>

quoting-CypressTK1/force-app/main/default/classes/ProjectMilestoneDto.cls
/*
 * Provus Services Quoting
 * Copyright (c) 2022 Provus Inc. All rights reserved.
 */

public with sharing class ProjectMilestoneDto extends BaseDTO {
	@AuraEnabled
	public String alignToActivityOrMilestone;
	@AuraEnabled
	public Date activityDate;
	@AuraEnabled
	public String activityName;
	@AuraEnabled
	public Decimal offset;
	@AuraEnabled
	public String offsetUnit;
	@AuraEnabled
	public Date estimatedOccurrenceDate;

	public ProjectMilestoneDto(ProjectMilestone__c milestoneSO) {
		this.id = milestoneSO.Id;
		this.name = milestoneSO.Name;
		this.alignToActivityOrMilestone = milestoneSO.AlignToActivityOrMilestone__c;
		this.activityName = milestoneSO.ActivityName__c;
		this.offset = milestoneSO.Offset__c;
		this.offsetUnit = milestoneSO.OffsetUnit__c;
		this.estimatedOccurrenceDate = milestoneSO.EstimatedOccurrenceDate__c;

		if (milestoneSO.Type__c == ProjectMilestone.TYPE_DATE) {
			this.activityDate = milestoneSO.ActivityDate__c;
		}
	}

	public override SObject refreshSo() {
		return null;
	}
}