quoting-CypressTK1/force-app/main/default/objects/ProjectMilestone__c/fields/AlignmentDate__c.field-meta.xml
<CustomField>
    <fullName>AlignmentDate__c</fullName>
    <label>Alignment Date</label>
    <type>Date</type>
</CustomField>

quoting-CypressTK1/force-app/main/default/objects/ProjectMilestone__c/fields/EstimatedOccurrenceDate__c.field-meta.xml
<CustomField>
    <fullName>EstimatedOccurrenceDate__c</fullName>
    <formula>IF(NOT(ISBLANK(Offset__c)),
CASE(OffsetUnit__c ,
&quot;Days&quot;,  ActivityDate__c +  Offset__c ,
&quot;Weeks&quot;, ActivityDate__c + (Offset__c * 7),
&quot;Months&quot;, ADDMONTHS(ActivityDate__c, Offset__c) ,
&quot;Quarters&quot;, ADDMONTHS(ActivityDate__c, (Offset__c * 3)),
&quot;Years&quot;, ADDMONTHS(ActivityDate__c, (Offset__c * 12)),
ActivityDate__c),
ActivityDate__c
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Estimated Occurrence Date</label>
    <type>Date</type>
</CustomField>

quoting-CypressTK1/force-app/main/default/objects/ProjectMilestone__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Occurs on a Date</fullName>
            </value>
            <value>
                <fullName>Aligned to Project Activity</fullName>
            </value>
            <value>
                <fullName>Aligned to another Milestone</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

quoting-CypressTK1/force-app/main/default/classes/ProjectMilestoneTriggers.cls
/*
 * Provus Services Quoting
 * Copyright (c) 2022 Provus Inc. All rights reserved.
 */

public with sharing class ProjectMilestoneTriggers {
	public static void processTrigger(List<ProjectMilestone__c> newMilestones) {
		for (ProjectMilestone__c milestoneSO : newMilestones) {
			if (
				milestoneSO.Type__c == ProjectMilestone.TYPE_MILESTONE ||
				milestoneSO.Type__c == ProjectMilestone.TYPE_ACTIVITY
			) {
				milestoneSO.AlignmentDate__c = milestoneSO.EstimatedOccurrenceDate__c;
			}
		}
	}
}