quoting-CypressTK1/force-app/main/default/objects/Adjustment__c/fields/Method__c.field-meta.xml
<CustomField>
    <fullName>Method__c</fullName>
    <label>Method</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Initial</fullName>
            </value>
            <value>
                <fullName>Manual</fullName>
            </value>
            <value>
                <fullName>Rule</fullName>
            </value>
            <value>
                <fullName>Contingency</fullName>
            </value>
            <value>
                <fullName>Cola</fullName>
            </value>
            <value>
                <fullName>Volume Discount</fullName>
            </value>
            <value>
                <fullName>Location Discount</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

quoting-CypressTK1/force-app/main/default/objects/VolumeDiscount__c/VolumeDiscount__c.object-meta.xml
<CustomObject>
    <description>Contains volume discount record</description>
    <label>Volume Discount</label>
    <nameField>
        <displayFormat>QVD-{00000}</displayFormat>
        <label>Volume Discount</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Volume Discounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

quoting-CypressTK1/force-app/main/default/objects/VolumeDiscount__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <description>Picklist of available category selections for quote volume discount</description>
    <inlineHelpText>Choose your quote volume discount category</inlineHelpText>
    <label>Category</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Headcount</fullName>
                <label>Headcount Discount</label>
            </value>
            <value>
                <fullName>Labor Revenue</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

quoting-CypressTK1/force-app/main/default/classes/PostInstallAdjustments.cls
/*
 * Provus Services Quoting
 * Copyright (c) 2022 Provus Inc. All rights reserved.
 */
public class PostInstallAdjustments {
	public static void onInstall(InstallContext context) {
		PicklistMetadataService.PicklistValue volumeDiscountPicklistOption = new PicklistMetadataService.PicklistValue();
		volumeDiscountPicklistOption.label = 'Volume Discount';
		volumeDiscountPicklistOption.fullName = 'Volume Discount';
		volumeDiscountPicklistOption.isActive = true;
		volumeDiscountPicklistOption.isDefault = false;

		PicklistMetadataService.addPicklistValue(
			Schema.Adjustment__c.SObjectType,
			Schema.Adjustment__c.Method__c,
			volumeDiscountPicklistOption
		);

		PicklistMetadataService.PicklistValue laborRevenuePicklistOption = new PicklistMetadataService.PicklistValue();
		laborRevenuePicklistOption.label = 'Labor Revenue';
		laborRevenuePicklistOption.fullName = 'Labor Revenue';
		laborRevenuePicklistOption.isActive = true;
		laborRevenuePicklistOption.isDefault = false;

		PicklistMetadataService.addPicklistValue(
			Schema.VolumeDiscount__c.SObjectType,
			Schema.VolumeDiscount__c.Category__c,
			laborRevenuePicklistOption
		);
	}
}