quoting-CypressTK1/force-app/main/default/objects/Product__c/Product__c.object-meta.xml
<CustomObject>
	<description>Provus Product object</description>
	<label>Product</label>
	<nameField>
		<label>Product Name</label>
		<type>Text</type>
	</nameField>
	<pluralLabel>Products</pluralLabel>
	<sharingModel>ReadWrite</sharingModel>
</CustomObject>

quoting-CypressTK1/force-app/main/default/objects/Product__c/fields/IsActive__c.field-meta.xml
<CustomField>
	<fullName>IsActive__c</fullName>
	<defaultValue>true</defaultValue>
	<description>Product Active</description>
	<label>Active</label>
	<type>Checkbox</type>
</CustomField>

quoting-CypressTK1/force-app/main/default/objects/Product__c/fields/ProductCode__c.field-meta.xml
<CustomField>
	<fullName>ProductCode__c</fullName>
	<label>Product Code</label>
	<length>255</length>
	<type>Text</type>
</CustomField>

quoting-CypressTK1/force-app/main/default/objects/Product__c/recordTypes/Product.recordType-meta.xml
<RecordType>
	<fullName>Product</fullName>
	<active>true</active>	
	<label>Product</label>
</RecordType>

quoting-CypressTK1/force-app/main/default/objects/Product__c/recordTypes/Service.recordType-meta.xml
<RecordType>
	<fullName>Service</fullName>
	<active>true</active>	
	<label>Service</label>
</RecordType>

quoting-CypressTK1/force-app/main/default/objects/Quote__c/fields/RateCardId__c.field-meta.xml
<CustomField>
    <fullName>RateCardId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Rate Card</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(6 OR 7) AND (3 OR 1) AND (4 OR 2) AND 5</booleanFilter>
        <errorMessage
		>The Rate Card is expired/inactive during the selected service start date</errorMessage>
        <filterItems>
            <field>$Source.ServiceStartDate__c</field>
            <operation>greaterOrEqual</operation>
            <valueField>RateCard__c.EffectiveDate__c</valueField>
        </filterItems>
        <filterItems>
            <field>$Source.ServiceStartDate__c</field>
            <operation>lessOrEqual</operation>
            <valueField>RateCard__c.ExpirationDate__c</valueField>
        </filterItems>
        <filterItems>
            <field>RateCard__c.EffectiveDate__c</field>
            <operation>equals</operation>
            <value />
        </filterItems>
        <filterItems>
            <field>RateCard__c.ExpirationDate__c</field>
            <operation>equals</operation>
            <value />
        </filterItems>
        <filterItems>
            <field>RateCard__c.IsActive__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>$Source.AccountId__c</field>
            <operation>equals</operation>
            <valueField>RateCard__c.AssignedToAccountId__c</valueField>
        </filterItems>
        <filterItems>
            <field>RateCard__c.AssignedToAccountId__c</field>
            <operation>equals</operation>
            <value />
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>RateCard__c</referenceTo>
    <relationshipLabel>Quotes</relationshipLabel>
    <relationshipName>Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

quoting-CypressTK1/force-app/main/default/classes/RateCardItemServiceTest.cls
/**
 *  Provus Services Quoting
 *  RateCardItemServiceTest
 *  @2021 Provus Inc. All rights reserved.
 */

@isTest
private class RateCardItemServiceTest extends TestBase {
	@testSetup
	static void setup() {
		Id resourceRoleTypeId = SObjectUtility.getRecordTypeIdbyName(
			Schema.SObjectType.Product__c.getName(),
			'Resource Role'
		);

		Product__c product = new Product__c(
			Name = 'SLA: Silver',
			ProductCode__c = 'SL9040',
			IsActive__c = true,
			RecordTypeId = resourceRoleTypeId
		);
		CRUDUtility.insertRecords(product);

		RateCard__c rateCard = newRateCard();
		newRateCardItem(rateCard.Id, product.Id);

		Quote__c quote = newQuote();
		quote.Name = 'Rate Card Item Service Test';
		quote.RateCardId__c = rateCard.Id;
		CRUDUtility.updateRecords(quote);
	}

	@isTest
	static void itShouldGetProductsFromQuote() {
		Test.startTest();
		Quote__c quote = [SELECT Id FROM Quote__c WHERE Name = 'Rate Card Item Service Test' LIMIT 1];
		List<RateCardItem__c> rateCardItems = RateCardItemService.getRateCardItemsProducts(quote.Id);
		System.assertEquals(1, rateCardItems.size(), 'expect to have 1 product');
		Test.stopTest();
	}

	@isTest
	static void itShouldGetRateCardItemForProduct() {
		Test.startTest();
		Quote__c quote = [SELECT Id FROM Quote__c WHERE Name = 'Rate Card Item Service Test' LIMIT 1];
		Product__c prod = [SELECT Id FROM Product__c WHERE Name = 'SLA: Silver' LIMIT 1];
		List<RateCardItemService.RateCardItemStruct> rateCardItems = RateCardItemService.getAllRateCardItemsForProduct(
			quote.Id,
			prod.Id
		);
		System.assertEquals(1, rateCardItems.size(), 'expect to have 1 product');
		Test.stopTest();
	}

	@isTest
	static void itShouldGetRateCardItem() {
		Test.startTest();
		RateCard__c rateCard = [
			SELECT Id
			FROM RateCard__c
			WHERE Name = 'Skill & Resource Location'
			LIMIT 1
		];
		Product__c prod = [SELECT Id FROM Product__c WHERE Name = 'SLA: Silver' LIMIT 1];
		List<RateCardItem__c> rateCardItems = RateCardItemService.getRateCardItems(
			rateCard.Id,
			new Set<Id>{ prod.Id }
		);
		System.assertEquals(1, rateCardItems.size(), 'expect to have 1 product');
		Test.stopTest();
	}
}