quoting-CypressTK1/force-app/main/default/objects/Product__c/Product__c.object-meta.xml
<CustomObject>
	<description>Provus Product object</description>
	<label>Product</label>
	<nameField>
		<label>Product Name</label>
		<type>Text</type>
	</nameField>
	<pluralLabel>Products</pluralLabel>
	<sharingModel>ReadWrite</sharingModel>
</CustomObject>

quoting-CypressTK1/force-app/main/default/objects/Product__c/fields/IsActive__c.field-meta.xml
<CustomField>
	<fullName>IsActive__c</fullName>
	<defaultValue>true</defaultValue>
	<description>Product Active</description>
	<label>Active</label>
	<type>Checkbox</type>
</CustomField>

quoting-CypressTK1/force-app/main/default/objects/RateCardAttributeGroup__c/RateCardAttributeGroup__c.object-meta.xml
<CustomObject>
    <label>Rate Card Attribute Group</label>
    <nameField>
        <label>Rate Card Attribute Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Rate Card Attribute Groups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

quoting-CypressTK1/force-app/main/default/objects/RateCardAttributeOption__c/RateCardAttributeOption__c.object-meta.xml
<CustomObject>
    <label>Rate Card Attribute Option</label>
    <nameField>
        <displayFormat>RCAO-{00000}</displayFormat>
        <label>Rate Card Attribute Option Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Rate Card Attribute Options</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

quoting-CypressTK1/force-app/main/default/objects/RateCardAttributeOption__c/fields/AttributeGroupId__c.field-meta.xml
<CustomField>
    <fullName>AttributeGroupId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Attribute Group</label>
    <referenceTo>RateCardAttributeGroup__c</referenceTo>
    <relationshipLabel>Rate Card Attribute Options</relationshipLabel>
    <relationshipName>RateCardAttributeOptions</relationshipName>
    <type>Lookup</type>
</CustomField>

quoting-CypressTK1/force-app/main/default/objects/RateCardAttributeOption__c/fields/RateCardAttributeId__c.field-meta.xml
<CustomField>
    <fullName>RateCardAttributeId__c</fullName>
    <label>Rate Card Attribute</label>
    <referenceTo>RateCardAttribute__c</referenceTo>
    <relationshipLabel>Rate Card Attribute Options</relationshipLabel>
    <relationshipName>RateCardAttributeOptions</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

quoting-CypressTK1/force-app/main/default/objects/RateCardAttributeOption__c/fields/RateCardAttributeOptionKey__c.field-meta.xml
<CustomField>
    <fullName>RateCardAttributeOptionKey__c</fullName>
    <externalId>true</externalId>
    <label>Rate Card Attribute Option Key</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

quoting-CypressTK1/force-app/main/default/objects/RateCardAttributeOption__c/fields/RateCardId__c.field-meta.xml
<CustomField>
    <fullName>RateCardId__c</fullName>
    <label>Rate Card</label>
    <referenceTo>RateCard__c</referenceTo>
    <relationshipLabel>Rate Card Attribute Options</relationshipLabel>
    <relationshipName>RateCardAttributeOptions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

quoting-CypressTK1/force-app/main/default/objects/RateCardAttributeOption__c/fields/TextValue__c.field-meta.xml
<CustomField>
    <fullName>TextValue__c</fullName>
    <label>Text Value</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

quoting-CypressTK1/force-app/main/default/objects/RateCardItem__c/fields/ProductId__c.field-meta.xml
<CustomField>
    <fullName>ProductId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product__c</referenceTo>
    <relationshipLabel>Rate Card Items</relationshipLabel>
    <relationshipName>RateCardItems</relationshipName>
    <type>Lookup</type>
</CustomField>

quoting-CypressTK1/force-app/main/default/objects/RateCardItemAttributeOption__c/RateCardItemAttributeOption__c.object-meta.xml
<CustomObject>
    <label>Rate Card Item Attribute Option</label>
    <nameField>
        <displayFormat>RCIAO-{00000}</displayFormat>
        <label>Rate Card Item Attribute Option</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Rate Card Item Attribute Options</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

quoting-CypressTK1/force-app/main/default/objects/RateCardItemAttributeOption__c/fields/AttributeOptionId__c.field-meta.xml
<CustomField>
    <fullName>AttributeOptionId__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Attribute Option</label>
    <referenceTo>RateCardAttributeOption__c</referenceTo>
    <relationshipLabel>Rate Card Items Attribute Options</relationshipLabel>
    <relationshipName>RateCardItemAttributeOptions</relationshipName>
    <type>Lookup</type>
</CustomField>

quoting-CypressTK1/force-app/main/default/objects/RateCardItemAttributeOption__c/fields/RateCardItemAttributeKey__c.field-meta.xml
<CustomField>
    <fullName>RateCardItemAttributeKey__c</fullName>
    <externalId>true</externalId>
    <label>Rate Card Item Attribute Key</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

quoting-CypressTK1/force-app/main/default/objects/RateCardItemAttributeOption__c/fields/RateCardItemId__c.field-meta.xml
<CustomField>
    <fullName>RateCardItemId__c</fullName>
    <label>Rate Card Item</label>
    <referenceTo>RateCardItem__c</referenceTo>
    <relationshipLabel>Rate Card Item Attribute Options</relationshipLabel>
    <relationshipName>RateCardItemAttributeOptions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

quoting-CypressTK1/force-app/main/default/classes/RateCardItemTriggersTest.cls
/**
 *  Provus Services Quoting
 *  RateCardItemTriggersTest
 *  @2022 Provus Inc. All rights reserved.
 */

@isTest
private class RateCardItemTriggersTest extends TestBase {
	@isTest
	static void itShouldCreateRateCardAttributeOptionsForRateCards() {
		RateCard__c testRateCard1 = newRateCard();
		RateCard__c testRateCard2 = newRateCard();

		RateCardAttributeGroup__c testAttributeGroup = newRateCardAttributeGroup();
		testRateCard1.AttributeGroupId__c = testAttributeGroup.Id;
		testRateCard2.AttributeGroupId__c = testAttributeGroup.Id;
		update new List<RateCard__c>{ testRateCard1, testRateCard2 };

		RateCardAttribute__c testAttribute = newRateCardAttribute(testAttributeGroup.Id);

		Product__c testProduct = newProduct('Test Resource', 'Resource Role');
		RateCardItem__c testRateCardItem1 = new RateCardItem__c(
			IsActive__c = true,
			RateCardId__c = testRateCard1.Id,
			ProductId__c = testProduct.Id,
			SkillLevel__c = 'L1'
		);
		RateCardItem__c testRateCardItem2 = new RateCardItem__c(
			IsActive__c = true,
			RateCardId__c = testRateCard2.Id,
			ProductId__c = testProduct.Id,
			SkillLevel__c = 'L2'
		);

		Test.startTest();
		insert new List<RateCardItem__c>{ testRateCardItem1, testRateCardItem2 };
		List<RateCardAttributeOption__c> optionsForRateCard1 = [
			SELECT
				Id,
				RateCardAttributeOptionKey__c,
				TextValue__c,
				AttributeGroupId__c,
				RateCardAttributeId__c,
				(SELECT RateCardItemAttributeKey__c, RateCardItemId__c FROM RateCardItemAttributeOptions__r)
			FROM RateCardAttributeOption__c
			WHERE RateCardId__c = :testRateCard1.Id
		];

		List<RateCardAttributeOption__c> optionsForRateCard2 = [
			SELECT
				Id,
				RateCardAttributeOptionKey__c,
				TextValue__c,
				AttributeGroupId__c,
				RateCardAttributeId__c,
				(SELECT RateCardItemAttributeKey__c, RateCardItemId__c FROM RateCardItemAttributeOptions__r)
			FROM RateCardAttributeOption__c
			WHERE RateCardId__c = :testRateCard2.Id
		];

		System.assertEquals(
			optionsForRateCard1[0].RateCardAttributeId__c,
			testAttribute.Id,
			'should have the right attribute associated'
		);
		System.assertEquals(
			optionsForRateCard2[0].RateCardAttributeId__c,
			testAttribute.Id,
			'should have the right attribute associated'
		);

		System.assertEquals(
			optionsForRateCard1[0].TextValue__c,
			testRateCardItem1.SkillLevel__c,
			'text value should match'
		);
		System.assertEquals(
			optionsForRateCard2[0].TextValue__c,
			testRateCardItem2.SkillLevel__c,
			'text value should match'
		);
	}

	@isTest
	static void itShouldNotCreateAttributeOptionsWhenRateCardAttributesAreNotDefined() {
		RateCard__c testRateCard = newRateCard();
		RateCardAttributeGroup__c testAttributeGroup = newRateCardAttributeGroup();
		testRateCard.AttributeGroupId__c = testAttributeGroup.Id;
		update testRateCard;

		Product__c testProduct = newProduct('Test Resource', 'Resource Role');
		RateCardItem__c testRateCardItem = new RateCardItem__c(
			IsActive__c = true,
			RateCardId__c = testRateCard.Id,
			ProductId__c = testProduct.Id,
			SkillLevel__c = 'L1'
		);

		Test.startTest();
		insert testRateCardItem;
		List<RateCardAttributeOption__c> optionsForRateCard = [
			SELECT
				Id,
				RateCardAttributeOptionKey__c,
				TextValue__c,
				AttributeGroupId__c,
				RateCardAttributeId__c,
				(SELECT RateCardItemAttributeKey__c, RateCardItemId__c FROM RateCardItemAttributeOptions__r)
			FROM RateCardAttributeOption__c
			WHERE RateCardId__c = :testRateCard.Id
		];

		System.assertEquals(optionsForRateCard.size(), 0, 'should not create attribute options');
	}
}