quoting-CypressTK1/force-app/main/default/objects/Product__c/Product__c.object-meta.xml
<CustomObject>
	<description>Provus Product object</description>
	<label>Product</label>
	<nameField>
		<label>Product Name</label>
		<type>Text</type>
	</nameField>
	<pluralLabel>Products</pluralLabel>
	<sharingModel>ReadWrite</sharingModel>
</CustomObject>

quoting-CypressTK1/force-app/main/default/objects/RateCardItem__c/fields/ProductId__c.field-meta.xml
<CustomField>
    <fullName>ProductId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product__c</referenceTo>
    <relationshipLabel>Rate Card Items</relationshipLabel>
    <relationshipName>RateCardItems</relationshipName>
    <type>Lookup</type>
</CustomField>

quoting-CypressTK1/force-app/main/default/classes/ResourceRoleDetail.cls
/**
 *  Provus Services Quoting
 *  EstimateResources
 *  @2022 Provus Inc. All rights reserved.
 */
public with sharing class ResourceRoleDetail {
	@AuraEnabled
	public String roleName;
	@AuraEnabled
	public Map<String, List<String>> skillMap;
	@AuraEnabled
	public String skill;
	@AuraEnabled
	public String location;
	@AuraEnabled
	public Integer sequence;

	@AuraEnabled
	public String skillId;
	@AuraEnabled
	public String locationId;

	public ResourceRoleDetail() {
	}

	public ResourceRoleDetail(RateCardItem__c rateCardItem) {
		roleName = rateCardItem.ProductId__r.Name;
		skillMap = new Map<String, List<String>>{
			rateCardItem.SkillLevel__c => new List<String>{ rateCardItem.LocationDisplayName__c }
		};
	}
}