quoting-CypressTK1/force-app/main/default/objects/ApprovalRequest__c/ApprovalRequest__c.object-meta.xml
<CustomObject>
    <label>Approval Request</label>
    <nameField>
        <displayFormat>AR-{00000}</displayFormat>
        <label>Approval Request</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Approval Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

quoting-CypressTK1/force-app/main/default/objects/ApprovalRequest__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

quoting-CypressTK1/force-app/main/default/objects/ApprovalRequestItem__c/ApprovalRequestItem__c.object-meta.xml
<CustomObject>
    <label>Approval Request Item</label>
    <nameField>
        <displayFormat>ARI-{00000}</displayFormat>
        <label>Approval Request Item</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Approval Request Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

quoting-CypressTK1/force-app/main/default/objects/ApprovalRequestItem__c/fields/ApprovalRequestId__c.field-meta.xml
<CustomField>
    <fullName>ApprovalRequestId__c</fullName>
    <label>Approval Request</label>
    <referenceTo>ApprovalRequest__c</referenceTo>
    <relationshipLabel>Approval Request Items</relationshipLabel>
    <relationshipName>ApprovalRequestItems</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

quoting-CypressTK1/force-app/main/default/objects/ApprovalRequestItem__c/fields/ApprovalSubmissionComments__c.field-meta.xml
<CustomField>
    <fullName>ApprovalSubmissionComments__c</fullName>
    <label>Approval Submission Comments</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

quoting-CypressTK1/force-app/main/default/objects/ApprovalRequestItem__c/fields/QuoteId__c.field-meta.xml
<CustomField>
    <fullName>QuoteId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quote</label>
    <referenceTo>Quote__c</referenceTo>
    <relationshipLabel>Approval Request Items</relationshipLabel>
    <relationshipName>ApprovalRequestItems</relationshipName>
    <type>Lookup</type>
</CustomField>

quoting-CypressTK1/force-app/main/default/objects/ApprovalRequestItem__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

quoting-CypressTK1/force-app/main/default/classes/QuoteCompareController.cls
/*
 * Provus Services Quoting
 * Copyright (c) 2022 Provus Inc. All rights reserved.
 */
public with sharing class QuoteCompareController {
	@AuraEnabled
	public static List<QuoteOverviewDto> getQuoteOverviewsForRequest(Id requestId) {
		List<Id> quoteIds = new List<Id>();
		Map<Id, String> submissionCommentsByQuoteId = new Map<Id, String>();
		for (ApprovalRequestItem__c item : [
			SELECT QuoteId__c, ApprovalSubmissionComments__c
			FROM ApprovalRequestItem__c
			WHERE ApprovalRequestId__c = :requestId AND ApprovalRequestId__r.Status__c = 'Submitted'
			WITH SECURITY_ENFORCED
			LIMIT :SOQLConstants.SOQL_QUERY_LIMIT
		]) {
			quoteIds.add(item.QuoteId__c);
			submissionCommentsByQuoteId.put(item.QuoteId__c, item.ApprovalSubmissionComments__c);
		}

		List<QuoteOverviewDto> overviews = getQuoteOverviews(quoteIds);
		for (QuoteOverviewDto overviewDto : overviews) {
			overviewDto.approvalSubmissionComments = submissionCommentsByQuoteId.get(overviewDto.id);
		}

		return overviews;
	}

	public static List<QuoteOverviewDto> getQuoteOverviews(List<Id> quoteIds) {
		List<QuoteOverviewDto> overviewDtos = new List<QuoteOverviewDto>();
		for (Quote__c quoteSo : [
			SELECT
				Id,
				Name,
				CreatedBy.Name,
				CreatedDate,
				TotalAmount__c,
				TimePeriod__c,
				DiscountAmount__c,
				MarginPercent__c,
				TotalCost__c,
				(SELECT Id FROM QuotePeriods__r)
			FROM Quote__c
			WHERE Id IN :quoteIds
			WITH SECURITY_ENFORCED
		]) {
			QuoteOverviewDto overviewDto = new QuoteOverviewDto(quoteSo);
			overviewDtos.add(overviewDto);

			for (QuoteSummaryDO summaryDto : QuoteSummaryService.getQuoteSummaries(quoteSo.Id)) {
				if (summaryDto.type == QuoteSummary.SUMMARYTYPE_LOCATION) {
					overviewDto.headcountByLocation.put(summaryDto.rowName, summaryDto.totalQuantity);
				}
			}
		}

		return overviewDtos;
	}

	@AuraEnabled
	public static void rejectQuotes(Id requestId, String rejectComments) {
		QuoteApprovalService.reject(requestId, rejectComments);
	}

	@AuraEnabled
	public static void approveQuote(Id requestId, Id quoteId) {
		QuoteApprovalService.approve(requestId, quoteId);
	}
}