quoting-CypressTK1/force-app/main/default/objects/VolumeDiscountTier__c/VolumeDiscountTier__c.object-meta.xml
<CustomObject>
    <description>Object holding volume discount tier details</description>
    <label>Volume Discount Tier</label>
    <nameField>
        <displayFormat>QVDT-{00000}</displayFormat>
        <label>Volume Discount Tier</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Volume Discount Tiers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

quoting-CypressTK1/force-app/main/default/objects/VolumeDiscountTier__c/fields/Discount__c.field-meta.xml
<CustomField>
    <fullName>Discount__c</fullName>
    <description>Quote volume discount tier percentage amount</description>
    <inlineHelpText>Quote volume discount tier percentage amount</inlineHelpText>
    <label>Discount</label>
    <precision>6</precision>
    <scale>3</scale>
    <type>Percent</type>
</CustomField>

quoting-CypressTK1/force-app/main/default/objects/VolumeDiscountTier__c/fields/From__c.field-meta.xml
<CustomField>
    <fullName>From__c</fullName>
    <description>Quote volume discount tier from numeric value</description>
    <inlineHelpText>Quote volume discount tier from numeric value</inlineHelpText>
    <label>From</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

quoting-CypressTK1/force-app/main/default/objects/VolumeDiscountTier__c/fields/Sequence__c.field-meta.xml
<CustomField>
    <fullName>Sequence__c</fullName>
    <description>Tier number indicating order within set of sibling records</description>
    <inlineHelpText>Tier number</inlineHelpText>
    <label>Sequence</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

quoting-CypressTK1/force-app/main/default/objects/VolumeDiscountTier__c/fields/To__c.field-meta.xml
<CustomField>
    <fullName>To__c</fullName>
    <description>Quote volume discount tier to numeric value</description>
    <inlineHelpText>Quote volume discount tier to numeric value</inlineHelpText>
    <label>To</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

quoting-CypressTK1/force-app/main/default/objects/VolumeDiscountTier__c/fields/VolumeDiscountId__c.field-meta.xml
<CustomField>
    <fullName>VolumeDiscountId__c</fullName>
    <description>Relationship to parent object Volume Discount</description>
    <inlineHelpText>Relationship to parent object Volume Discount</inlineHelpText>
    <label>Volume Discount</label>
    <referenceTo>VolumeDiscount__c</referenceTo>
    <relationshipLabel>Volume Discount Tiers</relationshipLabel>
    <relationshipName>VolumeDiscountTiers</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

quoting-CypressTK1/force-app/main/default/classes/VolumeDiscountTierDto.cls
/**
 *  Provus Services Quoting
 *  VolumeDiscountTier
 *  @2022 Provus Inc. All rights reserved.
 */
public with sharing virtual class VolumeDiscountTierDto extends BaseDTO {
	public VolumeDiscountTierDto() {
	}

	public VolumeDiscountTierDto(VolumeDiscountTier__c volumeDiscountSO) {
		this.volumeDiscountId = volumeDiscountSO.VolumeDiscountId__c;
		this.fromValue = volumeDiscountSO.From__c;
		this.toValue = volumeDiscountSO.To__c;
		this.discount = volumeDiscountSO.Discount__c;
		this.sequence = volumeDiscountSO.Sequence__c;
		this.id = volumeDiscountSO.Id;
	}

	@AuraEnabled
	public Id volumeDiscountId { get; set; }

	@AuraEnabled
	public Decimal fromValue { get; set; }

	@AuraEnabled
	public Decimal toValue { get; set; }

	@AuraEnabled
	public Decimal discount { get; set; }

	@AuraEnabled
	public Decimal sequence { get; set; }

	public override SObject refreshSo() {
		VolumeDiscountTier__c volumeDiscountTierSO = new VolumeDiscountTier__c(
			VolumeDiscountId__c = this.volumeDiscountId,
			Id = this.id,
			From__c = this.fromValue,
			To__c = this.toValue,
			Discount__c = this.discount,
			Sequence__c = this.sequence
		);

		return volumeDiscountTierSO;
	}
}