quoting-CypressTK1/force-app/main/default/objects/ResourceSplit__c/ResourceSplit__c.object-meta.xml
<CustomObject>
    <label>Resource Split</label>
    <nameField>
        <label>Resource Split Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Resource Splits</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

quoting-CypressTK1/force-app/main/default/objects/ResourceSplit__c/fields/LevelAdjustment__c.field-meta.xml
<CustomField>
    <fullName>LevelAdjustment__c</fullName>
    <formula>TaskRoleSummaryId__r.LevelAdjustment__c  *  SplitPercentage__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Level Adjustment</label>
    <precision>18</precision>
    <scale>5</scale>
    <type>Number</type>
</CustomField>

quoting-CypressTK1/force-app/main/default/objects/ResourceSplit__c/fields/TaskRoleSummaryId__c.field-meta.xml
<CustomField>
    <fullName>TaskRoleSummaryId__c</fullName>
    <label>Task Role Summary</label>
    <referenceTo>TaskRoleSummary__c</referenceTo>
    <relationshipLabel>Resource Splits</relationshipLabel>
    <relationshipName>ResourceSplits</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

quoting-CypressTK1/force-app/main/default/objects/ResourceSplit__c/fields/TotalAdjustments__c.field-meta.xml
<CustomField>
    <fullName>TotalAdjustments__c</fullName>
    <formula>TaskRoleSummaryId__r.TotalAdjustments__c  *  SplitPercentage__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total Adjustments</label>
    <precision>18</precision>
    <scale>5</scale>
    <type>Number</type>
</CustomField>

quoting-CypressTK1/force-app/main/default/objects/ResourceSplit__c/fields/TotalCalculatedDuration__c.field-meta.xml
<CustomField>
    <fullName>TotalCalculatedDuration__c</fullName>
    <formula>TaskRoleSummaryId__r.TotalCalculatedDuration__c  *  SplitPercentage__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total Calculated Duration</label>
    <precision>18</precision>
    <scale>5</scale>
    <type>Number</type>
</CustomField>

quoting-CypressTK1/force-app/main/default/objects/ResourceSplit__c/fields/TotalEstimatedDuration__c.field-meta.xml
<CustomField>
    <fullName>TotalEstimatedDuration__c</fullName>
    <formula>TaskRoleSummaryId__r.TotalEstimatedDuration__c  *  SplitPercentage__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total Estimated Duration</label>
    <precision>18</precision>
    <scale>5</scale>
    <type>Number</type>
</CustomField>

quoting-CypressTK1/force-app/main/default/objects/TaskRoleSummary__c/fields/LevelAdjustment__c.field-meta.xml
<CustomField>
    <fullName>LevelAdjustment__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Level adjustment</label>
    <precision>18</precision>
    <scale>5</scale>
    <type>Number</type>
</CustomField>

quoting-CypressTK1/force-app/main/default/objects/TaskRoleSummary__c/fields/RateCardItemId__c.field-meta.xml
<CustomField>
    <fullName>RateCardItemId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Rate Card Item</label>
    <referenceTo>RateCardItem__c</referenceTo>
    <relationshipLabel>Task Role Summaries</relationshipLabel>
    <relationshipName>TaskRoleSummaries</relationshipName>
    <type>Lookup</type>
</CustomField>

quoting-CypressTK1/force-app/main/default/objects/TaskRoleSummary__c/fields/ResourceRoleId__c.field-meta.xml
<CustomField>
    <fullName>ResourceRoleId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Resource Role</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Product__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Resource Role</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Product__c</referenceTo>
    <relationshipName>LevelSummaries</relationshipName>
    <type>Lookup</type>
</CustomField>

quoting-CypressTK1/force-app/main/default/objects/TaskRoleSummary__c/fields/SummaryLevel__c.field-meta.xml
<CustomField>
    <fullName>SummaryLevel__c</fullName>
    <label>Summary Level</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Estimate</fullName>
            </value>
            <value>
                <fullName>Activity Group</fullName>
            </value>
            <value>
                <fullName>Activity</fullName>
            </value>
            <value>
                <fullName>Phase</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

quoting-CypressTK1/force-app/main/default/objects/TaskRoleSummary__c/fields/TotalAdjustments__c.field-meta.xml
<CustomField>
    <fullName>TotalAdjustments__c</fullName>
    <formula>RolledUpAdjustments__c + LevelAdjustments__c + LevelAdjustment__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total adjustments</label>
    <precision>18</precision>
    <scale>5</scale>
    <type>Number</type>
</CustomField>

quoting-CypressTK1/force-app/main/default/objects/TaskRoleSummary__c/fields/TotalCalculatedDuration__c.field-meta.xml
<CustomField>
    <fullName>TotalCalculatedDuration__c</fullName>
    <formula>RolledUpCalculatedDuration__c + CalculatedDuration__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total calculated duration</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

quoting-CypressTK1/force-app/main/default/objects/TaskRoleSummary__c/fields/TotalEstimatedDuration__c.field-meta.xml
<CustomField>
    <fullName>TotalEstimatedDuration__c</fullName>
    <formula>TotalCalculatedDuration__c + TotalAdjustments__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total estimated duration</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

quoting-CypressTK1/force-app/main/default/classes/TaskRoleSummaryDto.cls
/*
 * Provus Services Quoting
 * Copyright (c) 2022 Provus Inc. All rights reserved.
 */
public with sharing class TaskRoleSummaryDto extends DurationDto {
	@AuraEnabled
	public String rateCardItemId { get; set; }
	@AuraEnabled
	public String resourceRole { get; set; }
	@AuraEnabled
	public Id resourceRoleId { get; set; }
	@AuraEnabled
	public Id estimateId { get; set; }
	@AuraEnabled
	public Id activityGroupId { get; set; }
	@AuraEnabled
	public Id activityId { get; set; }
	@AuraEnabled
	public String summaryLevel { get; set; }
	@AuraEnabled
	public List<ResourceSplitDTO> splits { get; set; }

	public TaskRoleSummaryDto() {
	}

	public TaskRoleSummaryDto(TaskRoleSummary__c roleSummarySo) {
		super(roleSummarySo);
		this.activityGroupId = roleSummarySo.ActivityGroupId__c;
		this.activityId = roleSummarySo.ActivityId__c;
		this.estimateId = roleSummarySo.EstimateId__c;
		this.levelAdjustment = roleSummarySo.LevelAdjustment__c;
		this.rateCardItemId = roleSummarySo.RateCardItemId__c;
		this.resourceRole = roleSummarySo.ResourceRole__c;
		this.resourceRoleId = roleSummarySo.ResourceRoleId__c;
		this.summaryLevel = roleSummarySo.SummaryLevel__c;
		this.totalAdjustments = roleSummarySo.TotalAdjustments__c;
		this.totalCalculatedDuration = roleSummarySo.TotalCalculatedDuration__c;
		this.totalEstimatedDuration = roleSummarySo.TotalEstimatedDuration__c;

		if (!SystemUtility.nullOrEmpty(roleSummarySo.ResourceSplits__r)) {
			splits = new List<ResourceSplitDTO>();
			for (ResourceSplit__c resourceSplitSo : roleSummarySo.ResourceSplits__r) {
				splits.add(new ResourceSplitDTO(resourceSplitSo));
			}
		}
	}

	public override SObject refreshSo() {
		if (this.sObj == null) {
			this.sObj = new TaskRoleSummary__c();
		}

		TaskRoleSummary__c roleSummarySo = (TaskRoleSummary__c) this.sObj;

		roleSummarySo.ActivityGroupId__c = this.activityGroupId;
		roleSummarySo.ActivityId__c = this.activityId;
		roleSummarySo.EstimateId__c = this.estimateId;
		roleSummarySo.Id = this.id;
		roleSummarySo.LevelAdjustment__c = this.levelAdjustment;
		roleSummarySo.RateCardItemId__c = this.rateCardItemId;
		roleSummarySo.ResourceRoleId__c = this.resourceRoleId;
		roleSummarySo.SummaryLevel__c = this.summaryLevel;

		return roleSummarySo;
	}
}