quoting-CypressTK1/force-app/main/default/objects/ResourceSplit__c/ResourceSplit__c.object-meta.xml
<CustomObject>
    <label>Resource Split</label>
    <nameField>
        <label>Resource Split Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Resource Splits</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

quoting-CypressTK1/force-app/main/default/objects/ResourceSplit__c/fields/SplitPercentage__c.field-meta.xml
<CustomField>
    <fullName>SplitPercentage__c</fullName>
    <label>Split Percentage</label>
    <precision>18</precision>
    <scale>15</scale>
    <type>Percent</type>
</CustomField>

quoting-CypressTK1/force-app/main/default/objects/ResourceSplit__c/fields/TaskRoleSummaryId__c.field-meta.xml
<CustomField>
    <fullName>TaskRoleSummaryId__c</fullName>
    <label>Task Role Summary</label>
    <referenceTo>TaskRoleSummary__c</referenceTo>
    <relationshipLabel>Resource Splits</relationshipLabel>
    <relationshipName>ResourceSplits</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

quoting-CypressTK1/force-app/main/default/classes/ResourceSplitServiceTest.cls
/*
 * Provus Services Quoting
 * Copyright (c) 2022 Provus Inc. All rights reserved.
 */
@IsTest
private class ResourceSplitServiceTest {
	@IsTest
	static void itShouldReturnSplitsForSummary() {
		TaskRoleSummary__c roleSummary = TaskRoleSummaryTestBase.newTaskRoleSummary();
		List<ResourceSplit__c> splits = new List<ResourceSplit__c>();
		splits.add(
			new ResourceSplit__c(
				Name = 'Test Role',
				TaskRoleSummaryId__c = roleSummary.Id,
				SplitPercentage__c = 100
			)
		);
		CRUDUtility.insertRecords(splits);
		Test.startTest();
		System.assert(
			ResourceSplitService.getSplitsForRoleSummary(roleSummary.Id).size() == 1,
			'should return resource splits for the role summary'
		);
		Test.stopTest();
	}
}