quoting-CypressTK1/force-app/main/default/objects/ResourceSplit__c/ResourceSplit__c.object-meta.xml
<CustomObject>
    <label>Resource Split</label>
    <nameField>
        <label>Resource Split Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Resource Splits</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

quoting-CypressTK1/force-app/main/default/objects/ResourceSplit__c/fields/LevelAdjustment__c.field-meta.xml
<CustomField>
    <fullName>LevelAdjustment__c</fullName>
    <formula>TaskRoleSummaryId__r.LevelAdjustment__c  *  SplitPercentage__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Level Adjustment</label>
    <precision>18</precision>
    <scale>5</scale>
    <type>Number</type>
</CustomField>

quoting-CypressTK1/force-app/main/default/objects/ResourceSplit__c/fields/SplitPercentage__c.field-meta.xml
<CustomField>
    <fullName>SplitPercentage__c</fullName>
    <label>Split Percentage</label>
    <precision>18</precision>
    <scale>15</scale>
    <type>Percent</type>
</CustomField>

quoting-CypressTK1/force-app/main/default/objects/ResourceSplit__c/fields/TaskRoleSummaryId__c.field-meta.xml
<CustomField>
    <fullName>TaskRoleSummaryId__c</fullName>
    <label>Task Role Summary</label>
    <referenceTo>TaskRoleSummary__c</referenceTo>
    <relationshipLabel>Resource Splits</relationshipLabel>
    <relationshipName>ResourceSplits</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

quoting-CypressTK1/force-app/main/default/objects/ResourceSplit__c/fields/TotalAdjustments__c.field-meta.xml
<CustomField>
    <fullName>TotalAdjustments__c</fullName>
    <formula>TaskRoleSummaryId__r.TotalAdjustments__c  *  SplitPercentage__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total Adjustments</label>
    <precision>18</precision>
    <scale>5</scale>
    <type>Number</type>
</CustomField>

quoting-CypressTK1/force-app/main/default/objects/ResourceSplit__c/fields/TotalCalculatedDuration__c.field-meta.xml
<CustomField>
    <fullName>TotalCalculatedDuration__c</fullName>
    <formula>TaskRoleSummaryId__r.TotalCalculatedDuration__c  *  SplitPercentage__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total Calculated Duration</label>
    <precision>18</precision>
    <scale>5</scale>
    <type>Number</type>
</CustomField>

quoting-CypressTK1/force-app/main/default/objects/ResourceSplit__c/fields/TotalEstimatedDuration__c.field-meta.xml
<CustomField>
    <fullName>TotalEstimatedDuration__c</fullName>
    <formula>TaskRoleSummaryId__r.TotalEstimatedDuration__c  *  SplitPercentage__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total Estimated Duration</label>
    <precision>18</precision>
    <scale>5</scale>
    <type>Number</type>
</CustomField>

quoting-CypressTK1/force-app/main/default/objects/TaskRoleSummary__c/fields/EstimatedAmount__c.field-meta.xml
<CustomField>
    <fullName>EstimatedAmount__c</fullName>
    <label>Estimated Amount</label>
    <precision>18</precision>
    <scale>5</scale>
    <type>Currency</type>
</CustomField>

quoting-CypressTK1/force-app/main/default/objects/TaskRoleSummary__c/fields/EstimatedCost__c.field-meta.xml
<CustomField>
    <fullName>EstimatedCost__c</fullName>
    <label>Estimated Cost</label>
    <precision>18</precision>
    <scale>5</scale>
    <type>Currency</type>
</CustomField>

quoting-CypressTK1/force-app/main/default/objects/TaskRoleSummary__c/fields/EstimatedDuration__c.field-meta.xml
<CustomField>
    <fullName>EstimatedDuration__c</fullName>
    <label>Estimated duration</label>
    <summarizedField>Task__c.EstimatedDuration__c</summarizedField>
    <summaryForeignKey>Task__c.RoleSummaryId__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

quoting-CypressTK1/force-app/main/default/objects/TaskRoleSummary__c/fields/LevelAdjustment__c.field-meta.xml
<CustomField>
    <fullName>LevelAdjustment__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Level adjustment</label>
    <precision>18</precision>
    <scale>5</scale>
    <type>Number</type>
</CustomField>

quoting-CypressTK1/force-app/main/default/objects/TaskRoleSummary__c/fields/PhaseId__c.field-meta.xml
<CustomField>
    <fullName>PhaseId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Phase</label>
    <referenceTo>Phase__c</referenceTo>
    <relationshipLabel>Role Summaries</relationshipLabel>
    <relationshipName>RoleSummaries</relationshipName>
    <type>Lookup</type>
</CustomField>

quoting-CypressTK1/force-app/main/default/objects/TaskRoleSummary__c/fields/RateCardItemId__c.field-meta.xml
<CustomField>
    <fullName>RateCardItemId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Rate Card Item</label>
    <referenceTo>RateCardItem__c</referenceTo>
    <relationshipLabel>Task Role Summaries</relationshipLabel>
    <relationshipName>TaskRoleSummaries</relationshipName>
    <type>Lookup</type>
</CustomField>

quoting-CypressTK1/force-app/main/default/objects/TaskRoleSummary__c/fields/ResourceRoleId__c.field-meta.xml
<CustomField>
    <fullName>ResourceRoleId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Resource Role</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Product__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Resource Role</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Product__c</referenceTo>
    <relationshipName>LevelSummaries</relationshipName>
    <type>Lookup</type>
</CustomField>

quoting-CypressTK1/force-app/main/default/objects/TaskRoleSummary__c/fields/RolledUpAdjustments__c.field-meta.xml
<CustomField>
    <fullName>RolledUpAdjustments__c</fullName>
    <label>Rolled-up adjustments</label>
    <precision>18</precision>
    <scale>5</scale>
    <type>Number</type>
</CustomField>

quoting-CypressTK1/force-app/main/default/objects/TaskRoleSummary__c/fields/RolledUpCalculatedDuration__c.field-meta.xml
<CustomField>
    <fullName>RolledUpCalculatedDuration__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Rolled-up calculated duration</label>
    <precision>18</precision>
    <scale>5</scale>
    <type>Number</type>
</CustomField>

quoting-CypressTK1/force-app/main/default/objects/TaskRoleSummary__c/fields/SummaryLevel__c.field-meta.xml
<CustomField>
    <fullName>SummaryLevel__c</fullName>
    <label>Summary Level</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Estimate</fullName>
            </value>
            <value>
                <fullName>Activity Group</fullName>
            </value>
            <value>
                <fullName>Activity</fullName>
            </value>
            <value>
                <fullName>Phase</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

quoting-CypressTK1/force-app/main/default/objects/TaskRoleSummary__c/fields/TotalAdjustments__c.field-meta.xml
<CustomField>
    <fullName>TotalAdjustments__c</fullName>
    <formula>RolledUpAdjustments__c + LevelAdjustments__c + LevelAdjustment__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total adjustments</label>
    <precision>18</precision>
    <scale>5</scale>
    <type>Number</type>
</CustomField>

quoting-CypressTK1/force-app/main/default/objects/TaskRoleSummary__c/fields/TotalCalculatedDuration__c.field-meta.xml
<CustomField>
    <fullName>TotalCalculatedDuration__c</fullName>
    <formula>RolledUpCalculatedDuration__c + CalculatedDuration__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total calculated duration</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

quoting-CypressTK1/force-app/main/default/objects/TaskRoleSummary__c/fields/TotalEstimatedAmount__c.field-meta.xml
<CustomField>
    <fullName>TotalEstimatedAmount__c</fullName>
    <formula>RateCardItemId__r.UnitPrice__c / (CASE(RateCardItemId__r.PriceUOM__c ,
&apos;Daily&apos;, $CustomMetadata.ScheduleSetting__mdt.StandardSchedule.StandardDayHours__c,
&apos;Weekly&apos;, $CustomMetadata.ScheduleSetting__mdt.StandardSchedule.StandardWeekHours__c,
&apos;Monthly&apos;, $CustomMetadata.ScheduleSetting__mdt.StandardSchedule.StandardMonthHours__c,
&apos;Yearly&apos;, $CustomMetadata.ScheduleSetting__mdt.StandardSchedule.StandardYearHours__c,
1)) *  TotalEstimatedDuration__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total Estimated Amount</label>
    <precision>18</precision>
    <scale>5</scale>
    <type>Currency</type>
</CustomField>

quoting-CypressTK1/force-app/main/default/objects/TaskRoleSummary__c/fields/TotalEstimatedCost__c.field-meta.xml
<CustomField>
    <fullName>TotalEstimatedCost__c</fullName>
    <formula>RateCardItemId__r.UnitCost__c / (CASE(RateCardItemId__r.PriceUOM__c ,
&apos;Daily&apos;, $CustomMetadata.ScheduleSetting__mdt.StandardSchedule.StandardDayHours__c,
&apos;Weekly&apos;, $CustomMetadata.ScheduleSetting__mdt.StandardSchedule.StandardWeekHours__c,
&apos;Monthly&apos;, $CustomMetadata.ScheduleSetting__mdt.StandardSchedule.StandardMonthHours__c,
&apos;Yearly&apos;, $CustomMetadata.ScheduleSetting__mdt.StandardSchedule.StandardYearHours__c,
1)) *  TotalEstimatedDuration__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total Estimated Cost</label>
    <precision>18</precision>
    <scale>5</scale>
    <type>Currency</type>
</CustomField>

quoting-CypressTK1/force-app/main/default/objects/TaskRoleSummary__c/fields/TotalEstimatedDuration__c.field-meta.xml
<CustomField>
    <fullName>TotalEstimatedDuration__c</fullName>
    <formula>TotalCalculatedDuration__c + TotalAdjustments__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total estimated duration</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

quoting-CypressTK1/force-app/main/default/classes/ResourceSummaryController.cls
/*
 * Provus Services Quoting
 * Copyright (c) 2022 Provus Inc. All rights reserved.
 */

public with sharing class ResourceSummaryController {
	@AuraEnabled
	public static void addResource(List<TaskRoleSummaryDto> roleSummaryDtos) {
		List<TaskRoleSummary__c> roleSummaries = new List<TaskRoleSummary__c>();
		for (TaskRoleSummaryDto roleSummaryDto : roleSummaryDtos) {
			roleSummaries.add((TaskRoleSummary__c) roleSummaryDto.refreshSo());
		}

		EstimateTreeSummarySupport.createSummaryRecords(
			roleSummaries[0],
			roleSummaries[0].SummaryLevel__c
		);
	}

	@AuraEnabled
	public static void adjustHours(TaskRoleSummaryDto roleSummaryDto) {
		TaskRoleSummary__c roleSummarySo = (TaskRoleSummary__c) roleSummaryDto.refreshSo();
		CRUDUtility.updateRecords(
			new TaskRoleSummary__c(
				Id = roleSummarySo.Id,
				LevelAdjustment__c = roleSummarySo.LevelAdjustment__c
			)
		);
	}

	@AuraEnabled
	public static List<TaskRoleSummaryDto> getRoleSummaries(String type, Id recordId) {
		List<TaskRoleSummaryDto> roleSummaryDtos = new List<TaskRoleSummaryDto>();
		for (TaskRoleSummary__c roleSummarySo : [
			SELECT
				ActivityGroupId__c,
				ActivityId__c,
				CalculatedDuration__c,
				EstimatedAmount__c,
				EstimatedCost__c,
				EstimatedDuration__c,
				EstimateId__c,
				Id,
				LevelAdjustment__c,
				LevelAdjustments__c,
				PhaseId__c,
				RateCardItemId__c,
				ResourceRole__c,
				ResourceRoleId__c,
				RolledUpAdjustments__c,
				RolledUpCalculatedDuration__c,
				RolledUpEstimatedDuration__c,
				SummaryId__c,
				SummaryLevel__c,
				TaskRoleSummaryId__c,
				TotalAdjustments__c,
				TotalCalculatedDuration__c,
				TotalEstimatedAmount__c,
				TotalEstimatedCost__c,
				TotalEstimatedDuration__c,
				(
					SELECT
						Name,
						TaskRoleSummaryId__c,
						TotalEstimatedDuration__c,
						TotalAdjustments__c,
						TotalCalculatedDuration__c,
						LevelAdjustment__c,
						SplitPercentage__c,
						Sequence__c
					FROM ResourceSplits__r
					ORDER BY Name
				)
			FROM TaskRoleSummary__c
			WHERE
				SummaryLevel__c = :type
				AND (EstimateId__c = :recordId
				OR ActivityGroupId__c = :recordId
				OR ActivityId__c = :recordId)
			WITH SECURITY_ENFORCED
		]) {
			roleSummaryDtos.add(new TaskRoleSummaryDto(roleSummarySo));
		}

		return roleSummaryDtos;
	}

	@AuraEnabled
	public static void updateNotApplicableField(
		String recordId,
		Boolean isNotApplicable,
		String type
	) {
		if (type == EstimatorConstants.ACTIVITY_GROUP) {
			EstimateTreeService.notApplicableForActivityGroup(recordId, isNotApplicable);
		} else if (type == EstimatorConstants.ACTIVITY) {
			EstimateTreeService.notApplicableForActivity(recordId, isNotApplicable);
		} else if (type == EstimatorConstants.PHASE) {
			EstimateTreeService.notApplicableForPhase(recordId, isNotApplicable);
		}
	}
}