quoting-CypressTK1/force-app/main/default/objects/ResourceSplit__c/ResourceSplit__c.object-meta.xml
<CustomObject>
    <label>Resource Split</label>
    <nameField>
        <label>Resource Split Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Resource Splits</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

quoting-CypressTK1/force-app/main/default/objects/ResourceSplit__c/fields/LevelAdjustment__c.field-meta.xml
<CustomField>
    <fullName>LevelAdjustment__c</fullName>
    <formula>TaskRoleSummaryId__r.LevelAdjustment__c  *  SplitPercentage__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Level Adjustment</label>
    <precision>18</precision>
    <scale>5</scale>
    <type>Number</type>
</CustomField>

quoting-CypressTK1/force-app/main/default/objects/ResourceSplit__c/fields/SplitPercentage__c.field-meta.xml
<CustomField>
    <fullName>SplitPercentage__c</fullName>
    <label>Split Percentage</label>
    <precision>18</precision>
    <scale>15</scale>
    <type>Percent</type>
</CustomField>

quoting-CypressTK1/force-app/main/default/objects/ResourceSplit__c/fields/TaskRoleSummaryId__c.field-meta.xml
<CustomField>
    <fullName>TaskRoleSummaryId__c</fullName>
    <label>Task Role Summary</label>
    <referenceTo>TaskRoleSummary__c</referenceTo>
    <relationshipLabel>Resource Splits</relationshipLabel>
    <relationshipName>ResourceSplits</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

quoting-CypressTK1/force-app/main/default/objects/ResourceSplit__c/fields/TotalAdjustments__c.field-meta.xml
<CustomField>
    <fullName>TotalAdjustments__c</fullName>
    <formula>TaskRoleSummaryId__r.TotalAdjustments__c  *  SplitPercentage__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total Adjustments</label>
    <precision>18</precision>
    <scale>5</scale>
    <type>Number</type>
</CustomField>

quoting-CypressTK1/force-app/main/default/objects/ResourceSplit__c/fields/TotalCalculatedDuration__c.field-meta.xml
<CustomField>
    <fullName>TotalCalculatedDuration__c</fullName>
    <formula>TaskRoleSummaryId__r.TotalCalculatedDuration__c  *  SplitPercentage__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total Calculated Duration</label>
    <precision>18</precision>
    <scale>5</scale>
    <type>Number</type>
</CustomField>

quoting-CypressTK1/force-app/main/default/objects/ResourceSplit__c/fields/TotalEstimatedDuration__c.field-meta.xml
<CustomField>
    <fullName>TotalEstimatedDuration__c</fullName>
    <formula>TaskRoleSummaryId__r.TotalEstimatedDuration__c  *  SplitPercentage__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total Estimated Duration</label>
    <precision>18</precision>
    <scale>5</scale>
    <type>Number</type>
</CustomField>

quoting-CypressTK1/force-app/main/default/classes/ResourceSplitDTO.cls
/*
 * Provus Services Quoting
 * Copyright (c) 2022 Provus Inc. All rights reserved.
 */
public with sharing class ResourceSplitDTO extends DurationDto {
	public ResourceSplit__c splitSO;
	@AuraEnabled
	public Decimal splitPercentage { get; set; }
	@AuraEnabled
	public Id taskRoleSummaryId { get; set; }
	@AuraEnabled
	public Integer sequence { get; set; }

	public ResourceSplitDTO() {
	}

	public ResourceSplitDTO(ResourceSplit__c splitSO) {
		this.id = splitSO.Id;
		this.name = splitSO.Name;
		this.totalEstimatedDuration = splitSO.TotalEstimatedDuration__c;
		this.totalAdjustments = splitSO.TotalAdjustments__c;
		this.totalCalculatedDuration = splitSO.TotalCalculatedDuration__c;
		this.levelAdjustment = splitSO.LevelAdjustment__c;
		this.splitPercentage = splitSO.SplitPercentage__c;
		this.taskRoleSummaryId = splitSO.TaskRoleSummaryId__c;
		this.sequence = (Integer) splitSO.Sequence__c;
	}

	public override SObject refreshSo() {
		if (this.splitSO == null) {
			this.splitSO = new ResourceSplit__c(TaskRoleSummaryId__c = this.taskRoleSummaryId);
		}

		this.splitSO.Id = this.id;
		this.splitSO.Name = this.name;
		this.splitSO.SplitPercentage__c = this.splitPercentage;
		this.splitSO.Sequence__c = (Integer) this.sequence;

		return this.splitSO;
	}
}