quoting-CypressTK1/force-app/main/default/objects/ActivityGroup__c/fields/PhaseId__c.field-meta.xml
<CustomField>
    <fullName>PhaseId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Phase</label>
    <referenceTo>Phase__c</referenceTo>
    <relationshipLabel>Phases</relationshipLabel>
    <relationshipName>Phases</relationshipName>
    <type>Lookup</type>
</CustomField>

quoting-CypressTK1/force-app/main/default/objects/Estimate__c/fields/ProductId__c.field-meta.xml
<CustomField>
    <fullName>ProductId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Product__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Product</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Product__c</referenceTo>
    <relationshipLabel>Estimates</relationshipLabel>
    <relationshipName>ProductEstimates</relationshipName>
    <type>Lookup</type>
</CustomField>

quoting-CypressTK1/force-app/main/default/objects/Estimate__c/fields/ServiceId__c.field-meta.xml
<CustomField>
    <fullName>ServiceId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(1 AND 2) OR (3 AND 4)</booleanFilter>
        <filterItems>
            <field>$Source.ProductId__c</field>
            <operation>equals</operation>
            <valueField>Product__c.AssociatedProductId__c</valueField>
        </filterItems>
        <filterItems>
            <field>Product__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Service</value>
        </filterItems>
        <filterItems>
            <field>$Source.ProductId__c</field>
            <operation>equals</operation>
            <value />
        </filterItems>
        <filterItems>
            <field>Product__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Service</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Product__c</referenceTo>
    <relationshipLabel>Estimates</relationshipLabel>
    <relationshipName>ServiceEstimates</relationshipName>
    <type>Lookup</type>
</CustomField>

quoting-CypressTK1/force-app/main/default/objects/Estimate__c/fields/UseProjectPhases__c.field-meta.xml
<CustomField>
    <fullName>UseProjectPhases__c</fullName>
    <defaultValue>false</defaultValue>
    <description
	>When enabled, Estimate will use Project Phases as their top level grouping item rather than Activity Groups</description>
    <label>Use Project Phases</label>
    <type>Checkbox</type>
</CustomField>

quoting-CypressTK1/force-app/main/default/objects/EstimateTemplate__c/fields/ProductId__c.field-meta.xml
<CustomField>
    <fullName>ProductId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Product__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Product</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Product__c</referenceTo>
    <relationshipLabel>Estimate Templates</relationshipLabel>
    <relationshipName>ProductEstimateTemplates</relationshipName>
    <type>Lookup</type>
</CustomField>

quoting-CypressTK1/force-app/main/default/objects/EstimateTemplate__c/fields/ServiceId__c.field-meta.xml
<CustomField>
    <fullName>ServiceId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(1 AND 2) OR (3 AND 4)</booleanFilter>
        <filterItems>
            <field>$Source.ProductId__c</field>
            <operation>equals</operation>
            <valueField>Product__c.AssociatedProductId__c</valueField>
        </filterItems>
        <filterItems>
            <field>Product__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Service</value>
        </filterItems>
        <filterItems>
            <field>$Source.ProductId__c</field>
            <operation>equals</operation>
            <value />
        </filterItems>
        <filterItems>
            <field>Product__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Service</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Product__c</referenceTo>
    <relationshipLabel>Estimate Templates</relationshipLabel>
    <relationshipName>ServiceEstimateTemplates</relationshipName>
    <type>Lookup</type>
</CustomField>

quoting-CypressTK1/force-app/main/default/objects/Phase__c/Phase__c.object-meta.xml
<CustomObject>
    <label>Phase</label>
    <nameField>
        <label>Phase Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Phases</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

quoting-CypressTK1/force-app/main/default/objects/Phase__c/fields/EstimateId__c.field-meta.xml
<CustomField>
    <fullName>EstimateId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Estimate</label>
    <referenceTo>Estimate__c</referenceTo>
    <relationshipLabel>Phases</relationshipLabel>
    <relationshipName>Phases</relationshipName>
    <type>Lookup</type>
</CustomField>

quoting-CypressTK1/force-app/main/default/objects/Product__c/Product__c.object-meta.xml
<CustomObject>
	<description>Provus Product object</description>
	<label>Product</label>
	<nameField>
		<label>Product Name</label>
		<type>Text</type>
	</nameField>
	<pluralLabel>Products</pluralLabel>
	<sharingModel>ReadWrite</sharingModel>
</CustomObject>

quoting-CypressTK1/force-app/main/default/objects/Product__c/fields/Description__c.field-meta.xml
<CustomField>
	<fullName>Description__c</fullName>
	<label>Product Description</label>
	<type>TextArea</type>
</CustomField>

quoting-CypressTK1/force-app/main/default/objects/Product__c/fields/IsActive__c.field-meta.xml
<CustomField>
	<fullName>IsActive__c</fullName>
	<defaultValue>true</defaultValue>
	<description>Product Active</description>
	<label>Active</label>
	<type>Checkbox</type>
</CustomField>

quoting-CypressTK1/force-app/main/default/classes/CreateEstimateServiceTest.cls
@IsTest
private class CreateEstimateServiceTest extends EstimateTestBase {
	@testSetup
	static void setup() {
		EstimateTemplate__c estimateTemplate = EstimateTemplateTestBase.newEstimateTemplate();
		List<ActivityGroupTemplate__c> activityGroupTemplates = EstimateTemplateTestBase.createActivityGroupTemplates(
			estimateTemplate.Id,
			null
		);
		List<ActivityTemplate__c> activityTemplates = EstimateTemplateTestBase.createActivityTemplates(
			activityGroupTemplates
		);
		List<Product__c> resourceRoles = createResourceRoles();
		EstimateTemplateTestBase.createTaskTemplates(activityTemplates, resourceRoles);
	}

	@IsTest
	static void phaseSetup() {
		EstimateTemplate__c estimateTemplate = EstimateTemplateTestBase.newEstimateTemplate(true);
		CRUDUtility.updateRecords(estimateTemplate);
		List<PhaseTemplate__c> phaseTemplates = EstimateTemplateTestBase.createPhaseTemplates(
			estimateTemplate.Id
		);
		EstimateTemplateTestBase.createActivityGroupTemplates(
			estimateTemplate.Id,
			phaseTemplates[0].Id
		);

		Test.startTest();
		EstimateTemplate__c estimateTemplate1 = [
			SELECT
				Id,
				Name,
				Description__c,
				Guidance__c,
				IsActive__c,
				RateCardId__c,
				ProductId__c,
				ServiceId__c,
				UseProjectPhases__c,
				ServiceId__r.Name,
				(
					SELECT Id, Name, Description__c, Guidance__c, Sequence__c, IsActive__c, PhaseTemplateId__c
					FROM ActivityGroups__r
					WHERE IsActive__c = TRUE
				),
				(
					SELECT Id, Name, Description__c, Guidance__c, Sequence__c
					FROM Phases__r
					WHERE IsActive__c = TRUE
				)
			FROM EstimateTemplate__c
			WHERE Id = :estimateTemplate.Id
			WITH SECURITY_ENFORCED
		];

		Estimate__c estimate = Estimate.newSO(estimateTemplate1);
		CRUDUtility.insertRecords(estimate);
		Map<Id, Phase__c> phasesByTemplateId = CreateEstimateSupport.createPhases(
			estimateTemplate1,
			estimate.Id
		);

		System.assertEquals(
			estimateTemplate1.Phases__r.size(),
			phasesByTemplateId.values().size(),
			'Phases not configured properly'
		);

		Map<Id, ActivityGroup__c> activitiesByTemplateId = CreateEstimateSupport.createActivityGroups(
			estimateTemplate.ActivityGroups__r,
			estimate.Id,
			phasesByTemplateId
		);
		Test.stopTest();

		System.assertEquals(
			estimateTemplate.ActivityGroups__r.size(),
			activitiesByTemplateId.values().size(),
			'Activities not configured properly'
		);
	}

	@IsTest
	static void createEstimateFromEstimateTemplateTest() {
		EstimateTemplate__c estimateTemplate = [
			SELECT
				Id,
				Name,
				Description__c,
				Guidance__c,
				IsActive__c,
				RateCardId__c,
				ProductId__c,
				ServiceId__c,
				UseProjectPhases__c,
				ServiceId__r.Name
			FROM EstimateTemplate__c
			WHERE Name = 'CLM Development Estimate'
		];

		Test.startTest();
		Estimate__c estimate = Estimate.newSO(estimateTemplate);
		Test.stopTest();

		System.assertEquals(estimateTemplate.Name, estimate.Name, 'Estimate not configured properly');
		System.assertEquals(
			estimateTemplate.Description__c,
			estimate.Description__c,
			'Estimate not configured properly'
		);
	}

	@IsTest
	static void getActivityGroupsFromTemplateTest() {
		EstimateTemplate__c estimateTemplate = [
			SELECT
				Id,
				Name,
				Description__c,
				Guidance__c,
				IsActive__c,
				RateCardId__c,
				ProductId__c,
				ServiceId__c,
				UseProjectPhases__c,
				ServiceId__r.Name,
				(
					SELECT Id, Name, Description__c, Guidance__c, Sequence__c, PhaseTemplateId__c
					FROM ActivityGroups__r
					WHERE IsActive__c = TRUE
				)
			FROM EstimateTemplate__c
			WHERE Name = 'CLM Development Estimate'
		];

		Test.startTest();
		Estimate__c estimate = Estimate.newSO(estimateTemplate);
		CRUDUtility.insertRecords(estimate);
		Map<Id, ActivityGroup__c> activitiesByTemplateId = CreateEstimateSupport.createActivityGroups(
			estimateTemplate.ActivityGroups__r,
			estimate.Id,
			new Map<Id, Phase__c>()
		);
		Test.stopTest();

		System.assertEquals(
			estimateTemplate.ActivityGroups__r.size(),
			activitiesByTemplateId.values().size(),
			'Activities not configured properly'
		);
	}
}