quoting-CypressTK1/force-app/main/default/objects/ActivityGroup__c/fields/PhaseId__c.field-meta.xml
<CustomField>
    <fullName>PhaseId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Phase</label>
    <referenceTo>Phase__c</referenceTo>
    <relationshipLabel>Phases</relationshipLabel>
    <relationshipName>Phases</relationshipName>
    <type>Lookup</type>
</CustomField>

quoting-CypressTK1/force-app/main/default/objects/EstimateTemplate__c/fields/ProductId__c.field-meta.xml
<CustomField>
    <fullName>ProductId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Product__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Product</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Product__c</referenceTo>
    <relationshipLabel>Estimate Templates</relationshipLabel>
    <relationshipName>ProductEstimateTemplates</relationshipName>
    <type>Lookup</type>
</CustomField>

quoting-CypressTK1/force-app/main/default/objects/EstimateTemplate__c/fields/ServiceId__c.field-meta.xml
<CustomField>
    <fullName>ServiceId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(1 AND 2) OR (3 AND 4)</booleanFilter>
        <filterItems>
            <field>$Source.ProductId__c</field>
            <operation>equals</operation>
            <valueField>Product__c.AssociatedProductId__c</valueField>
        </filterItems>
        <filterItems>
            <field>Product__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Service</value>
        </filterItems>
        <filterItems>
            <field>$Source.ProductId__c</field>
            <operation>equals</operation>
            <value />
        </filterItems>
        <filterItems>
            <field>Product__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Service</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Product__c</referenceTo>
    <relationshipLabel>Estimate Templates</relationshipLabel>
    <relationshipName>ServiceEstimateTemplates</relationshipName>
    <type>Lookup</type>
</CustomField>

quoting-CypressTK1/force-app/main/default/objects/Phase__c/Phase__c.object-meta.xml
<CustomObject>
    <label>Phase</label>
    <nameField>
        <label>Phase Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Phases</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

quoting-CypressTK1/force-app/main/default/objects/Phase__c/fields/EstimateId__c.field-meta.xml
<CustomField>
    <fullName>EstimateId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Estimate</label>
    <referenceTo>Estimate__c</referenceTo>
    <relationshipLabel>Phases</relationshipLabel>
    <relationshipName>Phases</relationshipName>
    <type>Lookup</type>
</CustomField>

quoting-CypressTK1/force-app/main/default/objects/Product__c/Product__c.object-meta.xml
<CustomObject>
	<description>Provus Product object</description>
	<label>Product</label>
	<nameField>
		<label>Product Name</label>
		<type>Text</type>
	</nameField>
	<pluralLabel>Products</pluralLabel>
	<sharingModel>ReadWrite</sharingModel>
</CustomObject>

quoting-CypressTK1/force-app/main/default/objects/Product__c/fields/Description__c.field-meta.xml
<CustomField>
	<fullName>Description__c</fullName>
	<label>Product Description</label>
	<type>TextArea</type>
</CustomField>

quoting-CypressTK1/force-app/main/default/objects/Product__c/fields/IsActive__c.field-meta.xml
<CustomField>
	<fullName>IsActive__c</fullName>
	<defaultValue>true</defaultValue>
	<description>Product Active</description>
	<label>Active</label>
	<type>Checkbox</type>
</CustomField>

quoting-CypressTK1/force-app/main/default/classes/CreateEstimateSupport.cls
public with sharing class CreateEstimateSupport {
	public static EstimateTemplate__c getEstimateTemplate(Id estimateTemplateId) {
		EstimateTemplate__c estimateTemplate = [
			SELECT
				Id,
				Name,
				Description__c,
				Guidance__c,
				IsActive__c,
				RateCardId__c,
				ProductId__c,
				ServiceId__c,
				UseProjectPhases__c,
				ServiceId__r.Name,
				(
					SELECT Id, Name, Description__c, Guidance__c, Sequence__c, IsActive__c, PhaseTemplateId__c
					FROM ActivityGroups__r
					WHERE IsActive__c = TRUE
				),
				(
					SELECT Id, Name, Description__c, Guidance__c, Sequence__c
					FROM Phases__r
					WHERE IsActive__c = TRUE
				)
			FROM EstimateTemplate__c
			WHERE Id = :estimateTemplateId
			WITH SECURITY_ENFORCED
		];

		return estimateTemplate;
	}

	public static Map<Id, Phase__c> createPhases(
		EstimateTemplate__c estimateTemplate,
		Id estimateId
	) {
		Map<Id, Phase__c> phasesByTemplateId = new Map<Id, Phase__c>();
		if (!estimateTemplate.UseProjectPhases__c) {
			return phasesByTemplateId;
		}

		for (PhaseTemplate__c phaseTemplate : estimateTemplate.Phases__r) {
			if (!phasesByTemplateId.containsKey(phaseTemplate.Id)) {
				Phase__c phase = Phase.newSO(phaseTemplate);
				phase.EstimateId__c = estimateId;
				phasesByTemplateId.put(phaseTemplate.Id, phase);
			}
		}

		CRUDUtility.insertRecords(phasesByTemplateId.values());

		return phasesByTemplateId;
	}

	public static Map<Id, ActivityGroup__c> createActivityGroups(
		List<ActivityGroupTemplate__c> activityGroupTemplates,
		Id estimateId,
		Map<Id, Phase__c> phasesByTemplateId
	) {
		Map<Id, ActivityGroup__c> activityGroupsByTemplateId = new Map<Id, ActivityGroup__c>();

		for (ActivityGroupTemplate__c activityGroupTemplate : activityGroupTemplates) {
			Id phaseId = null;
			if (phasesByTemplateId.containsKey(activityGroupTemplate.PhaseTemplateId__c)) {
				phaseId = phasesByTemplateId.get(activityGroupTemplate.PhaseTemplateId__c).Id;
			}

			if (!activityGroupsByTemplateId.containsKey(activityGroupTemplate.Id)) {
				ActivityGroup__c activityGroup = ActivityGroup.newSO(activityGroupTemplate);
				activityGroup.EstimateId__c = estimateId;
				activityGroup.PhaseId__c = phaseId;
				activityGroupsByTemplateId.put(activityGroupTemplate.Id, activityGroup);
			}
		}

		CRUDUtility.insertRecords(activityGroupsByTemplateId.values());

		return activityGroupsByTemplateId;
	}
}