quoting-CypressTK1/force-app/main/default/objects/LocationDiscount__c/LocationDiscount__c.object-meta.xml
<CustomObject>
    <description>Discounts based on Location for the quote.</description>
    <label>Location Discount</label>
    <nameField>
        <displayFormat>LD-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Location Discounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

quoting-CypressTK1/force-app/main/default/objects/LocationDiscount__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <label>Amount</label>
    <precision>18</precision>
    <scale>5</scale>
    <type>Number</type>
</CustomField>

quoting-CypressTK1/force-app/main/default/objects/LocationDiscount__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Countries</valueSetName>
    </valueSet>
</CustomField>

quoting-CypressTK1/force-app/main/default/objects/LocationDiscount__c/fields/QuoteId__c.field-meta.xml
<CustomField>
    <fullName>QuoteId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quote</label>
    <referenceTo>Quote__c</referenceTo>
    <relationshipLabel>Location Discounts</relationshipLabel>
    <relationshipName>LocationDiscounts</relationshipName>
    <type>Lookup</type>
</CustomField>

quoting-CypressTK1/force-app/main/default/objects/LocationDiscount__c/fields/RateMatch__c.field-meta.xml
<CustomField>
    <fullName>RateMatch__c</fullName>
    <formula>IF(NOT(ISBLANK(City__c)), &apos;City&apos;,
IF(NOT(ISBLANK(TEXT(State__c))), &apos;State&apos;,
IF(NOT(ISBLANK(TEXT(Country__c))), &apos;Country&apos;,
&apos;Global&apos;)))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Rate Match</label>
    <type>Text</type>
</CustomField>

quoting-CypressTK1/force-app/main/default/objects/LocationDiscount__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Discount Percent</fullName>
            </value>
            <value>
                <fullName>Discount Amount</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

quoting-CypressTK1/force-app/main/default/classes/LocationDiscountService.cls
/*
 * Provus Services Quoting
 * Copyright (c) 2022 Provus Inc. All rights reserved.
 */
public with sharing class LocationDiscountService {
	public static List<LocationDiscountDto> getLocationDiscounts(Id quoteId) {
		List<LocationDiscountDto> locationDiscountDtos = new List<LocationDiscountDto>();
		for (LocationDiscount__c locationDiscount : [
			SELECT Id, RateMatch__c, Country__c, State__c, City__c, Amount__c, QuoteId__c, Type__c
			FROM LocationDiscount__c
			WHERE QuoteId__c = :quoteId
			WITH SECURITY_ENFORCED
		]) {
			locationDiscountDtos.add(new LocationDiscountDto(locationDiscount));
		}

		return locationDiscountDtos;
	}

	public static void saveLocationDiscounts(List<LocationDiscountDto> locationDiscountDtos) {
		List<LocationDiscount__c> locationDiscountsToSave = new List<LocationDiscount__c>();
		List<LocationDiscount__c> locationDiscountsToDelete = new List<LocationDiscount__c>();

		for (LocationDiscountDto locationDiscountDto : locationDiscountDtos) {
			if (locationDiscountDto.isDelete()) {
				locationDiscountsToDelete.add((LocationDiscount__c) locationDiscountDto.refreshSo());
			} else {
				locationDiscountsToSave.add((LocationDiscount__c) locationDiscountDto.refreshSo());
			}
		}

		CRUDUtility.upsertRecords(locationDiscountsToSave);
		CRUDUtility.deleteRecords(locationDiscountsToDelete);
	}
}