quoting-CypressTK1/force-app/main/default/objects/LocationDiscount__c/LocationDiscount__c.object-meta.xml
<CustomObject>
    <description>Discounts based on Location for the quote.</description>
    <label>Location Discount</label>
    <nameField>
        <displayFormat>LD-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Location Discounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

quoting-CypressTK1/force-app/main/default/objects/LocationDiscount__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <label>Amount</label>
    <precision>18</precision>
    <scale>5</scale>
    <type>Number</type>
</CustomField>

quoting-CypressTK1/force-app/main/default/objects/LocationDiscount__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Countries</valueSetName>
    </valueSet>
</CustomField>

quoting-CypressTK1/force-app/main/default/objects/LocationDiscount__c/fields/QuoteId__c.field-meta.xml
<CustomField>
    <fullName>QuoteId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quote</label>
    <referenceTo>Quote__c</referenceTo>
    <relationshipLabel>Location Discounts</relationshipLabel>
    <relationshipName>LocationDiscounts</relationshipName>
    <type>Lookup</type>
</CustomField>

quoting-CypressTK1/force-app/main/default/objects/LocationDiscount__c/fields/RateMatch__c.field-meta.xml
<CustomField>
    <fullName>RateMatch__c</fullName>
    <formula>IF(NOT(ISBLANK(City__c)), &apos;City&apos;,
IF(NOT(ISBLANK(TEXT(State__c))), &apos;State&apos;,
IF(NOT(ISBLANK(TEXT(Country__c))), &apos;Country&apos;,
&apos;Global&apos;)))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Rate Match</label>
    <type>Text</type>
</CustomField>

quoting-CypressTK1/force-app/main/default/objects/LocationDiscount__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Discount Percent</fullName>
            </value>
            <value>
                <fullName>Discount Amount</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

quoting-CypressTK1/force-app/main/default/objects/LocationDiscountAdjustment__c/LocationDiscountAdjustment__c.object-meta.xml
<CustomObject>
    <label>Location Discount Adjustment</label>
    <nameField>
        <displayFormat>LDA-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Location Discount Adjustments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

quoting-CypressTK1/force-app/main/default/objects/LocationDiscountAdjustment__c/fields/AdjustmentId__c.field-meta.xml
<CustomField>
    <fullName>AdjustmentId__c</fullName>
    <label>Adjustment</label>
    <referenceTo>Adjustment__c</referenceTo>
    <relationshipLabel>Location Discount Adjustments</relationshipLabel>
    <relationshipName>LocationDiscountAdjustments</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

quoting-CypressTK1/force-app/main/default/objects/LocationDiscountAdjustment__c/fields/LocationDiscountId__c.field-meta.xml
<CustomField>
    <fullName>LocationDiscountId__c</fullName>
    <label>Location Discount</label>
    <referenceTo>LocationDiscount__c</referenceTo>
    <relationshipLabel>Location Discount Adjustments</relationshipLabel>
    <relationshipName>LocationDiscountAdjustments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

quoting-CypressTK1/force-app/main/default/classes/LocationDiscountReviewService.cls
/*
 * Provus Services Quoting
 * Copyright (c) 2022 Provus Inc. All rights reserved.
 */

public with sharing class LocationDiscountReviewService {
	public static List<LocationDiscountReviewDto> getLocationDiscountsReviewForQuote(Id quoteId) {
		List<LocationDiscount__c> locationDiscounts = getLocationDiscounts(quoteId);
		List<LocationDiscountReviewDto> reviewDtos = new List<LocationDiscountReviewDto>();
		for (LocationDiscount__c locationDiscount : locationDiscounts) {
			reviewDtos.add(new LocationDiscountReviewDto(locationDiscount));
		}
		return reviewDtos;
	}

	private static List<LocationDiscount__c> getLocationDiscounts(Id quoteId) {
		return [
			SELECT
				Id,
				Name,
				Country__c,
				State__c,
				City__c,
				RateMatch__c,
				Type__c,
				Amount__c,
				QuoteId__c,
				(
					SELECT
						Id,
						AdjustmentId__r.NamedRangeId__r.NamedRangeTotalId__r.BaseExtendedAmount__c,
						AdjustmentId__c
					FROM LocationDiscountAdjustments__r
				)
			FROM LocationDiscount__c
			WHERE QuoteId__c = :quoteId
			WITH SECURITY_ENFORCED
		];
	}

	private static List<LocationDiscountReviewDto> generateLocationReviewDtos() {
		List<LocationDiscountReviewDto> generatedDtos = new List<LocationDiscountReviewDto>();
		List<String> sampleCountries = new List<String>{
			'United States',
			'India',
			'Afghanistan',
			'Albania',
			'Algeria',
			'Barbados',
			'Belgium',
			'Bolivia'
		};
		List<String> sampleStates = new List<String>{
			'Andhra Pradesh',
			'Assam',
			'Chhattisgarh',
			'Gujarat',
			'Puducherry',
			'Delaware',
			'Florida',
			'Iowa'
		};
		List<String> sampleCities = new List<String>{
			'San Francisco',
			'Boise',
			'Los Angeles',
			'New York City',
			'Miami',
			'Paris',
			'London',
			'Moscow'
		};

		Integer numOfDtos = Integer.valueOf((Math.random() * 15) + 5); // Guarantees at least 5 DTOs, plus up to 15 more.
		String mockLocation;
		for (Integer i = 0; i < numOfDtos; i++) {
			LocationDiscountReviewDto newDto = new LocationDiscountReviewDto();
			// Each DTO will always have a country assigned (for rate match)
			newDto.location = sampleCountries.get(
				Integer.valueOf(Math.random() * (sampleCountries.size() - 1))
			);
			newDto.rateMatch = 'Country';
			// Randomly determine if we are adding a state
			if ((Math.random() * 2) >= 1) {
				newDto.location =
					newDto.location +
					'/' +
					sampleStates.get(Integer.valueOf(Math.random() * (sampleStates.size() - 1)));
				newDto.rateMatch = 'State';
				// Randomly determine if we are adding a city
				if ((Math.random() * 2) >= 1) {
					newDto.location =
						newDto.location +
						'/' +
						sampleCities.get(Integer.valueOf(Math.random() * (sampleCities.size() - 1)));
					newDto.rateMatch = 'City';
				}
			}
			Decimal locationAmt = Math.random() * 100.00;
			newDto.locationAmount = locationAmt.setScale(2, RoundingMode.CEILING);
			// Assign a discount amount anywhere from 0 to 100.
			Decimal discountAmt = Math.random() * 100.00;
			newDto.discountAmount = discountAmt.setScale(2, RoundingMode.CEILING);
			Decimal discountPercentage = Math.random() * 100.00;
			newDto.discountPercentage = discountPercentage.setScale(2, RoundingMode.CEILING);
			Decimal newAmt = Math.random() * 100.00;
			newDto.newAmount = newAmt;

			generatedDtos.add(newDto);
		}

		return generatedDtos;
	}
}