quoting-CypressTK1/force-app/main/default/objects/LocationDiscount__c/LocationDiscount__c.object-meta.xml
<CustomObject>
    <description>Discounts based on Location for the quote.</description>
    <label>Location Discount</label>
    <nameField>
        <displayFormat>LD-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Location Discounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

quoting-CypressTK1/force-app/main/default/objects/LocationDiscount__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <label>Amount</label>
    <precision>18</precision>
    <scale>5</scale>
    <type>Number</type>
</CustomField>

quoting-CypressTK1/force-app/main/default/objects/LocationDiscount__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Countries</valueSetName>
    </valueSet>
</CustomField>

quoting-CypressTK1/force-app/main/default/objects/LocationDiscount__c/fields/QuoteId__c.field-meta.xml
<CustomField>
    <fullName>QuoteId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quote</label>
    <referenceTo>Quote__c</referenceTo>
    <relationshipLabel>Location Discounts</relationshipLabel>
    <relationshipName>LocationDiscounts</relationshipName>
    <type>Lookup</type>
</CustomField>

quoting-CypressTK1/force-app/main/default/objects/LocationDiscount__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Discount Percent</fullName>
            </value>
            <value>
                <fullName>Discount Amount</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

quoting-CypressTK1/force-app/main/default/objects/LocationDiscountAdjustment__c/LocationDiscountAdjustment__c.object-meta.xml
<CustomObject>
    <label>Location Discount Adjustment</label>
    <nameField>
        <displayFormat>LDA-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Location Discount Adjustments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

quoting-CypressTK1/force-app/main/default/objects/LocationDiscountAdjustment__c/fields/AdjustmentId__c.field-meta.xml
<CustomField>
    <fullName>AdjustmentId__c</fullName>
    <label>Adjustment</label>
    <referenceTo>Adjustment__c</referenceTo>
    <relationshipLabel>Location Discount Adjustments</relationshipLabel>
    <relationshipName>LocationDiscountAdjustments</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

quoting-CypressTK1/force-app/main/default/objects/LocationDiscountAdjustment__c/fields/LocationDiscountId__c.field-meta.xml
<CustomField>
    <fullName>LocationDiscountId__c</fullName>
    <label>Location Discount</label>
    <referenceTo>LocationDiscount__c</referenceTo>
    <relationshipLabel>Location Discount Adjustments</relationshipLabel>
    <relationshipName>LocationDiscountAdjustments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

quoting-CypressTK1/force-app/main/default/objects/NamedRange__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>User Defined</fullName>
            </value>
            <value>
                <fullName>Quote</fullName>
            </value>
            <value>
                <fullName>Quote Labor</fullName>
            </value>
            <value>
                <fullName>Quote Labor (Non-billable)</fullName>
            </value>
            <value>
                <fullName>Quote Ancillaries (Non-billable)</fullName>
            </value>
            <value>
                <fullName>Quote Ancillaries</fullName>
            </value>
            <value>
                <fullName>Quote Item</fullName>
            </value>
            <value>
                <fullName>Quote Period</fullName>
            </value>
            <value>
                <fullName>Quote Period Group</fullName>
            </value>
            <value>
                <fullName>Quote Item Period Group</fullName>
            </value>
            <value>
                <fullName>Quote Section</fullName>
            </value>
            <value>
                <fullName>Project Phase</fullName>
            </value>
            <value>
                <fullName>Quote Item Project Phase</fullName>
            </value>
            <value>
                <fullName>Section Period</fullName>
            </value>
            <value>
                <fullName>Section Phase</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

quoting-CypressTK1/force-app/main/default/objects/NamedRangeTotal__c/fields/BaseExtendedAmount__c.field-meta.xml
<CustomField>
    <fullName>BaseExtendedAmount__c</fullName>
    <label>Base Extended Amount</label>
    <precision>18</precision>
    <scale>5</scale>
    <type>Currency</type>
</CustomField>

quoting-CypressTK1/force-app/main/default/classes/LocationDiscountReviewControllerTest.cls
@IsTest
public class LocationDiscountReviewControllerTest extends TestBase {
	@IsTest
	public static void verifyDiscountAmount() {
		Quote__c quoteSO = newQuote();
		LocationDiscount__c locationDiscountSO = new LocationDiscount__c(
			Country__c = 'India',
			State__c = 'Karnataka',
			City__c = 'Bangalore',
			Type__c = Adjustment.TYPE_DISCOUNT_PERCENT,
			Amount__c = 10,
			QuoteId__c = quoteSO.Id
		);
		CRUDUtility.insertRecords(locationDiscountSO);

		NamedRangeTotal__c namedRangeTotalSO = new NamedRangeTotal__c(
			QuoteId__c = quoteSO.Id,
			BaseExtendedAmount__c = 500
		);
		CRUDUtility.insertRecords(namedRangeTotalSO);

		NamedRange__c namedRangeSO = new NamedRange__c(
			NamedRangeTotalId__c = namedRangeTotalSO.Id,
			QuoteId__c = quoteSO.Id
		);
		CRUDUtility.insertRecords(namedRangeSO);

		Adjustment__c adjustmentSO = new Adjustment__c(NamedRangeId__c = namedRangeSO.Id);
		CRUDUtility.insertRecords(adjustmentSO);

		LocationDiscountAdjustment__c locationAdjustmentSO = new LocationDiscountAdjustment__c(
			LocationDiscountId__c = locationDiscountSO.Id,
			AdjustmentId__c = adjustmentSO.Id
		);
		CRUDUtility.insertRecords(locationAdjustmentSO);

		Test.startTest();

		List<LocationDiscountReviewDto> locationDiscounts = LocationDiscountReviewController.getLocationDiscountReviewForQuote(
			quoteSO.Id
		);
		System.assert(locationDiscounts.size() == 1, 'Should have location discount reviews');
		System.assert(
			locationDiscounts[0].discountAmount == 50,
			'Should have discount amount = 50 for 10%'
		);
		System.assert(
			locationDiscounts[0].newAmount == 450,
			'Should have new amount = 450 after 10% disount'
		);

		Test.stopTest();
	}

	@IsTest
	public static void verifyDiscountPercentage() {
		Quote__c quoteSO = newQuote();
		LocationDiscount__c locationDiscountSO = new LocationDiscount__c(
			Country__c = 'India',
			State__c = 'Karnataka',
			City__c = 'Bangalore',
			Type__c = Adjustment.TYPE_DISCOUNT_AMOUNT,
			Amount__c = 50,
			QuoteId__c = quoteSO.Id
		);
		CRUDUtility.insertRecords(locationDiscountSO);

		NamedRangeTotal__c namedRangeTotalSO = new NamedRangeTotal__c(
			QuoteId__c = quoteSO.Id,
			BaseExtendedAmount__c = 500
		);
		CRUDUtility.insertRecords(namedRangeTotalSO);

		NamedRange__c namedRangeSO = new NamedRange__c(
			NamedRangeTotalId__c = namedRangeTotalSO.Id,
			QuoteId__c = quoteSO.Id
		);
		CRUDUtility.insertRecords(namedRangeSO);

		Adjustment__c adjustmentSO = new Adjustment__c(NamedRangeId__c = namedRangeSO.Id);
		CRUDUtility.insertRecords(adjustmentSO);

		LocationDiscountAdjustment__c locationAdjustmentSO = new LocationDiscountAdjustment__c(
			LocationDiscountId__c = locationDiscountSO.Id,
			AdjustmentId__c = adjustmentSO.Id
		);
		CRUDUtility.insertRecords(locationAdjustmentSO);

		Test.startTest();

		List<LocationDiscountReviewDto> locationDiscounts = LocationDiscountReviewController.getLocationDiscountReviewForQuote(
			quoteSO.Id
		);
		System.assert(locationDiscounts.size() == 1, 'Should have location discount reviews');
		System.assert(locationDiscounts[0].discountAmount == 50, 'Should have discount amount = 50');
		System.assert(
			locationDiscounts[0].discountPercentage == 10,
			'Should have discount percentage = 10 for $50'
		);
		System.assert(
			locationDiscounts[0].newAmount == 450,
			'Should have new amount = 450 after $50 discount'
		);

		Test.stopTest();
	}

	@IsTest
	public static void verifyMultipleDiscountAmount() {
		Quote__c quoteSO = newQuote();
		LocationDiscount__c locationDiscountSO = new LocationDiscount__c(
			Country__c = 'India',
			State__c = 'Karnataka',
			City__c = 'Bangalore',
			Type__c = Adjustment.TYPE_DISCOUNT_PERCENT,
			Amount__c = 10,
			QuoteId__c = quoteSO.Id
		);
		CRUDUtility.insertRecords(locationDiscountSO);

		NamedRangeTotal__c namedRangeTotalSO = new NamedRangeTotal__c(
			QuoteId__c = quoteSO.Id,
			BaseExtendedAmount__c = 500
		);
		NamedRangeTotal__c namedRangeTotalSO2 = new NamedRangeTotal__c(
			QuoteId__c = quoteSO.Id,
			BaseExtendedAmount__c = 500
		);
		CRUDUtility.insertRecords(
			new List<NamedRangeTotal__c>{ namedRangeTotalSO, namedRangeTotalSO2 }
		);

		NamedRange__c namedRangeSO = new NamedRange__c(
			NamedRangeTotalId__c = namedRangeTotalSO.Id,
			QuoteId__c = quoteSO.Id
		);
		NamedRange__c namedRangeSO2 = new NamedRange__c(
			NamedRangeTotalId__c = namedRangeTotalSO2.Id,
			QuoteId__c = quoteSO.Id
		);
		CRUDUtility.insertRecords(new List<NamedRange__c>{ namedRangeSO, namedRangeSO2 });

		Adjustment__c adjustmentSO = new Adjustment__c(NamedRangeId__c = namedRangeSO.Id);
		Adjustment__c adjustmentSO2 = new Adjustment__c(NamedRangeId__c = namedRangeSO2.Id);
		CRUDUtility.insertRecords(new List<Adjustment__c>{ adjustmentSO, adjustmentSO2 });

		LocationDiscountAdjustment__c locationAdjustmentSO = new LocationDiscountAdjustment__c(
			LocationDiscountId__c = locationDiscountSO.Id,
			AdjustmentId__c = adjustmentSO.Id
		);
		LocationDiscountAdjustment__c locationAdjustmentSO2 = new LocationDiscountAdjustment__c(
			LocationDiscountId__c = locationDiscountSO.Id,
			AdjustmentId__c = adjustmentSO2.Id
		);
		CRUDUtility.insertRecords(
			new List<LocationDiscountAdjustment__c>{ locationAdjustmentSO, locationAdjustmentSO2 }
		);

		Test.startTest();

		List<LocationDiscountReviewDto> locationDiscounts = LocationDiscountReviewController.getLocationDiscountReviewForQuote(
			quoteSO.Id
		);
		System.assert(locationDiscounts.size() == 1, 'Should have location discount reviews');
		System.assert(
			locationDiscounts[0].discountAmount == 100,
			'Should have discount amount = 100 for 10%'
		);
		System.assert(
			locationDiscounts[0].newAmount == 900,
			'Should have new amount = 900 after 10% disount'
		);

		Test.stopTest();
	}
}