quoting-CypressTK1/force-app/main/default/objects/LocationDiscount__c/LocationDiscount__c.object-meta.xml
<CustomObject>
    <description>Discounts based on Location for the quote.</description>
    <label>Location Discount</label>
    <nameField>
        <displayFormat>LD-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Location Discounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

quoting-CypressTK1/force-app/main/default/objects/LocationDiscount__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <label>Amount</label>
    <precision>18</precision>
    <scale>5</scale>
    <type>Number</type>
</CustomField>

quoting-CypressTK1/force-app/main/default/objects/LocationDiscount__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Countries</valueSetName>
    </valueSet>
</CustomField>

quoting-CypressTK1/force-app/main/default/objects/LocationDiscount__c/fields/QuoteId__c.field-meta.xml
<CustomField>
    <fullName>QuoteId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quote</label>
    <referenceTo>Quote__c</referenceTo>
    <relationshipLabel>Location Discounts</relationshipLabel>
    <relationshipName>LocationDiscounts</relationshipName>
    <type>Lookup</type>
</CustomField>

quoting-CypressTK1/force-app/main/default/objects/LocationDiscount__c/fields/RateMatch__c.field-meta.xml
<CustomField>
    <fullName>RateMatch__c</fullName>
    <formula>IF(NOT(ISBLANK(City__c)), &apos;City&apos;,
IF(NOT(ISBLANK(TEXT(State__c))), &apos;State&apos;,
IF(NOT(ISBLANK(TEXT(Country__c))), &apos;Country&apos;,
&apos;Global&apos;)))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Rate Match</label>
    <type>Text</type>
</CustomField>

quoting-CypressTK1/force-app/main/default/objects/LocationDiscount__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Discount Percent</fullName>
            </value>
            <value>
                <fullName>Discount Amount</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

quoting-CypressTK1/force-app/main/default/classes/LocationDiscountDto.cls
/*
 * Provus Services Quoting
 * Copyright (c) 2022 Provus Inc. All rights reserved.
 */
public with sharing class LocationDiscountDto extends BaseDTO {
	@AuraEnabled
	public String id { get; set; }
	@AuraEnabled
	public String rateMatch { get; set; }
	@AuraEnabled
	public String country { get; set; }
	@AuraEnabled
	public String state { get; set; }
	@AuraEnabled
	public String city { get; set; }
	@AuraEnabled
	public Decimal amount { get; set; }
	@AuraEnabled
	public String quoteId { get; set; }
	@AuraEnabled
	public String type { get; set; }

	public LocationDiscountDto() {
	}

	public LocationDiscountDto(LocationDiscount__c discountRecord) {
		this.id = discountRecord.Id;
		this.rateMatch = discountRecord.RateMatch__c;
		this.country = discountRecord.Country__c;
		this.state = discountRecord.State__c;
		this.city = discountRecord.City__c;
		this.amount = discountRecord.Amount__c;
		this.quoteId = discountRecord.QuoteId__c;
		this.type = discountRecord.Type__c;
	}

	public override SObject refreshSo() {
		this.sObj = new LocationDiscount__c(
			Id = this.id,
			Country__c = this.country,
			State__c = this.state,
			City__c = this.city,
			Amount__c = this.amount,
			QuoteId__c = this.quoteId,
			Type__c = this.type
		);

		return this.sObj;
	}
}