quoting-CypressTK1/force-app/main/default/objects/Estimate__c/fields/ProductId__c.field-meta.xml
<CustomField>
    <fullName>ProductId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Product__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Product</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Product__c</referenceTo>
    <relationshipLabel>Estimates</relationshipLabel>
    <relationshipName>ProductEstimates</relationshipName>
    <type>Lookup</type>
</CustomField>

quoting-CypressTK1/force-app/main/default/objects/Estimate__c/fields/QuoteId__c.field-meta.xml
<CustomField>
    <fullName>QuoteId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quote</label>
    <referenceTo>Quote__c</referenceTo>
    <relationshipLabel>Estimate</relationshipLabel>
    <relationshipName>Estimate</relationshipName>
    <type>Lookup</type>
</CustomField>

quoting-CypressTK1/force-app/main/default/objects/EstimateTemplate__c/fields/ProductId__c.field-meta.xml
<CustomField>
    <fullName>ProductId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Product__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Product</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Product__c</referenceTo>
    <relationshipLabel>Estimate Templates</relationshipLabel>
    <relationshipName>ProductEstimateTemplates</relationshipName>
    <type>Lookup</type>
</CustomField>

quoting-CypressTK1/force-app/main/default/objects/Product__c/Product__c.object-meta.xml
<CustomObject>
	<description>Provus Product object</description>
	<label>Product</label>
	<nameField>
		<label>Product Name</label>
		<type>Text</type>
	</nameField>
	<pluralLabel>Products</pluralLabel>
	<sharingModel>ReadWrite</sharingModel>
</CustomObject>

quoting-CypressTK1/force-app/main/default/objects/Product__c/recordTypes/Product.recordType-meta.xml
<RecordType>
	<fullName>Product</fullName>
	<active>true</active>	
	<label>Product</label>
</RecordType>

quoting-CypressTK1/force-app/main/default/objects/Quote__c/fields/LaborUnits__c.field-meta.xml
<CustomField>
    <fullName>LaborUnits__c</fullName>
    <defaultValue>&apos;Headcount&apos;</defaultValue>
    <label>Labor Units</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Headcount</fullName>
            </value>
            <value>
                <fullName>Hours</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

quoting-CypressTK1/force-app/main/default/objects/Quote__c/fields/RateCardId__c.field-meta.xml
<CustomField>
    <fullName>RateCardId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Rate Card</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(6 OR 7) AND (3 OR 1) AND (4 OR 2) AND 5</booleanFilter>
        <errorMessage
		>The Rate Card is expired/inactive during the selected service start date</errorMessage>
        <filterItems>
            <field>$Source.ServiceStartDate__c</field>
            <operation>greaterOrEqual</operation>
            <valueField>RateCard__c.EffectiveDate__c</valueField>
        </filterItems>
        <filterItems>
            <field>$Source.ServiceStartDate__c</field>
            <operation>lessOrEqual</operation>
            <valueField>RateCard__c.ExpirationDate__c</valueField>
        </filterItems>
        <filterItems>
            <field>RateCard__c.EffectiveDate__c</field>
            <operation>equals</operation>
            <value />
        </filterItems>
        <filterItems>
            <field>RateCard__c.ExpirationDate__c</field>
            <operation>equals</operation>
            <value />
        </filterItems>
        <filterItems>
            <field>RateCard__c.IsActive__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>$Source.AccountId__c</field>
            <operation>equals</operation>
            <valueField>RateCard__c.AssignedToAccountId__c</valueField>
        </filterItems>
        <filterItems>
            <field>RateCard__c.AssignedToAccountId__c</field>
            <operation>equals</operation>
            <value />
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>RateCard__c</referenceTo>
    <relationshipLabel>Quotes</relationshipLabel>
    <relationshipName>Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

quoting-CypressTK1/force-app/main/default/objects/Quote__c/fields/TimePeriodsAlignment__c.field-meta.xml
<CustomField>
    <fullName>TimePeriodsAlignment__c</fullName>
    <label>Time Periods Alignment</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>User Defined Calendar</fullName>
            </value>            
            <value>
                <fullName>Weekday Calendar</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

quoting-CypressTK1/force-app/main/default/objects/QuoteItem__c/fields/ProductId__c.field-meta.xml
<CustomField>
    <fullName>ProductId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product__c</referenceTo>
    <relationshipLabel>Quote Items</relationshipLabel>
    <relationshipName>QuoteItems</relationshipName>
    <type>Lookup</type>
</CustomField>

quoting-CypressTK1/force-app/main/default/objects/TaskRoleSummary__c/fields/LevelAdjustment__c.field-meta.xml
<CustomField>
    <fullName>LevelAdjustment__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Level adjustment</label>
    <precision>18</precision>
    <scale>5</scale>
    <type>Number</type>
</CustomField>

quoting-CypressTK1/force-app/main/default/objects/TaskRoleSummary__c/fields/SummaryLevel__c.field-meta.xml
<CustomField>
    <fullName>SummaryLevel__c</fullName>
    <label>Summary Level</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Estimate</fullName>
            </value>
            <value>
                <fullName>Activity Group</fullName>
            </value>
            <value>
                <fullName>Activity</fullName>
            </value>
            <value>
                <fullName>Phase</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

quoting-CypressTK1/force-app/main/default/classes/CreateQuoteFromEstimateServiceTest.cls
/**
 *  Provus Services Quoting
 *  @2021 Provus Inc. All rights reserved.
 */
@IsTest
private class CreateQuoteFromEstimateServiceTest extends EstimateTestBase {
	@TestSetup
	static void setup() {
		List<Product__c> resourceRoles = createResourceRoles();
		RateCard__c rateCard = newRateCardWithItems(resourceRoles);
		EstimateTemplate__c estimateTemplate = EstimateTemplateTestBase.newEstimateTemplate();
		estimateTemplate.RateCardId__c = rateCard.Id;
		update estimateTemplate;
		List<ActivityGroupTemplate__c> activityGroupTemplates = EstimateTemplateTestBase.createActivityGroupTemplates(
			estimateTemplate.Id
		);
		List<ActivityTemplate__c> activityTemplates = EstimateTemplateTestBase.createActivityTemplates(
			activityGroupTemplates
		);

		EstimateTemplateTestBase.createTaskTemplates(activityTemplates, resourceRoles);
		CreateEstimateService.createEstimate(estimateTemplate.Id);

		createDataForSplitQuote(rateCard.Id, resourceRoles);
	}

	@IsTest
	static void itShouldSplitPeriodSpanValueWithRatio40x60WhenSplitOf40And60ExistForResource() {
		// test data creates two 50 hour tasks. To determine the period span we divide 50 / 8 which equal 6.25
		// we then split this by the corresponding resource split percentages
		SplitResourceTestInfo testInfo = getSplitResourceTestInfo();

		Test.startTest();

		CreateQuoteFromEstimateService.createSections(testInfo.quote);

		Test.stopTest();

		List<QuoteItemCell__c> quoteItemCellValues = getQuoteCellValues(testInfo.quote.Id);

		System.assertEquals(4, quoteItemCellValues.size(), 'should create 4 quote item cell records');

		// should be split 40% of 6.25 which equals 2.5
		QuoteItemCell__c quoteItemCell1 = quoteItemCellValues[0];
		System.assertEquals(1, quoteItemCell1.C001__c, 'item cell 1 value should equal one');
		System.assertEquals(1, quoteItemCell1.C002__c, 'item cell 2 value should equal one');
		System.assertEquals(0.5, quoteItemCell1.C003__c, 'item cell 3 value should equal 0.5');

		// should be split 60% of 6.25 which equals 3.75
		QuoteItemCell__c quoteItemCell2 = quoteItemCellValues[1];
		System.assertEquals(1, quoteItemCell2.C001__c, 'item cell 1 value should equal one');
		System.assertEquals(1, quoteItemCell2.C002__c, 'item cell 2 value should equal one');
		System.assertEquals(1, quoteItemCell2.C003__c, 'item cell 3 value should equal one');
		System.assertEquals(0.75, quoteItemCell2.C004__c, 'item cell 4 value should equal 0.75');
	}

	@IsTest
	static void itShouldSplitEvenlyPeriodSpanStartingAtCellPos4WhenCrossingQuoteSectionAndSplitOf50And50ExistForResource() {
		// test data creates two 50 hour tasks. To determine the period span we divide 50 / 8 which equal 6.25
		// we then split this by the corresponding resource split percentages
		SplitResourceTestInfo testInfo = getSplitResourceTestInfo();

		Test.startTest();

		CreateQuoteFromEstimateService.createSections(testInfo.quote);

		Test.stopTest();

		List<QuoteItemCell__c> quoteItemCellValues = getQuoteCellValues(testInfo.quote.Id);

		// should be split 50% of 6.25 which equals 3.125
		QuoteItemCell__c quoteItemCell3 = quoteItemCellValues[2];
		System.assertEquals(0.25, quoteItemCell3.C004__c, 'item cell 4 value should equal 0.25');
		System.assertEquals(1, quoteItemCell3.C005__c, 'item cell 5 value should equal one');
		System.assertEquals(1, quoteItemCell3.C006__c, 'item cell 6 value should equal one');
		System.assertEquals(0.875, quoteItemCell3.C007__c, 'item cell 7 value should equal 0.875');

		// should be split 50% of 6.25 which equals 3.125
		QuoteItemCell__c quoteItemCell4 = quoteItemCellValues[3];
		System.assertEquals(0.25, quoteItemCell4.C004__c, 'item cell 4 value should equal 0.25');
		System.assertEquals(1, quoteItemCell4.C005__c, 'item cell 5 value should equal one');
		System.assertEquals(1, quoteItemCell4.C006__c, 'item cell 6 value should equal one');
		System.assertEquals(0.875, quoteItemCell4.C007__c, 'item cell 7 value should equal 0.875');
	}

	@IsTest
	static void itShouldAssignQuoteItems() {
		Test.startTest();
		Quote__c quoteSO = createQuoteFromEstimate('Months');
		List<QuoteItem__c> quoteItems = [
			SELECT Id, ProductId__r.Name
			FROM QuoteItem__c
			WHERE QuoteId__c = :quoteSO.Id
			ORDER BY Sequence__c
		];
		System.assert(!quoteItems.isEmpty(), 'quote items should exist for quote');
		System.assert(
			quoteItems[0].ProductId__r.Name == 'Software Engineer' &&
			quoteItems[1].ProductId__r.Name == 'Project Manager',
			'quote item creation should follow task order'
		);
		Test.stopTest();
	}

	private static Quote__c createQuoteFromEstimate(String timePeriod) {
		Estimate__c estimateObj = [
			SELECT Id, RateCardId__c
			FROM Estimate__c
			WHERE Name = 'CLM Development Estimate'
		];
		QuoteDO quoteResult = CreateQuoteFromEstimateController.getEstimateDetails(estimateObj.Id);

		quoteResult.serviceStartDate = System.today();
		quoteResult.serviceEndDate = System.today().addYears(1);
		quoteResult.timePeriod = timePeriod;
		quoteResult.timePeriodsGroupMethod = TimePeriodYear.NAME;
		quoteResult.timePeriodsAlignment = 'User Defined Calendar';

		Quote__c quoteSO = QuoteDO.getQuoteFromData(quoteResult);
		quoteSO.QuoteDate__c = System.today();
		quoteSO.Version__c = 1;
		quoteSO.Type__c = QuoteService.RECORDTYPE_NAME_QUOTE;
		CRUDUtility.insertRecords(quoteSO);
		List<TaskRoleSummary__c> roleSummaries = new List<TaskRoleSummary__c>();
		for (TaskRoleSummary__c roleSummary : [
			SELECT Id
			FROM TaskRoleSummary__c
			WHERE SummaryLevel__c = 'Activity Group'
		]) {
			roleSummary.LevelAdjustment__c = 1;
			roleSummaries.add(roleSummary);
		}

		CRUDUtility.updateRecords(roleSummaries);
		CreateQuoteFromEstimateService.convertEntitiesFromEstimate(quoteSO);
		return quoteSO;
	}

	@IsTest
	static void itShouldReturn3ResourceRolesWhenOneTaskRoleSummaryHasZeroEstimateDuration() {
		SplitResourceTestInfo testInfo = getSplitResourceTestInfo();

		Test.startTest();

		Set<Id> resourceRoles = EstimateService.getOrderedResourceRoles(testInfo.quote.EstimateId__c);

		Test.stopTest();

		System.assertEquals(2, resourceRoles.size(), 'resource roles');
	}

	@IsTest
	static void itShouldSetQuoteItemCellsForMonths() {
		Test.startTest();
		Quote__c quoteSO = createQuoteFromEstimate('Months');
		List<QuoteItem__c> quoteItems = [
			SELECT Id, (SELECT C001__c FROM QuoteItemCells__r)
			FROM QuoteItem__c
			WHERE QuoteId__c = :quoteSO.Id
		];
		System.assert(
			quoteItems[0].QuoteItemCells__r[0].C001__c > 0,
			'quote item cell should be non-zero'
		);
		Test.stopTest();
	}

	@IsTest
	static void itShouldSetQuoteItemCellsForDays() {
		Test.startTest();
		Quote__c quoteSO = createQuoteFromEstimate('Days');
		List<QuoteItem__c> quoteItems = [
			SELECT Id, (SELECT C001__c FROM QuoteItemCells__r)
			FROM QuoteItem__c
			WHERE QuoteId__c = :quoteSO.Id
		];
		System.assert(
			quoteItems[0].QuoteItemCells__r[0].C001__c > 0,
			'quote item cell should be non-zero'
		);
		Test.stopTest();
	}

	@IsTest
	static void itShouldSetQuoteItemCellsForWeeks() {
		Test.startTest();
		Quote__c quoteSO = createQuoteFromEstimate('Weeks');
		List<QuoteItem__c> quoteItems = [
			SELECT Id, (SELECT C001__c FROM QuoteItemCells__r)
			FROM QuoteItem__c
			WHERE QuoteId__c = :quoteSO.Id
		];
		System.assert(
			quoteItems[0].QuoteItemCells__r[0].C001__c > 0,
			'quote item cell should be non-zero'
		);
		Test.stopTest();
	}

	static SplitResourceTestInfo getSplitResourceTestInfo() {
		SplitResourceTestInfo testInfo = new SplitResourceTestInfo();
		Id resourceRoleTypeId = SObjectUtility.getRecordTypeIdbyName(
			Schema.SObjectType.Product__c.getName(),
			'Resource Role'
		);

		testInfo.quote = [
			SELECT Id, EstimateId__c, TimePeriod__c, TimePeriodsAlignment__c, LaborUnits__c
			FROM Quote__c
			WHERE Name = :EstimateTestBase.TEST_SPLIT_QUOTE
			LIMIT 1
		];

		ResourceRolePreference resourceRolePref = new ResourceRolePreference();
		resourceRolePref.skillLevel = 'L1';
		resourceRolePref.location = 'United States/California';

		for (Product__c product : [
			SELECT Id
			FROM Product__c
			WHERE RecordTypeId = :resourceRoleTypeId
		]) {
			testInfo.rolePreferencesById.put(product.Id, resourceRolePref);
		}

		return testInfo;
	}

	class SplitResourceTestInfo {
		Quote__c quote;
		Map<Id, ResourceRolePreference> rolePreferencesById = new Map<Id, ResourceRolePreference>();
	}
}