quoting-CypressTK1/force-app/main/default/objects/Estimate__c/fields/ProductId__c.field-meta.xml
<CustomField>
    <fullName>ProductId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Product__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Product</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Product__c</referenceTo>
    <relationshipLabel>Estimates</relationshipLabel>
    <relationshipName>ProductEstimates</relationshipName>
    <type>Lookup</type>
</CustomField>

quoting-CypressTK1/force-app/main/default/objects/Estimate__c/fields/QuoteId__c.field-meta.xml
<CustomField>
    <fullName>QuoteId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quote</label>
    <referenceTo>Quote__c</referenceTo>
    <relationshipLabel>Estimate</relationshipLabel>
    <relationshipName>Estimate</relationshipName>
    <type>Lookup</type>
</CustomField>

quoting-CypressTK1/force-app/main/default/objects/Estimate__c/fields/ServiceId__c.field-meta.xml
<CustomField>
    <fullName>ServiceId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(1 AND 2) OR (3 AND 4)</booleanFilter>
        <filterItems>
            <field>$Source.ProductId__c</field>
            <operation>equals</operation>
            <valueField>Product__c.AssociatedProductId__c</valueField>
        </filterItems>
        <filterItems>
            <field>Product__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Service</value>
        </filterItems>
        <filterItems>
            <field>$Source.ProductId__c</field>
            <operation>equals</operation>
            <value />
        </filterItems>
        <filterItems>
            <field>Product__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Service</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Product__c</referenceTo>
    <relationshipLabel>Estimates</relationshipLabel>
    <relationshipName>ServiceEstimates</relationshipName>
    <type>Lookup</type>
</CustomField>

quoting-CypressTK1/force-app/main/default/objects/EstimateTemplate__c/fields/ProductId__c.field-meta.xml
<CustomField>
    <fullName>ProductId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Product__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Product</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Product__c</referenceTo>
    <relationshipLabel>Estimate Templates</relationshipLabel>
    <relationshipName>ProductEstimateTemplates</relationshipName>
    <type>Lookup</type>
</CustomField>

quoting-CypressTK1/force-app/main/default/objects/EstimateTemplate__c/fields/ServiceId__c.field-meta.xml
<CustomField>
    <fullName>ServiceId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(1 AND 2) OR (3 AND 4)</booleanFilter>
        <filterItems>
            <field>$Source.ProductId__c</field>
            <operation>equals</operation>
            <valueField>Product__c.AssociatedProductId__c</valueField>
        </filterItems>
        <filterItems>
            <field>Product__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Service</value>
        </filterItems>
        <filterItems>
            <field>$Source.ProductId__c</field>
            <operation>equals</operation>
            <value />
        </filterItems>
        <filterItems>
            <field>Product__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Service</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Product__c</referenceTo>
    <relationshipLabel>Estimate Templates</relationshipLabel>
    <relationshipName>ServiceEstimateTemplates</relationshipName>
    <type>Lookup</type>
</CustomField>

quoting-CypressTK1/force-app/main/default/objects/Product2/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <defaultValue>&apos;Product&apos;</defaultValue>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Add-On</fullName>
            </value>
            <value>
                <fullName>Product</fullName>
            </value>
            <value>
                <fullName>Resource Role</fullName>
            </value>
            <value>
                <fullName>Service</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

quoting-CypressTK1/force-app/main/default/objects/Product2/recordTypes/Product.recordType-meta.xml
<RecordType>
    <fullName>Product</fullName>
    <active>false</active>
    <label>Product</label>
</RecordType>

quoting-CypressTK1/force-app/main/default/objects/Product2/recordTypes/Service.recordType-meta.xml
<RecordType>
    <fullName>Service</fullName>
    <active>false</active>
    <label>Service</label>
</RecordType>

quoting-CypressTK1/force-app/main/default/objects/Product__c/Product__c.object-meta.xml
<CustomObject>
	<description>Provus Product object</description>
	<label>Product</label>
	<nameField>
		<label>Product Name</label>
		<type>Text</type>
	</nameField>
	<pluralLabel>Products</pluralLabel>
	<sharingModel>ReadWrite</sharingModel>
</CustomObject>

quoting-CypressTK1/force-app/main/default/objects/Product__c/fields/AssociatedProductId__c.field-meta.xml
<CustomField>
	<fullName>AssociatedProductId__c</fullName>
	<deleteConstraint>SetNull</deleteConstraint>
	<description>Association between Product and Service record types</description>
	<label>Associated Product</label>
	<referenceTo>Product__c</referenceTo>
	<relationshipLabel>Associated Products</relationshipLabel>
	<relationshipName>AssociatedProducts</relationshipName>
	<type>Lookup</type>
</CustomField>

quoting-CypressTK1/force-app/main/default/objects/Product__c/fields/StandardProductId__c.field-meta.xml
<CustomField>
    <fullName>StandardProductId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Provus Products</relationshipLabel>
    <relationshipName>ProvusProducts</relationshipName>
    <type>Lookup</type>
</CustomField>

quoting-CypressTK1/force-app/main/default/objects/Product__c/recordTypes/Product.recordType-meta.xml
<RecordType>
	<fullName>Product</fullName>
	<active>true</active>	
	<label>Product</label>
</RecordType>

quoting-CypressTK1/force-app/main/default/objects/Product__c/recordTypes/Service.recordType-meta.xml
<RecordType>
	<fullName>Service</fullName>
	<active>true</active>	
	<label>Service</label>
</RecordType>

quoting-CypressTK1/force-app/main/default/objects/Quote__c/fields/RateCardId__c.field-meta.xml
<CustomField>
    <fullName>RateCardId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Rate Card</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(6 OR 7) AND (3 OR 1) AND (4 OR 2) AND 5</booleanFilter>
        <errorMessage
		>The Rate Card is expired/inactive during the selected service start date</errorMessage>
        <filterItems>
            <field>$Source.ServiceStartDate__c</field>
            <operation>greaterOrEqual</operation>
            <valueField>RateCard__c.EffectiveDate__c</valueField>
        </filterItems>
        <filterItems>
            <field>$Source.ServiceStartDate__c</field>
            <operation>lessOrEqual</operation>
            <valueField>RateCard__c.ExpirationDate__c</valueField>
        </filterItems>
        <filterItems>
            <field>RateCard__c.EffectiveDate__c</field>
            <operation>equals</operation>
            <value />
        </filterItems>
        <filterItems>
            <field>RateCard__c.ExpirationDate__c</field>
            <operation>equals</operation>
            <value />
        </filterItems>
        <filterItems>
            <field>RateCard__c.IsActive__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>$Source.AccountId__c</field>
            <operation>equals</operation>
            <valueField>RateCard__c.AssignedToAccountId__c</valueField>
        </filterItems>
        <filterItems>
            <field>RateCard__c.AssignedToAccountId__c</field>
            <operation>equals</operation>
            <value />
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>RateCard__c</referenceTo>
    <relationshipLabel>Quotes</relationshipLabel>
    <relationshipName>Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

quoting-CypressTK1/force-app/main/default/objects/Quote__c/fields/ServiceId__c.field-meta.xml
<CustomField>
    <fullName>ServiceId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service</label>
    <referenceTo>Product__c</referenceTo>
    <relationshipLabel>Quotes</relationshipLabel>
    <relationshipName>ServiceQuotes</relationshipName>
    <type>Lookup</type>
</CustomField>

quoting-CypressTK1/force-app/main/default/objects/QuoteItem__c/fields/ProductId__c.field-meta.xml
<CustomField>
    <fullName>ProductId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product__c</referenceTo>
    <relationshipLabel>Quote Items</relationshipLabel>
    <relationshipName>QuoteItems</relationshipName>
    <type>Lookup</type>
</CustomField>

quoting-CypressTK1/force-app/main/default/classes/ServiceRecommendationsTestsBase.cls
/**
 *  Provus Services Quoting
 *  ServiceRecommendationsTestsBase
 *  @2021 Provus Inc. All rights reserved.
 */
public with sharing abstract class ServiceRecommendationsTestsBase extends EstimateTestBase {
	public static void setupData() {
		// price book
		Pricebook2 pricebook = newPriceBook();
		// opportunity
		Opportunity opp = newOpportunity(pricebook);
		// setup products
		Product2 product = newProduct2('Main Product', 'Product');
		CRUDUtility.insertRecords(product);
		Product2 service = newProduct2('Service Product', 'Service');
		service.AssociatedProductId__c = product.Id;
		CRUDUtility.insertRecords(service);

		Id productTypeId = SObjectUtility.getRecordTypeIdbyName(
			Schema.SObjectType.Product__c.getName(),
			'Product'
		);
		Id serviceTypeId = SObjectUtility.getRecordTypeIdbyName(
			Schema.SObjectType.Product__c.getName(),
			'Service'
		);
		Product__c cproduct = newProduct('Main Product', productTypeId);
		cproduct.StandardProductId__c = product.Id;
		CRUDUtility.insertRecords(cproduct);
		Product__c cservice = newProduct('Service Product', serviceTypeId);
		cservice.StandardProductId__c = service.Id;
		cservice.AssociatedProductId__c = cproduct.Id;
		CRUDUtility.insertRecords(cservice);

		// pricebook entries
		Id standardPricebookId = Test.getStandardPricebookId();
		List<PricebookEntry> pricebookEntries = new List<PricebookEntry>{
			newPricebookEntry(standardPricebookId, product.Id),
			newPricebookEntry(standardPricebookId, service.Id),
			newPricebookEntry(pricebook.Id, product.Id),
			newPricebookEntry(pricebook.Id, service.Id)
		};
		CRUDUtility.insertRecords(pricebookEntries);
		// resource roles
		List<Product__c> resourceRoles = createResourceRoles();
		// rate card
		RateCard__c rateCard = newRateCardWithItems(resourceRoles);
		// estimates
		EstimateTemplate__c estimateTemplate = EstimateTemplateTestBase.newEstimateTemplate();
		estimateTemplate.RateCardId__c = rateCard.Id;
		CRUDUtility.updateRecords(estimateTemplate);
		List<ActivityGroupTemplate__c> activityGroupTemplates = EstimateTemplateTestBase.createActivityGroupTemplates(
			estimateTemplate.Id
		);
		List<ActivityTemplate__c> activityTemplates = EstimateTemplateTestBase.createActivityTemplates(
			activityGroupTemplates
		);
		EstimateTemplateTestBase.createTaskTemplates(activityTemplates, resourceRoles);
		Estimate__c estimateSO = CreateEstimateService.createEstimate(estimateTemplate.Id);
		estimateSO.Default__c = true;
		estimateSO.ProductId__c = cproduct.Id;
		estimateSO.ServiceId__c = cservice.Id;
		CRUDUtility.updateRecords(estimateSO);

		// quote
		Quote__c quote = newQuote();
		quote.Name = 'Test Quote';
		quote.EstimateId__c = estimateSO.Id;
		quote.OpportunityId__c = opp.Id;
		quote.Type__c = 'Quote';
		quote.ServiceId__c = cservice.Id;
		CRUDUtility.updateRecords(quote);
		// quote item
		QuoteItem__c quoteItemSO = new QuoteItem__c();
		quoteItemSO.QuoteId__c = quote.Id;
		quoteItemSO.ProductId__c = cservice.Id;
		CRUDUtility.insertRecords(quoteItemSO);
	}

	public static OpportunityLineItem createProductOpportunityLineItem() {
		Opportunity opp = [
			SELECT Id, Name, Pricebook2Id
			FROM Opportunity
			WHERE Name = 'Test'
			WITH SECURITY_ENFORCED
			LIMIT 1
		];
		List<OpportunityLineItem> oppLineItems = [
			SELECT Id
			FROM OpportunityLineItem
			WHERE OpportunityId = :opp.Id
			WITH SECURITY_ENFORCED
		];
		CRUDUtility.deleteRecords(oppLineItems);
		Product2 product = [
			SELECT Id, Name
			FROM Product2
			WHERE Name = 'Main Product'
			WITH SECURITY_ENFORCED
			LIMIT 1
		];
		OpportunityLineItem oppLineItem = new OpportunityLineItem();
		PricebookEntry pricebookEntry = [
			SELECT Id
			FROM PricebookEntry
			WHERE Product2Id = :product.Id AND Pricebook2Id = :opp.Pricebook2Id
			WITH SECURITY_ENFORCED
			LIMIT 1
		];
		ServiceRecommendationsDto.OpportunityLineItemRequest oppLineItemRequest = new ServiceRecommendationsDto.OpportunityLineItemRequest();
		oppLineItemRequest.opportunityLineItems.add(oppLineItem);
		oppLineItemRequest.opportunityId = opp.Id;
		oppLineItemRequest.productId = product.Id;
		oppLineItemRequest.pricebookEntryId = pricebookEntry.Id;
		NamedRange.NamedRangeDO quoteTotalNamedRange = new NamedRange.NamedRangeDO();
		quoteTotalNamedRange.relatedTotal = new NamedRangeTotal.NamedRangeTotalDO();
		quoteTotalNamedRange.relatedTotal.netExtendedAmount = 1000;
		oppLineItemRequest.quoteTotalNamedRange = quoteTotalNamedRange;
		List<OpportunityLineItem> opportunityLineItems = ServiceRecommendationsSupport.upsertOpportunityLineItem(
			oppLineItemRequest
		);
		return opportunityLineItems[0];
	}

	public static OpportunityLineItem createOpportunityLineItem() {
		Opportunity opp = [
			SELECT Id, Name, Pricebook2Id
			FROM Opportunity
			WHERE Name = 'Test'
			WITH SECURITY_ENFORCED
			LIMIT 1
		];
		Product2 product = [
			SELECT Id, Name
			FROM Product2
			WHERE Name = 'Service Product'
			WITH SECURITY_ENFORCED
			LIMIT 1
		];
		PricebookEntry pricebookEntry = [
			SELECT Id
			FROM PricebookEntry
			WHERE Product2Id = :product.Id AND Pricebook2Id = :opp.Pricebook2Id
			WITH SECURITY_ENFORCED
			LIMIT 1
		];
		OpportunityLineItem serviceOpportunityLineItem = newOpportunityLineItem(
			opp.Id,
			product.Id,
			pricebookEntry.Id
		);
		CRUDUtility.insertRecords(serviceOpportunityLineItem);
		return serviceOpportunityLineItem;
	}
}