quoting-CypressTK1/force-app/main/default/objects/Estimate__c/fields/ProductId__c.field-meta.xml
<CustomField>
    <fullName>ProductId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Product__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Product</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Product__c</referenceTo>
    <relationshipLabel>Estimates</relationshipLabel>
    <relationshipName>ProductEstimates</relationshipName>
    <type>Lookup</type>
</CustomField>

quoting-CypressTK1/force-app/main/default/objects/Estimate__c/fields/QuoteId__c.field-meta.xml
<CustomField>
    <fullName>QuoteId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quote</label>
    <referenceTo>Quote__c</referenceTo>
    <relationshipLabel>Estimate</relationshipLabel>
    <relationshipName>Estimate</relationshipName>
    <type>Lookup</type>
</CustomField>

quoting-CypressTK1/force-app/main/default/objects/Product__c/Product__c.object-meta.xml
<CustomObject>
	<description>Provus Product object</description>
	<label>Product</label>
	<nameField>
		<label>Product Name</label>
		<type>Text</type>
	</nameField>
	<pluralLabel>Products</pluralLabel>
	<sharingModel>ReadWrite</sharingModel>
</CustomObject>

quoting-CypressTK1/force-app/main/default/objects/Product__c/fields/Description__c.field-meta.xml
<CustomField>
	<fullName>Description__c</fullName>
	<label>Product Description</label>
	<type>TextArea</type>
</CustomField>

quoting-CypressTK1/force-app/main/default/objects/Product__c/fields/IsActive__c.field-meta.xml
<CustomField>
	<fullName>IsActive__c</fullName>
	<defaultValue>true</defaultValue>
	<description>Product Active</description>
	<label>Active</label>
	<type>Checkbox</type>
</CustomField>

quoting-CypressTK1/force-app/main/default/objects/Quote__c/fields/RateCardId__c.field-meta.xml
<CustomField>
    <fullName>RateCardId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Rate Card</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(6 OR 7) AND (3 OR 1) AND (4 OR 2) AND 5</booleanFilter>
        <errorMessage
		>The Rate Card is expired/inactive during the selected service start date</errorMessage>
        <filterItems>
            <field>$Source.ServiceStartDate__c</field>
            <operation>greaterOrEqual</operation>
            <valueField>RateCard__c.EffectiveDate__c</valueField>
        </filterItems>
        <filterItems>
            <field>$Source.ServiceStartDate__c</field>
            <operation>lessOrEqual</operation>
            <valueField>RateCard__c.ExpirationDate__c</valueField>
        </filterItems>
        <filterItems>
            <field>RateCard__c.EffectiveDate__c</field>
            <operation>equals</operation>
            <value />
        </filterItems>
        <filterItems>
            <field>RateCard__c.ExpirationDate__c</field>
            <operation>equals</operation>
            <value />
        </filterItems>
        <filterItems>
            <field>RateCard__c.IsActive__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>$Source.AccountId__c</field>
            <operation>equals</operation>
            <valueField>RateCard__c.AssignedToAccountId__c</valueField>
        </filterItems>
        <filterItems>
            <field>RateCard__c.AssignedToAccountId__c</field>
            <operation>equals</operation>
            <value />
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>RateCard__c</referenceTo>
    <relationshipLabel>Quotes</relationshipLabel>
    <relationshipName>Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

quoting-CypressTK1/force-app/main/default/objects/QuoteItem__c/fields/ProductId__c.field-meta.xml
<CustomField>
    <fullName>ProductId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product__c</referenceTo>
    <relationshipLabel>Quote Items</relationshipLabel>
    <relationshipName>QuoteItems</relationshipName>
    <type>Lookup</type>
</CustomField>

quoting-CypressTK1/force-app/main/default/objects/QuoteSection__c/fields/ActivityGroupId__c.field-meta.xml
<CustomField>
    <fullName>ActivityGroupId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Activity Group</label>
    <referenceTo>ActivityGroup__c</referenceTo>
    <relationshipName>QuoteSections</relationshipName>
    <type>Lookup</type>
</CustomField>

quoting-CypressTK1/force-app/main/default/objects/RateCardItem__c/fields/ProductId__c.field-meta.xml
<CustomField>
    <fullName>ProductId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product__c</referenceTo>
    <relationshipLabel>Rate Card Items</relationshipLabel>
    <relationshipName>RateCardItems</relationshipName>
    <type>Lookup</type>
</CustomField>

quoting-CypressTK1/force-app/main/default/objects/ResourceSplit__c/ResourceSplit__c.object-meta.xml
<CustomObject>
    <label>Resource Split</label>
    <nameField>
        <label>Resource Split Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Resource Splits</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

quoting-CypressTK1/force-app/main/default/objects/ResourceSplit__c/fields/SplitPercentage__c.field-meta.xml
<CustomField>
    <fullName>SplitPercentage__c</fullName>
    <label>Split Percentage</label>
    <precision>18</precision>
    <scale>15</scale>
    <type>Percent</type>
</CustomField>

quoting-CypressTK1/force-app/main/default/objects/ResourceSplit__c/fields/TaskRoleSummaryId__c.field-meta.xml
<CustomField>
    <fullName>TaskRoleSummaryId__c</fullName>
    <label>Task Role Summary</label>
    <referenceTo>TaskRoleSummary__c</referenceTo>
    <relationshipLabel>Resource Splits</relationshipLabel>
    <relationshipName>ResourceSplits</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

quoting-CypressTK1/force-app/main/default/objects/ResourceSplit__c/fields/TotalEstimatedDuration__c.field-meta.xml
<CustomField>
    <fullName>TotalEstimatedDuration__c</fullName>
    <formula>TaskRoleSummaryId__r.TotalEstimatedDuration__c  *  SplitPercentage__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total Estimated Duration</label>
    <precision>18</precision>
    <scale>5</scale>
    <type>Number</type>
</CustomField>

quoting-CypressTK1/force-app/main/default/objects/Task__c/fields/ResourceRoleId__c.field-meta.xml
<CustomField>
    <fullName>ResourceRoleId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Resource Role</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Product__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Resource Role</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Product__c</referenceTo>
    <relationshipLabel>Tasks</relationshipLabel>
    <relationshipName>Tasks</relationshipName>
    <type>Lookup</type>
</CustomField>

quoting-CypressTK1/force-app/main/default/objects/TaskRoleSummary__c/fields/EstimatedDuration__c.field-meta.xml
<CustomField>
    <fullName>EstimatedDuration__c</fullName>
    <label>Estimated duration</label>
    <summarizedField>Task__c.EstimatedDuration__c</summarizedField>
    <summaryForeignKey>Task__c.RoleSummaryId__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

quoting-CypressTK1/force-app/main/default/objects/TaskRoleSummary__c/fields/ResourceRoleId__c.field-meta.xml
<CustomField>
    <fullName>ResourceRoleId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Resource Role</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Product__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Resource Role</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Product__c</referenceTo>
    <relationshipName>LevelSummaries</relationshipName>
    <type>Lookup</type>
</CustomField>

quoting-CypressTK1/force-app/main/default/objects/TaskRoleSummary__c/fields/SummaryLevel__c.field-meta.xml
<CustomField>
    <fullName>SummaryLevel__c</fullName>
    <label>Summary Level</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Estimate</fullName>
            </value>
            <value>
                <fullName>Activity Group</fullName>
            </value>
            <value>
                <fullName>Activity</fullName>
            </value>
            <value>
                <fullName>Phase</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

quoting-CypressTK1/force-app/main/default/objects/TaskRoleSummary__c/fields/TotalEstimatedDuration__c.field-meta.xml
<CustomField>
    <fullName>TotalEstimatedDuration__c</fullName>
    <formula>TotalCalculatedDuration__c + TotalAdjustments__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total estimated duration</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

quoting-CypressTK1/force-app/main/default/objects/TaskSummary__c/TaskSummary__c.object-meta.xml
<CustomObject>
    <label>Task Summary</label>
    <nameField>
        <displayFormat>TS-{00000}</displayFormat>
        <label>Task Summary</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Task Summaries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

quoting-CypressTK1/force-app/main/default/classes/EstimateTestBase.cls
/**
 *  Provus Services Quoting
 *  EstimatorTestsBase
 *  @2021 Provus Inc. All rights reserved.
 */
public with sharing abstract class EstimateTestBase extends TestBase {
	public static final String GUIDANCE = 'sample guidance for test';
	public static final String DESCRIPTION = 'sample description for test';
	static final String TEST_ESTIMATE_W_RESOURCE_SPLIT_NAME = 'Test Estimate With Resource Splits';
	public static final String TEST_SPLIT_QUOTE = 'Split Quote';
	static final String SUMMARYLEVEL_ACTIVITYGROUP = EstimatorConstants.ACTIVITY_GROUP;

	public static ActivityGroup__c createNewActivityGroup(Id estimateId) {
		ActivityGroup__c groupSo = new ActivityGroup__c(EstimateId__c = estimateId);
		CRUDUtility.insertRecords(groupSo);
		return groupSo;
	}

	public static List<Product__c> createResourceRoles() {
		Id resourceRoleTypeId = SObjectUtility.getRecordTypeIdbyName(
			Schema.SObjectType.Product__c.getName(),
			'Resource Role'
		);

		List<Product__c> resourceRoles = new List<Product__c>();
		resourceRoles.add(newProduct('Software Engineer', resourceRoleTypeId));
		resourceRoles.add(newProduct('Project Manager', resourceRoleTypeId));
		resourceRoles.add(newProduct('Configuration Engineer', resourceRoleTypeId));

		CRUDUtility.insertRecords(resourceRoles);
		return resourceRoles;
	}

	public static RateCardItem__c newRateCardItem(
		Map<String, Object> rateCardItemValues,
		Id productId
	) {
		RateCardItem__c rateCardItem = new RateCardItem__c(
			IsActive__c = true,
			ProductId__c = productId
		);
		for (String field : rateCardItemValues.keySet()) {
			rateCardItem.put(field, rateCardItemValues.get(field));
		}

		return rateCardItem;
	}

	public static RateCard__c newRateCardWithItems(List<Product__c> resourceRoles) {
		RateCard__c rateCard = newRateCard();
		Map<String, Object> rateCardItemValues = new Map<String, Object>();
		rateCardItemValues.put('RateCardId__c', (String) rateCard.Id);
		//rateCardItemValues.add('ProductId__c', role.Id);
		rateCardItemValues.put('LocationCountry__c', 'United States');
		rateCardItemValues.put('SkillLevel__c', 'L1');
		rateCardItemValues.put('LocationDisplayName__c', 'United States/California');

		List<RateCardItem__c> rateCardItems = new List<RateCardItem__c>();
		for (Product__c role : resourceRoles) {
			rateCardItems.add(newRateCardItem(rateCardItemValues, role.Id));
		}

		rateCardItemValues.put('SkillLevel__c', 'L2');
		for (Product__c role : resourceRoles) {
			rateCardItems.add(newRateCardItem(rateCardItemValues, role.Id));
		}

		if (!rateCardItems.isEmpty()) {
			CRUDUtility.insertRecords(rateCardItems);
		}

		return rateCard;
	}

	/**
	 * @param rateCardID rate card ID
	 * @param resourceRoles resource role Product__c records for estimate setup
	 */
	public static void createDataForSplitQuote(Id rateCardID, List<Product__c> resourceRoles) {
		Estimate__c testEstimateWithResourceSplits = new Estimate__c(
			Name = TEST_ESTIMATE_W_RESOURCE_SPLIT_NAME,
			IsActive__c = true,
			RateCardId__c = rateCardID,
			Guidance__c = 'sample guidance for test',
			Description__c = 'sample description for test'
		);
		CRUDUtility.insertRecords(testEstimateWithResourceSplits);

		List<ActivityGroup__c> activityGroups = new List<ActivityGroup__c>();
		ActivityGroup__c activityGroupInitiation = new ActivityGroup__c(
			EstimateId__c = testEstimateWithResourceSplits.Id,
			Name = 'Initiation',
			Sequence__c = 1,
			IsActive__c = true,
			Guidance__c = 'initiation activity group guidance',
			Description__c = 'initiation activity group description'
		);
		activityGroups.add(activityGroupInitiation);
		ActivityGroup__c activityGroupDesign = new ActivityGroup__c(
			EstimateId__c = testEstimateWithResourceSplits.Id,
			Name = 'Design',
			Sequence__c = 2,
			IsActive__c = true,
			Guidance__c = 'design activity group guidance',
			Description__c = 'design activity group description'
		);
		activityGroups.add(activityGroupDesign);
		CRUDUtility.insertRecords(activityGroups);

		List<TaskSummary__c> taskSummaries = new List<TaskSummary__c>();
		TaskSummary__c taskSumm1 = new TaskSummary__c();
		taskSummaries.add(taskSumm1);

		CRUDUtility.insertRecords(taskSummaries);

		List<TaskRoleSummary__c> taskRoleSummaries = new List<TaskRoleSummary__c>();
		TaskRoleSummary__c taskRoleSummary1 = createTaskRoleSummaryForActivityGroup(
			testEstimateWithResourceSplits.Id
		);
		taskRoleSummary1.ResourceRoleId__c = resourceRoles[0].Id;
		taskRoleSummary1.ActivityGroupId__c = activityGroups[0].Id;
		taskRoleSummary1.SummaryId__c = taskSumm1.Id;
		taskRoleSummaries.add(taskRoleSummary1);

		TaskRoleSummary__c taskRoleSummary2 = createTaskRoleSummaryForActivityGroup(
			testEstimateWithResourceSplits.Id
		);
		taskRoleSummary2.ResourceRoleId__c = resourceRoles[1].Id;
		taskRoleSummary2.ActivityGroupId__c = activityGroups[1].Id;
		taskRoleSummary2.SummaryId__c = taskSumm1.Id;
		taskRoleSummaries.add(taskRoleSummary2);

		TaskRoleSummary__c taskRoleSummary3 = createTaskRoleSummaryForActivityGroup(
			testEstimateWithResourceSplits.Id
		);
		taskRoleSummary3.ResourceRoleId__c = resourceRoles[2].Id;
		taskRoleSummary3.ActivityGroupId__c = activityGroups[0].Id;
		taskRoleSummary3.SummaryId__c = taskSumm1.Id;
		taskRoleSummaries.add(taskRoleSummary3);

		CRUDUtility.insertRecords(taskRoleSummaries);

		List<Task__c> tasks = new List<Task__c>();
		Task__c task1 = new Task__c();
		task1.EstimateId__c = testEstimateWithResourceSplits.Id;
		task1.ActivityGroupId__c = activityGroupInitiation.Id;
		task1.CalculatedDuration__c = 50;
		task1.EstimatedDuration__c = 50;
		task1.RoleSummaryId__c = taskRoleSummary1.Id;
		tasks.add(task1);

		Task__c task2 = new Task__c();
		task2.EstimateId__c = testEstimateWithResourceSplits.Id;
		task2.ActivityGroupId__c = activityGroupDesign.Id;
		task2.CalculatedDuration__c = 50;
		task2.EstimatedDuration__c = 50;
		task2.RoleSummaryId__c = taskRoleSummary2.Id;
		tasks.add(task2);

		Task__c task3 = new Task__c();
		task3.EstimateId__c = testEstimateWithResourceSplits.Id;
		task3.ActivityGroupId__c = activityGroupDesign.Id;
		task3.CalculatedDuration__c = 0;
		task3.EstimatedDuration__c = 0;
		task3.RoleSummaryId__c = taskRoleSummary3.Id;
		tasks.add(task3);

		CRUDUtility.insertRecords(tasks);

		taskRoleSummaries = [
			SELECT TotalEstimatedDuration__c
			FROM TaskRoleSummary__c
			WHERE EstimateId__c = :testEstimateWithResourceSplits.Id
			WITH SECURITY_ENFORCED
		];

		List<ResourceSplit__c> resourceSplits = new List<ResourceSplit__c>();
		ResourceSplit__c resourceSplit1 = new ResourceSplit__c(
			SplitPercentage__c = 40,
			Sequence__c = 1,
			TaskRoleSummaryId__c = taskRoleSummary1.Id
		);
		resourceSplits.add(resourceSplit1);
		ResourceSplit__c resourceSplit2 = new ResourceSplit__c(
			SplitPercentage__c = 60,
			Sequence__c = 2,
			TaskRoleSummaryId__c = taskRoleSummary1.Id
		);
		resourceSplits.add(resourceSplit2);
		ResourceSplit__c resourceSplit3 = new ResourceSplit__c(
			SplitPercentage__c = 50,
			Sequence__c = 1,
			TaskRoleSummaryId__c = taskRoleSummary2.Id
		);
		resourceSplits.add(resourceSplit3);
		ResourceSplit__c resourceSplit4 = new ResourceSplit__c(
			SplitPercentage__c = 50,
			Sequence__c = 2,
			TaskRoleSummaryId__c = taskRoleSummary2.Id
		);
		resourceSplits.add(resourceSplit4);
		CRUDUtility.insertRecords(resourceSplits);

		Quote__c splitQuote = newQuote(TEST_SPLIT_QUOTE);
		splitQuote.TimePeriod__c = 'Days';
		splitQuote.ServiceStartDate__c = Date.newInstance(2022, 1, 1);
		splitQuote.ServiceEndDate__c = DurationCalcs.endDate(
			100,
			splitQuote.Id,
			splitQuote.ServiceStartDate__c
		);
		splitQuote.EstimateId__c = testEstimateWithResourceSplits.Id;
		CRUDUtility.updateRecords(splitQuote);

		// create section
		QuoteSection__c section = new QuoteSection__c();
		section.Name = 'Quote Section';
		section.Sequence__c = 1;
		section.QuoteId__c = splitQuote.Id;
		CRUDUtility.insertRecords(section);
	}

	public static List<QuoteItemCell__c> getQuoteCellValues(Id quoteId) {
		List<QuoteItem__c> quoteItems = [
			SELECT Id
			FROM QuoteItem__c
			WHERE QuoteId__c = :quoteId
			WITH SECURITY_ENFORCED
		];
		Set<Id> quoteItemIds = (new Map<Id, QuoteItem__c>(quoteItems)).keySet();
		List<QuoteItemCell__c> quoteItemCells = QuoteItemCellService.getQuoteItemCellsByQuoteItemIds(
			quoteItemIds
		);

		return quoteItemCells;
	}

	static TaskRoleSummary__c createTaskRoleSummaryForActivityGroup(Id estimateId) {
		TaskRoleSummary__c taskRoleSummary = new TaskRoleSummary__c();
		taskRoleSummary.EstimateId__c = estimateId;
		taskRoleSummary.SummaryLevel__c = SUMMARYLEVEL_ACTIVITYGROUP;
		return taskRoleSummary;
	}
}