quoting-CypressTK1/force-app/main/default/objects/Estimate__c/fields/QuoteId__c.field-meta.xml
<CustomField>
    <fullName>QuoteId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quote</label>
    <referenceTo>Quote__c</referenceTo>
    <relationshipLabel>Estimate</relationshipLabel>
    <relationshipName>Estimate</relationshipName>
    <type>Lookup</type>
</CustomField>

quoting-CypressTK1/force-app/main/default/objects/Estimate__c/fields/ServiceId__c.field-meta.xml
<CustomField>
    <fullName>ServiceId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(1 AND 2) OR (3 AND 4)</booleanFilter>
        <filterItems>
            <field>$Source.ProductId__c</field>
            <operation>equals</operation>
            <valueField>Product__c.AssociatedProductId__c</valueField>
        </filterItems>
        <filterItems>
            <field>Product__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Service</value>
        </filterItems>
        <filterItems>
            <field>$Source.ProductId__c</field>
            <operation>equals</operation>
            <value />
        </filterItems>
        <filterItems>
            <field>Product__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Service</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Product__c</referenceTo>
    <relationshipLabel>Estimates</relationshipLabel>
    <relationshipName>ServiceEstimates</relationshipName>
    <type>Lookup</type>
</CustomField>

quoting-CypressTK1/force-app/main/default/objects/Product__c/Product__c.object-meta.xml
<CustomObject>
	<description>Provus Product object</description>
	<label>Product</label>
	<nameField>
		<label>Product Name</label>
		<type>Text</type>
	</nameField>
	<pluralLabel>Products</pluralLabel>
	<sharingModel>ReadWrite</sharingModel>
</CustomObject>

quoting-CypressTK1/force-app/main/default/objects/Product__c/fields/Description__c.field-meta.xml
<CustomField>
	<fullName>Description__c</fullName>
	<label>Product Description</label>
	<type>TextArea</type>
</CustomField>

quoting-CypressTK1/force-app/main/default/objects/Product__c/fields/Group__c.field-meta.xml
<CustomField>
	<fullName>Group__c</fullName>
	<label>Group</label>
	<type>Picklist</type>
	<valueSet>
		<restricted>true</restricted>
		<valueSetName>Groups</valueSetName>
	</valueSet>
</CustomField>

quoting-CypressTK1/force-app/main/default/objects/Product__c/fields/Practice__c.field-meta.xml
<CustomField>
	<fullName>Practice__c</fullName>
	<label>Practice</label>
	<type>Picklist</type>
	<valueSet>
		<restricted>true</restricted>
		<valueSetName>Practices</valueSetName>
	</valueSet>
</CustomField>

quoting-CypressTK1/force-app/main/default/objects/Quote__c/fields/RateCardId__c.field-meta.xml
<CustomField>
    <fullName>RateCardId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Rate Card</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(6 OR 7) AND (3 OR 1) AND (4 OR 2) AND 5</booleanFilter>
        <errorMessage
		>The Rate Card is expired/inactive during the selected service start date</errorMessage>
        <filterItems>
            <field>$Source.ServiceStartDate__c</field>
            <operation>greaterOrEqual</operation>
            <valueField>RateCard__c.EffectiveDate__c</valueField>
        </filterItems>
        <filterItems>
            <field>$Source.ServiceStartDate__c</field>
            <operation>lessOrEqual</operation>
            <valueField>RateCard__c.ExpirationDate__c</valueField>
        </filterItems>
        <filterItems>
            <field>RateCard__c.EffectiveDate__c</field>
            <operation>equals</operation>
            <value />
        </filterItems>
        <filterItems>
            <field>RateCard__c.ExpirationDate__c</field>
            <operation>equals</operation>
            <value />
        </filterItems>
        <filterItems>
            <field>RateCard__c.IsActive__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>$Source.AccountId__c</field>
            <operation>equals</operation>
            <valueField>RateCard__c.AssignedToAccountId__c</valueField>
        </filterItems>
        <filterItems>
            <field>RateCard__c.AssignedToAccountId__c</field>
            <operation>equals</operation>
            <value />
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>RateCard__c</referenceTo>
    <relationshipLabel>Quotes</relationshipLabel>
    <relationshipName>Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

quoting-CypressTK1/force-app/main/default/objects/Quote__c/fields/ServiceId__c.field-meta.xml
<CustomField>
    <fullName>ServiceId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service</label>
    <referenceTo>Product__c</referenceTo>
    <relationshipLabel>Quotes</relationshipLabel>
    <relationshipName>ServiceQuotes</relationshipName>
    <type>Lookup</type>
</CustomField>

quoting-CypressTK1/force-app/main/default/objects/QuoteSection__c/fields/ActivityGroupId__c.field-meta.xml
<CustomField>
    <fullName>ActivityGroupId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Activity Group</label>
    <referenceTo>ActivityGroup__c</referenceTo>
    <relationshipName>QuoteSections</relationshipName>
    <type>Lookup</type>
</CustomField>

quoting-CypressTK1/force-app/main/default/objects/ResourceAvailability__c/ResourceAvailability__c.object-meta.xml
<CustomObject>
    <description
	>Captures the maximum time a resource is available to work for a given period</description>
    <label>Resource Availability</label>
    <nameField>
        <displayFormat>RA-{00000}</displayFormat>
        <label>Resource Availability</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Resource Availabilities</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

quoting-CypressTK1/force-app/main/default/objects/ResourceAvailability__c/fields/AvailabilityPercentage__c.field-meta.xml
<CustomField>
    <fullName>AvailabilityPercentage__c</fullName>
    <label>Availability Percentage</label>
    <precision>6</precision>
    <scale>3</scale>
    <type>Percent</type>
</CustomField>

quoting-CypressTK1/force-app/main/default/objects/ResourceAvailability__c/fields/TaskRoleSummaryId__c.field-meta.xml
<CustomField>
    <fullName>TaskRoleSummaryId__c</fullName>
    <label>Task Role Summary</label>
    <referenceTo>TaskRoleSummary__c</referenceTo>
    <relationshipLabel>Resource Availabilities</relationshipLabel>
    <relationshipName>ResourceAvailabilities</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

quoting-CypressTK1/force-app/main/default/objects/ResourceSplit__c/ResourceSplit__c.object-meta.xml
<CustomObject>
    <label>Resource Split</label>
    <nameField>
        <label>Resource Split Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Resource Splits</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

quoting-CypressTK1/force-app/main/default/objects/ResourceSplit__c/fields/SplitPercentage__c.field-meta.xml
<CustomField>
    <fullName>SplitPercentage__c</fullName>
    <label>Split Percentage</label>
    <precision>18</precision>
    <scale>15</scale>
    <type>Percent</type>
</CustomField>

quoting-CypressTK1/force-app/main/default/objects/ResourceSplit__c/fields/TaskRoleSummaryId__c.field-meta.xml
<CustomField>
    <fullName>TaskRoleSummaryId__c</fullName>
    <label>Task Role Summary</label>
    <referenceTo>TaskRoleSummary__c</referenceTo>
    <relationshipLabel>Resource Splits</relationshipLabel>
    <relationshipName>ResourceSplits</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

quoting-CypressTK1/force-app/main/default/objects/ResourceSplit__c/fields/TotalEstimatedDuration__c.field-meta.xml
<CustomField>
    <fullName>TotalEstimatedDuration__c</fullName>
    <formula>TaskRoleSummaryId__r.TotalEstimatedDuration__c  *  SplitPercentage__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total Estimated Duration</label>
    <precision>18</precision>
    <scale>5</scale>
    <type>Number</type>
</CustomField>

quoting-CypressTK1/force-app/main/default/objects/TaskRoleSummary__c/fields/ResourceRoleId__c.field-meta.xml
<CustomField>
    <fullName>ResourceRoleId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Resource Role</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Product__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Resource Role</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Product__c</referenceTo>
    <relationshipName>LevelSummaries</relationshipName>
    <type>Lookup</type>
</CustomField>

quoting-CypressTK1/force-app/main/default/objects/TaskRoleSummary__c/fields/TotalEstimatedDuration__c.field-meta.xml
<CustomField>
    <fullName>TotalEstimatedDuration__c</fullName>
    <formula>TotalCalculatedDuration__c + TotalAdjustments__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total estimated duration</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

quoting-CypressTK1/force-app/main/default/classes/CreateQuoteFromEstimateService.cls
/**
 *  Provus Services Quoting
 *  @2021 Provus Inc. All rights reserved.
 */
public with sharing class CreateQuoteFromEstimateService {
	//String Values
	private static final String STATUS_DRAFT = 'Draft';

	public static QuoteDO getEstimateQuoteDetails(Estimate__c estimateSO) {
		QuoteDO quoteData = new QuoteDO();
		quoteData.isPrimary = true;
		quoteData.description = estimateSO.Description__c;
		quoteData.rateCardId = estimateSO.RateCardId__c;
		quoteData.estimateId = estimateSO.Id;
		quoteData.status = STATUS_DRAFT;
		quoteData.serviceId = estimateSO.ServiceId__c;
		quoteData.practice = estimateSO.ServiceId__r.Practice__c;
		quoteData.groupValue = estimateSO.ServiceId__r.Group__c;

		if (Account.SObjectType.getDescribe().isAccessible()) {
			quoteData.accountId = estimateSO.AccountId__c;
		}
		if (Opportunity.SObjectType.getDescribe().isAccessible()) {
			quoteData.opportunityId = estimateSO.OpportunityId__c;
		}

		return quoteData;
	}

	public static void convertEntitiesFromEstimate(Quote__c quote) {
		createSections(quote);
	}

	@TestVisible
	private static void createSections(Quote__c quoteSO) {
		List<ActivityGroup__c> groups = ActivityGroupService.getApplicableGroups(quoteSO.EstimateId__c);
		EstimateActivityGroupIterator activityGroupIterator = new EstimateActivityGroupIterator(groups);
		Set<Id> orderedRoleIds = EstimateService.getOrderedResourceRoles(quoteSO.EstimateId__c);

		List<QuoteSection__c> sections = new List<QuoteSection__c>();
		Map<String, Decimal> durationsBySectionRole = new Map<String, Decimal>();
		Set<Id> allTaskRoleSummaryIds = new Set<Id>();
		QuoteItemsCreationDetail quoteItemCreationDetails = new QuoteItemsCreationDetail();
		Map<Id, RateCardItem__c> rateCardItemByRoleId = EstimateService.getRateCardItemPreferences(
			quoteSO.EstimateId__c
		);

		while (activityGroupIterator.hasNext()) {
			ActivityGroup__c activityGroup = activityGroupIterator.next();
			QuoteSection__c section = new QuoteSection__c();
			section.Name = activityGroup.Name;
			section.Sequence__c = activityGroup.Sequence__c;
			section.DisplaySequence__c = activityGroup.Sequence__c;
			section.QuoteId__c = quoteSO.Id;
			section.ActivityGroupId__c = activityGroup.Id;
			sections.add(section);

			QuoteSectionDetails sectionDetails = new QuoteSectionDetails();
			Set<Id> roleIds = new Set<Id>();
			for (TaskRoleSummary__c summary : activityGroup.RoleSummaries__r) {
				String durationRoleKey = EstimateService.generateRoleSequenceKey(
					summary.ResourceRoleId__c,
					section
				);

				durationsBySectionRole.put(durationRoleKey, summary.TotalEstimatedDuration__c);
				allTaskRoleSummaryIds.add(summary.Id);
				sectionDetails.taskRoleSummaryIds.put(summary.ResourceRoleId__c, summary.Id);
				roleIds.add(summary.ResourceRoleId__c);
			}

			sectionDetails.section = section;
			sectionDetails.roleIds = EstimateService.filterOrderedRoles(orderedRoleIds, roleIds);
			quoteItemCreationDetails.sectionRequests.add(sectionDetails);
			quoteItemCreationDetails.sequence = activityGroup.Sequence__c;
		}

		CRUDUtility.insertRecords(sections);

		// list of resource split records by task role summary id as the key
		CreateQuoteItemsResponse createQuoteItemsResp = createQuoteItems(
			quoteItemCreationDetails,
			allTaskRoleSummaryIds,
			rateCardItemByRoleId
		);

		CRUDUtility.insertRecords(createQuoteItemsResp.quoteItems);
		if (!createQuoteItemsResp.quoteItems.isEmpty()) {
			EstimateService.createQuoteItemCells(quoteSO, createQuoteItemsResp, durationsBySectionRole);
		}
	}

	private static CreateQuoteItemsResponse createQuoteItems(
		QuoteItemsCreationDetail quoteItemRequest,
		Set<Id> allTaskRoleSummaryIds,
		Map<Id, RateCardItem__c> rateCardItemByRoleId
	) {
		CreateQuoteItemsResponse response = new CreateQuoteItemsResponse();
		// get task role splits
		List<TaskRoleSummary__c> taskRoleSummaries = [
			SELECT
				Id,
				ResourceRoleId__c,
				(SELECT SplitPercentage__c FROM ResourceSplits__r ORDER BY Sequence__c),
				(SELECT AvailabilityPercentage__c FROM ResourceAvailabilities__r LIMIT 1)
			FROM TaskRoleSummary__c
			WHERE Id IN :allTaskRoleSummaryIds
			WITH SECURITY_ENFORCED
			LIMIT :SOQLConstants.SOQL_QUERY_LIMIT
		];

		Map<Id, TaskRoleSummary__c> taskRoleSummariesMap = new Map<Id, TaskRoleSummary__c>(
			taskRoleSummaries
		);

		CreateQuoteItemRequest quoteItemReq = new CreateQuoteItemRequest();
		quoteItemReq.sequence = ++quoteItemRequest.sequence; // quote item sequences start after the last section sequence

		for (QuoteSectionDetails sectionRequest : quoteItemRequest.sectionRequests) {
			quoteItemReq.section = sectionRequest.section;
			quoteItemReq.sectionSequence = 1;

			for (Id roleId : sectionRequest.roleIds) {
				quoteItemReq.roleId = roleId;

				// get task role summary id for role id
				Id roleSummaryId = sectionRequest.taskRoleSummaryIds.get(roleId);
				TaskRoleSummary__c taskRoleSummary = taskRoleSummariesMap.get(roleSummaryId);
				List<ResourceSplit__c> splits = taskRoleSummary.ResourceSplits__r;
				if (splits != null && splits.size() > 0) {
					// create quote item for each corresponding split record
					for (ResourceSplit__c splitPercent : splits) {
						QuoteItem__c newItem = EstimateService.createQuoteItem(
							quoteItemReq,
							rateCardItemByRoleId
						);
						// store split value by derived key
						response.quoteItemSplitsById.put(
							EstimateService.quoteItemSplitRolesKey(newItem),
							splitPercent.SplitPercentage__c
						);
						response.quoteItems.add(newItem);
						quoteItemReq.sectionSequence++;
					}
				} else {
					QuoteItem__c newItem = EstimateService.createQuoteItem(
						quoteItemReq,
						rateCardItemByRoleId
					);
					response.quoteItems.add(newItem);
					quoteItemReq.sectionSequence++;
				}

				// set availability percentage
				response.availabilityPercentageByRoleKey.put(
					roleId +
					'-' +
					quoteItemReq.section.Sequence__c,
					EstimateService.getAvailabilityPercentage(taskRoleSummary)
				);
			}
		}

		return response;
	}

	public class QuoteSectionDetails {
		public Set<Id> roleIds;
		public Map<Id, Id> taskRoleSummaryIds = new Map<Id, Id>();
		public QuoteSection__c section;
	}

	public class QuoteItemsCreationDetail {
		public List<QuoteSectionDetails> sectionRequests = new List<QuoteSectionDetails>();
		public Id quoteId;
		public Set<Id> allTaskRoleSummaryIds = new Set<Id>();
		public Decimal sequence = 1;
	}

	public class CreateQuoteItemRequest {
		public QuoteSection__c section;
		public Integer sectionSequence;
		public Id roleId;
		public Decimal sequence;
	}

	public class CreateQuoteItemsResponse {
		public Map<String, Decimal> quoteItemSplitsById = new Map<String, Decimal>();
		public List<QuoteItem__c> quoteItems = new List<QuoteItem__c>();
		public Map<String, Decimal> availabilityPercentageByRoleKey = new Map<String, Decimal>();
	}
}