quoting-CypressTK1/force-app/main/default/objects/Estimate__c/fields/QuoteId__c.field-meta.xml
<CustomField>
    <fullName>QuoteId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quote</label>
    <referenceTo>Quote__c</referenceTo>
    <relationshipLabel>Estimate</relationshipLabel>
    <relationshipName>Estimate</relationshipName>
    <type>Lookup</type>
</CustomField>

quoting-CypressTK1/force-app/main/default/objects/Estimate__c/fields/ServiceId__c.field-meta.xml
<CustomField>
    <fullName>ServiceId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(1 AND 2) OR (3 AND 4)</booleanFilter>
        <filterItems>
            <field>$Source.ProductId__c</field>
            <operation>equals</operation>
            <valueField>Product__c.AssociatedProductId__c</valueField>
        </filterItems>
        <filterItems>
            <field>Product__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Service</value>
        </filterItems>
        <filterItems>
            <field>$Source.ProductId__c</field>
            <operation>equals</operation>
            <value />
        </filterItems>
        <filterItems>
            <field>Product__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Service</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Product__c</referenceTo>
    <relationshipLabel>Estimates</relationshipLabel>
    <relationshipName>ServiceEstimates</relationshipName>
    <type>Lookup</type>
</CustomField>

quoting-CypressTK1/force-app/main/default/objects/Product__c/Product__c.object-meta.xml
<CustomObject>
	<description>Provus Product object</description>
	<label>Product</label>
	<nameField>
		<label>Product Name</label>
		<type>Text</type>
	</nameField>
	<pluralLabel>Products</pluralLabel>
	<sharingModel>ReadWrite</sharingModel>
</CustomObject>

quoting-CypressTK1/force-app/main/default/objects/Product__c/fields/Description__c.field-meta.xml
<CustomField>
	<fullName>Description__c</fullName>
	<label>Product Description</label>
	<type>TextArea</type>
</CustomField>

quoting-CypressTK1/force-app/main/default/objects/Product__c/fields/Group__c.field-meta.xml
<CustomField>
	<fullName>Group__c</fullName>
	<label>Group</label>
	<type>Picklist</type>
	<valueSet>
		<restricted>true</restricted>
		<valueSetName>Groups</valueSetName>
	</valueSet>
</CustomField>

quoting-CypressTK1/force-app/main/default/objects/Product__c/fields/Practice__c.field-meta.xml
<CustomField>
	<fullName>Practice__c</fullName>
	<label>Practice</label>
	<type>Picklist</type>
	<valueSet>
		<restricted>true</restricted>
		<valueSetName>Practices</valueSetName>
	</valueSet>
</CustomField>

quoting-CypressTK1/force-app/main/default/objects/Quote__c/fields/RateCardId__c.field-meta.xml
<CustomField>
    <fullName>RateCardId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Rate Card</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(6 OR 7) AND (3 OR 1) AND (4 OR 2) AND 5</booleanFilter>
        <errorMessage
		>The Rate Card is expired/inactive during the selected service start date</errorMessage>
        <filterItems>
            <field>$Source.ServiceStartDate__c</field>
            <operation>greaterOrEqual</operation>
            <valueField>RateCard__c.EffectiveDate__c</valueField>
        </filterItems>
        <filterItems>
            <field>$Source.ServiceStartDate__c</field>
            <operation>lessOrEqual</operation>
            <valueField>RateCard__c.ExpirationDate__c</valueField>
        </filterItems>
        <filterItems>
            <field>RateCard__c.EffectiveDate__c</field>
            <operation>equals</operation>
            <value />
        </filterItems>
        <filterItems>
            <field>RateCard__c.ExpirationDate__c</field>
            <operation>equals</operation>
            <value />
        </filterItems>
        <filterItems>
            <field>RateCard__c.IsActive__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>$Source.AccountId__c</field>
            <operation>equals</operation>
            <valueField>RateCard__c.AssignedToAccountId__c</valueField>
        </filterItems>
        <filterItems>
            <field>RateCard__c.AssignedToAccountId__c</field>
            <operation>equals</operation>
            <value />
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>RateCard__c</referenceTo>
    <relationshipLabel>Quotes</relationshipLabel>
    <relationshipName>Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

quoting-CypressTK1/force-app/main/default/objects/Quote__c/fields/ServiceId__c.field-meta.xml
<CustomField>
    <fullName>ServiceId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service</label>
    <referenceTo>Product__c</referenceTo>
    <relationshipLabel>Quotes</relationshipLabel>
    <relationshipName>ServiceQuotes</relationshipName>
    <type>Lookup</type>
</CustomField>

quoting-CypressTK1/force-app/main/default/classes/CreateQuoteFromEstimateController.cls
/**
 *  Provus Services Quoting
 *  CreateQuoteFromEstimateController
 *  @2021 Provus Inc. All rights reserved.
 */
public with sharing class CreateQuoteFromEstimateController {
	@AuraEnabled(Cacheable=true)
	public static QuoteDO getEstimateDetails(String estimateId) {
		//Required Fields from estimate
		Set<String> requiredFields = new Set<String>();
		if (Account.SObjectType.getDescribe().isAccessible()) {
			requiredFields.add(Schema.Estimate__c.AccountId__c + '');
		}
		if (Opportunity.SObjectType.getDescribe().isAccessible()) {
			requiredFields.add(Schema.Estimate__c.OpportunityId__c + '');
		}

		requiredFields.add(Schema.Estimate__c.Description__c + '');
		requiredFields.add(Schema.Estimate__c.RateCardId__c + '');
		requiredFields.add(Schema.Estimate__c.ServiceId__c + '');
		requiredFields.add(
			SystemUtility.getRName(Schema.Estimate__c.ServiceId__c) +
			'.' +
			Schema.Product__c.Practice__c
		);
		requiredFields.add(
			SystemUtility.getRName(Schema.Estimate__c.ServiceId__c) +
			'.' +
			Schema.Product__c.Group__c
		);

		QueryRequest queryRequest = new QueryRequest(Schema.Estimate__c.SObjectType);
		queryRequest.requestedFields = requiredFields;
		queryRequest.setFilterBy(new Map<String, String>{ SObjectUtility.FIELD_ID => estimateId });
		List<Estimate__c> estimates = SOQLUtility.querySObject(queryRequest);

		QuoteDO quoteData;
		if (!estimates.isEmpty()) {
			Estimate__c estimateSO = estimates[0];
			quoteData = CreateQuoteFromEstimateService.getEstimateQuoteDetails(estimateSO);
		}
		return quoteData;
	}

	@AuraEnabled
	public static Date getServiceEndDate(Id estimateId, EndDateArgs endDateArgs) {
		return EstimateService.getServiceEndDate(estimateId, endDateArgs);
	}

	@AuraEnabled
	public static Boolean isValidPeriodCount(
		Date serviceStartDate,
		Date serviceEndDate,
		String timePeriods
	) {
		ITimePeriod timePeriodCalc = TimePeriodFactory.newTimePeriod(timePeriods);
		Decimal periodCount = timePeriodCalc.numberOfPeriods(serviceStartDate, serviceEndDate);

		if (periodCount > QuotePeriodService.MAX_PERIOD_COUNT) {
			return false;
		}

		return true;
	}

	@AuraEnabled
	public static Id createQuote(String quoteDetails) {
		QuoteDO quoteDate = (QuoteDO) JSON.deserialize(quoteDetails, QuoteDO.class);
		Quote__c quoteSO = QuoteDO.getQuoteFromData(quoteDate);
		quoteSO.QuoteDate__c = System.today();
		quoteSO.Version__c = 1;
		quoteSO.Type__c = QuoteService.RECORDTYPE_NAME_QUOTE;
		CRUDUtility.insertRecords(quoteSO);

		CreateQuoteFromEstimateService.convertEntitiesFromEstimate(quoteSO);
		associateQuoteToEstimate(quoteSO);
		return quoteSO.Id;
	}

	public static void associateQuoteToEstimate(Quote__c quote) {
		QueryRequest queryRequest = new QueryRequest(Schema.Estimate__c.SObjectType);

		queryRequest.requestedFields = SObjectUtility.getFieldsForSObject(
			Schema.Estimate__c.SObjectType
		);

		queryRequest.setFilterBy(
			new Map<String, String>{ Schema.Estimate__c.Id + '' => quote.EstimateId__c }
		);

		List<Estimate__c> estimate = (List<Estimate__c>) SOQLUtility.querySObject(queryRequest);
		estimate[0].QuoteId__c = quote.Id;
		CRUDUtility.updateRecords(estimate);
	}
}