quoting-CypressTK1/force-app/main/default/objects/Estimate__c/fields/ServiceId__c.field-meta.xml
<CustomField>
    <fullName>ServiceId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(1 AND 2) OR (3 AND 4)</booleanFilter>
        <filterItems>
            <field>$Source.ProductId__c</field>
            <operation>equals</operation>
            <valueField>Product__c.AssociatedProductId__c</valueField>
        </filterItems>
        <filterItems>
            <field>Product__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Service</value>
        </filterItems>
        <filterItems>
            <field>$Source.ProductId__c</field>
            <operation>equals</operation>
            <value />
        </filterItems>
        <filterItems>
            <field>Product__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Service</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Product__c</referenceTo>
    <relationshipLabel>Estimates</relationshipLabel>
    <relationshipName>ServiceEstimates</relationshipName>
    <type>Lookup</type>
</CustomField>

quoting-CypressTK1/force-app/main/default/objects/Product2/recordTypes/Product.recordType-meta.xml
<RecordType>
    <fullName>Product</fullName>
    <active>false</active>
    <label>Product</label>
</RecordType>

quoting-CypressTK1/force-app/main/default/objects/Product2/recordTypes/Service.recordType-meta.xml
<RecordType>
    <fullName>Service</fullName>
    <active>false</active>
    <label>Service</label>
</RecordType>

quoting-CypressTK1/force-app/main/default/objects/Product__c/Product__c.object-meta.xml
<CustomObject>
	<description>Provus Product object</description>
	<label>Product</label>
	<nameField>
		<label>Product Name</label>
		<type>Text</type>
	</nameField>
	<pluralLabel>Products</pluralLabel>
	<sharingModel>ReadWrite</sharingModel>
</CustomObject>

quoting-CypressTK1/force-app/main/default/objects/Product__c/fields/StandardProductId__c.field-meta.xml
<CustomField>
    <fullName>StandardProductId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Provus Products</relationshipLabel>
    <relationshipName>ProvusProducts</relationshipName>
    <type>Lookup</type>
</CustomField>

quoting-CypressTK1/force-app/main/default/objects/Product__c/recordTypes/Product.recordType-meta.xml
<RecordType>
	<fullName>Product</fullName>
	<active>true</active>	
	<label>Product</label>
</RecordType>

quoting-CypressTK1/force-app/main/default/objects/Product__c/recordTypes/Service.recordType-meta.xml
<RecordType>
	<fullName>Service</fullName>
	<active>true</active>	
	<label>Service</label>
</RecordType>

quoting-CypressTK1/force-app/main/default/objects/Quote__c/fields/ServiceId__c.field-meta.xml
<CustomField>
    <fullName>ServiceId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service</label>
    <referenceTo>Product__c</referenceTo>
    <relationshipLabel>Quotes</relationshipLabel>
    <relationshipName>ServiceQuotes</relationshipName>
    <type>Lookup</type>
</CustomField>

quoting-CypressTK1/force-app/main/default/classes/ServiceRecommendationsControllerTest.cls
/**
 *  Provus Services Quoting
 *  ServiceRecommendationsControllerTest
 *  @2021 Provus Inc. All rights reserved.
 */
@isTest
public with sharing class ServiceRecommendationsControllerTest extends ServiceRecommendationsTestsBase {
	private static final String PRODUCT_MAIN_PRODUCT = 'Main Product';
	private static final String PRODUCT_SERVICE_PRODUCT = 'Service Product';
	private static final String QUOTE_TEMPLATE_NAME = 'Test Quote Template';

	@testSetup
	static void setup() {
		setupData();
		createProductOpportunityLineItem();
	}

	@isTest
	static void itShouldGetServiceRecommendations() {
		Test.startTest();
		Opportunity opp = [SELECT Id FROM Opportunity WHERE Name = 'Test' LIMIT 1];
		Map<Id, ServiceRecommendationsController.ServiceRecommendation> serviceRecommendations = ServiceRecommendationsController.getServiceRecommendations(
			opp.Id
		);
		System.assertEquals(1, serviceRecommendations.size(), 'There is 1 service recommendation');
		Test.stopTest();
	}

	@isTest
	static void itShouldGetNoServiceRecommendations() {
		Test.startTest();
		Opportunity opp = newOpportunity();
		Map<Id, ServiceRecommendationsController.ServiceRecommendation> serviceRecommendations = ServiceRecommendationsController.getServiceRecommendations(
			opp.Id
		);
		System.assertEquals(0, serviceRecommendations.size(), 'There are no service recommendation');
		Test.stopTest();
	}

	@isTest
	static void itShouldAddServiceRecommendations() {
		Test.startTest();
		Opportunity opp = [SELECT Id FROM Opportunity WHERE Name = 'Test' LIMIT 1];
		Product2 product = [SELECT Id, Name FROM Product2 WHERE Name = :PRODUCT_MAIN_PRODUCT];
		Product2 service = [SELECT Id, Name FROM Product2 WHERE Name = :PRODUCT_SERVICE_PRODUCT];
		ServiceRecommendationsController.ServiceOpportunity serviceOpportunity = ServiceRecommendationsController.addServiceToOpportunity(
			opp.Id,
			service.Id,
			product.Id
		);
		System.assert(serviceOpportunity.success, 'Service recommendation was added successfully');
		Test.stopTest();
	}

	@isTest
	static void itShouldFailServiceRecommendationsForMissingEstimate() {
		Test.startTest();
		Opportunity opp = [SELECT Id FROM Opportunity WHERE Name = 'Test' LIMIT 1];
		Product2 product = [SELECT Id, Name FROM Product2 WHERE Name = :PRODUCT_MAIN_PRODUCT];
		Product2 service = [SELECT Id, Name FROM Product2 WHERE Name = :PRODUCT_SERVICE_PRODUCT];
		Product__c cservice = [
			SELECT Id, Name
			FROM Product__c
			WHERE StandardProductId__c = :service.Id
		];
		Estimate__c estimate = [SELECT Id FROM Estimate__c WHERE ServiceId__c = :cservice.Id LIMIT 1];
		delete estimate;
		// ignore initial setup data
		List<Quote__c> quotes = [SELECT Id FROM Quote__c WHERE ServiceId__c = :cservice.Id];
		delete quotes;
		ServiceRecommendationsController.ServiceOpportunity serviceOpportunity = ServiceRecommendationsController.addServiceToOpportunity(
			opp.Id,
			service.Id,
			product.Id
		);
		System.assert(
			!serviceOpportunity.success,
			'It should have failed to return any service recommendations'
		);
		Test.stopTest();
	}

	@isTest
	static void itShouldGenerateFromEstimateForServiceRecommendations() {
		Test.startTest();
		Opportunity opp = [SELECT Id FROM Opportunity WHERE Name = 'Test' LIMIT 1];
		Product2 product = [SELECT Id, Name FROM Product2 WHERE Name = :PRODUCT_MAIN_PRODUCT];
		Product2 service = [SELECT Id, Name FROM Product2 WHERE Name = :PRODUCT_SERVICE_PRODUCT];
		Product__c cservice = [
			SELECT Id, Name
			FROM Product__c
			WHERE StandardProductId__c = :service.Id
		];
		Estimate__c estimate = [SELECT Id FROM Estimate__c WHERE ServiceId__c = :cservice.Id LIMIT 1];
		Quote__c quote = [SELECT Id FROM Quote__c WHERE EstimateId__c = :estimate.Id LIMIT 1];
		delete quote;
		ServiceRecommendationsController.ServiceOpportunity serviceOpportunity = ServiceRecommendationsController.addServiceToOpportunity(
			opp.Id,
			service.Id,
			product.Id
		);
		System.assert(
			serviceOpportunity.success,
			'It should have created a quote and associated to opportunity for an estimate'
		);
		Test.stopTest();
	}

	@isTest
	static void itShouldGenerateFromUniqueEstimatesForServiceRecommendations() {
		Test.startTest();
		Opportunity opp = [SELECT Id FROM Opportunity WHERE Name = 'Test' LIMIT 1];
		Product2 product = [SELECT Id, Name FROM Product2 WHERE Name = :PRODUCT_MAIN_PRODUCT];
		Product2 service = [SELECT Id, Name FROM Product2 WHERE Name = :PRODUCT_SERVICE_PRODUCT];
		ServiceRecommendationsController.ServiceOpportunity serviceOpportunity = ServiceRecommendationsController.addServiceToOpportunity(
			opp.Id,
			service.Id,
			product.Id
		);

		Opportunity opp2 = newOpportunity();
		opp2.Name = 'Test2';
		update opp2;
		ServiceRecommendationsController.ServiceOpportunity serviceOpportunity2 = ServiceRecommendationsController.addServiceToOpportunity(
			opp2.Id,
			service.Id,
			product.Id
		);

		Quote__c quoteSO1 = [
			SELECT Id
			FROM Quote__c
			WHERE OpportunityId__c = :opp.Id AND ServiceId__r.StandardProductId__c = :service.Id
			LIMIT 1
		];
		Quote__c quoteSO2 = [
			SELECT Id
			FROM Quote__c
			WHERE OpportunityId__c = :opp2.Id AND ServiceId__r.StandardProductId__c = :service.Id
			LIMIT 1
		];
		System.assertNotEquals(quoteSO1.Id, quoteSO2.Id, 'Quotes should be unique from each other');

		Test.stopTest();
	}
}