quoting-CypressTK1/force-app/main/default/objects/ScopeParameterTemplate__c/ScopeParameterTemplate__c.object-meta.xml
<CustomObject>
    <label>Scope Parameter Template</label>
    <nameField>
        <label>Scope Parameter Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Scope Parameter Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

quoting-CypressTK1/force-app/main/default/objects/ScopeParameterTemplate__c/fields/ActivityGroupTemplateId__c.field-meta.xml
<CustomField>
    <fullName>ActivityGroupTemplateId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Activity Group Template</label>
    <referenceTo>ActivityGroupTemplate__c</referenceTo>
    <relationshipLabel>Scope Parameter Templates</relationshipLabel>
    <relationshipName>ScopeParameterTemplates</relationshipName>
    <type>Lookup</type>
</CustomField>

quoting-CypressTK1/force-app/main/default/objects/ScopeParameterTemplate__c/fields/ActivityTemplateId__c.field-meta.xml
<CustomField>
    <fullName>ActivityTemplateId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Activity Template</label>
    <referenceTo>ActivityTemplate__c</referenceTo>
    <relationshipLabel>Scope Parameter Templates</relationshipLabel>
    <relationshipName>ScopeParameterTemplates</relationshipName>
    <type>Lookup</type>
</CustomField>

quoting-CypressTK1/force-app/main/default/objects/ScopeParameterTemplate__c/fields/AllowedValues__c.field-meta.xml
<CustomField>
    <fullName>AllowedValues__c</fullName>
    <label>Allowed Values</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

quoting-CypressTK1/force-app/main/default/objects/ScopeParameterTemplate__c/fields/DeveloperName__c.field-meta.xml
<CustomField>
    <fullName>DeveloperName__c</fullName>
    <label>Hashtag</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

quoting-CypressTK1/force-app/main/default/objects/ScopeParameterTemplate__c/fields/EstimateTemplateId__c.field-meta.xml
<CustomField>
    <fullName>EstimateTemplateId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Estimate Template</label>
    <referenceTo>EstimateTemplate__c</referenceTo>
    <relationshipLabel>Scope Parameter Templates</relationshipLabel>
    <relationshipName>ScopeParameterTemplates</relationshipName>
    <type>Lookup</type>
</CustomField>

quoting-CypressTK1/force-app/main/default/objects/ScopeParameterValueTemplate__c/ScopeParameterValueTemplate__c.object-meta.xml
<CustomObject>
    <label>Scope Parameter Value Template</label>
    <nameField>
        <displayFormat>SPVT-{00000}</displayFormat>
        <label>Scope Parameter Value Template Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Scope Parameter Value Templates</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

quoting-CypressTK1/force-app/main/default/objects/ScopeParameterValueTemplate__c/fields/ScopeParameterTemplateId__c.field-meta.xml
<CustomField>
    <fullName>ScopeParameterTemplateId__c</fullName>
    <label>Scope Parameter Template</label>
    <referenceTo>ScopeParameterTemplate__c</referenceTo>
    <relationshipLabel>Scope Parameter Value Templates</relationshipLabel>
    <relationshipName>ScopeParameterValueTemplates</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

quoting-CypressTK1/force-app/main/default/classes/ScopeParameterTemplateDto.cls
/*
 * Provus Services Quoting
 * Copyright (c) 2022 Provus Inc. All rights reserved.
 */

public with sharing class ScopeParameterTemplateDto extends ScopeParameterBaseDto {
	public ScopeParameterTemplate__c templateSo;
	@AuraEnabled
	public Id estimateTemplateId { get; set; }
	@AuraEnabled
	public Id activityGroupTemplateId { get; set; }
	@AuraEnabled
	public Id activityTemplateId { get; set; }
	@AuraEnabled
	public List<ScopeParameterValueTemplateDto> paramValues { get; set; }
	@AuraEnabled
	public String allowedValues { get; set; }

	public ScopeParameterTemplateDto() {
		super();
	}

	public ScopeParameterTemplateDto(ScopeParameterTemplate__c scopeParameterSo) {
		super(scopeParameterSo);
		stripUnqueried();
		scopeParameterSo = (ScopeParameterTemplate__c) this.sObj;

		this.id = scopeParameterSo.Id;
		this.sequence = scopeParameterSo.Sequence__c;
		this.name = scopeParameterSo.Name;
		this.guidance = scopeParameterSo.Guidance__c;
		this.dataType = scopeParameterSo.DataType__c;
		this.developerName = scopeParameterSo.DeveloperName__c; // the hash tag name
		this.estimateTemplateId = scopeParameterSo.EstimateTemplateId__c;
		this.activityGroupTemplateId = scopeParameterSo.ActivityGroupTemplateId__c;
		this.activityTemplateId = scopeParameterSo.ActivityTemplateId__c;
		this.allowedValues = scopeParameterSo.AllowedValues__c;

		List<ScopeParameterValueTemplateDto> paramValues = new List<ScopeParameterValueTemplateDto>();
		if (scopeParameterSo.ScopeParameterValueTemplates__r != null) {
			for (
				ScopeParameterValueTemplate__c valueTemplateSo : scopeParameterSo.ScopeParameterValueTemplates__r
			) {
				paramValues.add(new ScopeParameterValueTemplateDto(valueTemplateSo));
			}
		}
		this.paramValues = paramValues;
	}

	public override SObject refreshSo() {
		if (this.templateSo == null) {
			this.templateSo = new ScopeParameterTemplate__c(Id = this.id);
		}

		this.templateSo.Sequence__c = this.sequence;
		this.templateSo.Name = this.name;
		this.templateSo.Guidance__c = this.guidance;
		this.templateSo.DataType__c = this.dataType;
		this.templateSo.DeveloperName__c = this.developerName;
		this.templateSo.EstimateTemplateId__c = this.estimateTemplateId;
		this.templateSo.ActivityGroupTemplateId__c = this.activityGroupTemplateId;
		this.templateSo.ActivityTemplateId__c = this.activityTemplateId;
		this.templateSo.AllowedValues__c = this.allowedValues;
		return this.templateSo;
	}
}