quoting-CypressTK1/force-app/main/default/objects/ScopeParameterTemplate__c/ScopeParameterTemplate__c.object-meta.xml
<CustomObject>
    <label>Scope Parameter Template</label>
    <nameField>
        <label>Scope Parameter Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Scope Parameter Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

quoting-CypressTK1/force-app/main/default/objects/ScopeParameterTemplate__c/fields/ActivityGroupTemplateId__c.field-meta.xml
<CustomField>
    <fullName>ActivityGroupTemplateId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Activity Group Template</label>
    <referenceTo>ActivityGroupTemplate__c</referenceTo>
    <relationshipLabel>Scope Parameter Templates</relationshipLabel>
    <relationshipName>ScopeParameterTemplates</relationshipName>
    <type>Lookup</type>
</CustomField>

quoting-CypressTK1/force-app/main/default/objects/ScopeParameterTemplate__c/fields/ActivityTemplateId__c.field-meta.xml
<CustomField>
    <fullName>ActivityTemplateId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Activity Template</label>
    <referenceTo>ActivityTemplate__c</referenceTo>
    <relationshipLabel>Scope Parameter Templates</relationshipLabel>
    <relationshipName>ScopeParameterTemplates</relationshipName>
    <type>Lookup</type>
</CustomField>

quoting-CypressTK1/force-app/main/default/objects/ScopeParameterValueTemplate__c/ScopeParameterValueTemplate__c.object-meta.xml
<CustomObject>
    <label>Scope Parameter Value Template</label>
    <nameField>
        <displayFormat>SPVT-{00000}</displayFormat>
        <label>Scope Parameter Value Template Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Scope Parameter Value Templates</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

quoting-CypressTK1/force-app/main/default/objects/ScopeParameterValueTemplate__c/fields/ScopeParameterTemplateId__c.field-meta.xml
<CustomField>
    <fullName>ScopeParameterTemplateId__c</fullName>
    <label>Scope Parameter Template</label>
    <referenceTo>ScopeParameterTemplate__c</referenceTo>
    <relationshipLabel>Scope Parameter Value Templates</relationshipLabel>
    <relationshipName>ScopeParameterValueTemplates</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

quoting-CypressTK1/force-app/main/default/objects/TaskParameterTemplate__c/fields/ScopeParameterTemplateId__c.field-meta.xml
<CustomField>
    <fullName>ScopeParameterTemplateId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Scope Parameter</label>
    <referenceTo>ScopeParameterTemplate__c</referenceTo>
    <relationshipLabel>Task Parameters</relationshipLabel>
    <relationshipName>TaskParameters</relationshipName>
    <type>Lookup</type>
</CustomField>

quoting-CypressTK1/force-app/main/default/classes/TaskParameterTemplateTriggersTest.cls
/*
 * Provus Services Quoting
 * Copyright (c) 2022 Provus Inc. All rights reserved.
 */
@IsTest
private class TaskParameterTemplateTriggersTest {
	@IsTest
	static void shouldCopyScopeParamValuesToTaskTemplate() {
		ScopeParameterTemplate__c scopeParam = new ScopeParameterTemplate__c();
		CRUDUtility.insertRecords(scopeParam);

		ScopeParameterValueTemplate__c scopeParamValue = new ScopeParameterValueTemplate__c(
			ScopeParameterTemplateId__c = scopeParam.Id
		);
		CRUDUtility.insertRecords(scopeParamValue);

		ActivityGroupTemplate__c activityGroup = new ActivityGroupTemplate__c();
		CRUDUtility.insertRecords(activityGroup);

		ActivityTemplate__c activity = new ActivityTemplate__c(
			ActivityGroupTemplateId__c = activityGroup.Id
		);
		CRUDUtility.insertRecords(activity);

		TaskTemplate__c task = new TaskTemplate__c(ActivityTemplateId__c = activity.Id);
		CRUDUtility.insertRecords(task);

		TaskParameterTemplate__c taskParam = new TaskParameterTemplate__c(
			TaskTemplateId__c = task.Id,
			ScopeParameterTemplateId__c = scopeParam.Id
		);
		Test.startTest();
		{
			CRUDUtility.insertRecords(taskParam);
			List<TaskParameterValueTemplate__c> taskParameterValueTemplates = [
				SELECT Id
				FROM TaskParameterValueTemplate__c
				WHERE TaskParameterTemplateId__c = :taskParam.Id
				WITH SECURITY_ENFORCED
				LIMIT :SOQLConstants.SOQL_QUERY_LIMIT
			];
			System.assert(
				taskParameterValueTemplates.size() > 0,
				'should have task parameter values copied'
			);

			taskParam.ScopeParameterTemplateId__c = null;
			CRUDUtility.updateRecords(taskParam);

			taskParameterValueTemplates = [
				SELECT Id
				FROM TaskParameterValueTemplate__c
				WHERE TaskParameterTemplateId__c = :taskParam.Id
				WITH SECURITY_ENFORCED
				LIMIT :SOQLConstants.SOQL_QUERY_LIMIT
			];
			System.assert(
				taskParameterValueTemplates.size() == 0,
				'should have task parameter values deleted'
			);
		}
		Test.stopTest();
	}
}