quoting-CypressTK1/force-app/main/default/objects/ScopeParameterTemplate__c/ScopeParameterTemplate__c.object-meta.xml
<CustomObject>
    <label>Scope Parameter Template</label>
    <nameField>
        <label>Scope Parameter Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Scope Parameter Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

quoting-CypressTK1/force-app/main/default/objects/ScopeParameterValueTemplate__c/ScopeParameterValueTemplate__c.object-meta.xml
<CustomObject>
    <label>Scope Parameter Value Template</label>
    <nameField>
        <displayFormat>SPVT-{00000}</displayFormat>
        <label>Scope Parameter Value Template Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Scope Parameter Value Templates</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

quoting-CypressTK1/force-app/main/default/objects/ScopeParameterValueTemplate__c/fields/ScopeParameterTemplateId__c.field-meta.xml
<CustomField>
    <fullName>ScopeParameterTemplateId__c</fullName>
    <label>Scope Parameter Template</label>
    <referenceTo>ScopeParameterTemplate__c</referenceTo>
    <relationshipLabel>Scope Parameter Value Templates</relationshipLabel>
    <relationshipName>ScopeParameterValueTemplates</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

quoting-CypressTK1/force-app/main/default/classes/ScopeParameterDialogController.cls
/*
 * Provus Services Quoting
 * Copyright (c) 2022 Provus Inc. All rights reserved.
 */

public with sharing class ScopeParameterDialogController {
	@AuraEnabled
	public static List<ScopeParameterTemplateDto> getScopeParameters(Id parentId) {
		return ScopeParameterTemplateService.getParamsForParentId(parentId);
	}

	@AuraEnabled
	public static List<String> getHashtagsForEstimate(Id estimateId) {
		return HashtagDictionaryService.getHashtagsForEstimateTemplate(estimateId);
	}

	@AuraEnabled
	public static List<ScopeParameterTemplateDto> saveScopeParameters(
		Id parentId,
		List<ScopeParameterTemplateDto> params
	) {
		List<ScopeParameterTemplate__c> paramSos = new List<ScopeParameterTemplate__c>();
		Map<Decimal, List<ScopeParameterValueTemplate__c>> paramValueSosByParentSequence = new Map<Decimal, List<ScopeParameterValueTemplate__c>>();
		for (ScopeParameterTemplateDto param : params) {
			if (parentId.getSobjectType() == Schema.EstimateTemplate__c.SObjectType) {
				param.estimateTemplateId = parentId;
			} else if (parentId.getSobjectType() == Schema.ActivityGroupTemplate__c.SObjectType) {
				param.activityGroupTemplateId = parentId;
			} else if (parentId.getSobjectType() == Schema.ActivityTemplate__c.SObjectType) {
				param.activityTemplateId = parentId;
			}

			if (!SystemUtility.nullOrEmpty(param.paramValues)) {
				List<String> allowedValues = new List<String>();
				List<ScopeParameterValueTemplate__c> paramValueSos = new List<ScopeParameterValueTemplate__c>();
				for (ScopeParameterValueTemplateDto paramValueDto : param.paramValues) {
					allowedValues.add(
						param.dataType == ScopeParameterService.DATATYPE_PICKLIST
							? paramValueDto.label
							: paramValueDto.fromValue + '-' + paramValueDto.toValue
					);
					paramValueSos.add((ScopeParameterValueTemplate__c) paramValueDto.refreshSo());
				}
				param.allowedValues = String.join(allowedValues, '; ');
				paramValueSosByParentSequence.put(param.sequence, paramValueSos);
			}

			paramSos.add((ScopeParameterTemplate__c) param.refreshSo());
		}

		CRUDUtility.upsertRecords(
			associateParentToParameterValues(
				CRUDUtility.upsertRecords(paramSos),
				paramValueSosByParentSequence
			)
		);
		return getScopeParameters(parentId);
	}

	private static List<ScopeParameterValueTemplate__c> associateParentToParameterValues(
		List<ScopeParameterTemplate__c> paramSos,
		Map<Decimal, List<ScopeParameterValueTemplate__c>> paramValueSosByParentSequence
	) {
		List<ScopeParameterValueTemplate__c> updateParamValueSos = new List<ScopeParameterValueTemplate__c>();
		for (ScopeParameterTemplate__c paramSo : paramSos) {
			List<ScopeParameterValueTemplate__c> paramValuesForParam = paramValueSosByParentSequence.get(
				paramSo.Sequence__c
			);
			if (!SystemUtility.nullOrEmpty(paramValuesForParam)) {
				for (ScopeParameterValueTemplate__c paramValueSo : paramValuesForParam) {
					if (paramValueSo.Id == null) {
						paramValueSo.ScopeParameterTemplateId__c = paramSo.Id;
					}
					updateParamValueSos.add(paramValueSo);
				}
			}
		}

		return updateParamValueSos;
	}

	@AuraEnabled
	public static void deleteScopeParameters(List<ScopeParameterTemplateDto> templateDtos) {
		List<ScopeParameterTemplate__c> paramSos = new List<ScopeParameterTemplate__c>();
		for (ScopeParameterTemplateDto paramDtos : templateDtos) {
			paramSos.add((ScopeParameterTemplate__c) paramDtos.refreshSo());
		}

		CRUDUtility.deleteRecords(paramSos);
	}

	@AuraEnabled
	public static void deleteScopeParameterValues(
		List<ScopeParameterValueTemplateDto> valueTemplateDtos
	) {
		List<ScopeParameterValueTemplate__c> valueTemplateSos = new List<ScopeParameterValueTemplate__c>();
		for (ScopeParameterValueTemplateDto valueTemplateDto : valueTemplateDtos) {
			valueTemplateSos.add((ScopeParameterValueTemplate__c) valueTemplateDto.refreshSo());
		}

		CRUDUtility.deleteRecords(valueTemplateSos);
	}
}