quoting-CypressTK1/force-app/main/default/objects/CloneSchema__mdt/CloneSchema__mdt.object-meta.xml
<CustomObject>
    <label>Clone Schema</label>
    <pluralLabel>Clone Schemas</pluralLabel>
</CustomObject>

quoting-CypressTK1/force-app/main/default/objects/CloneSchema__mdt/fields/Criteria__c.field-meta.xml
<CustomField>
    <fullName>Criteria__c</fullName>
    <label>Criteria</label>
    <length>256</length>
    <type>LongTextArea</type>
</CustomField>

quoting-CypressTK1/force-app/main/default/objects/CloneSchema__mdt/fields/IsRootCloneSchema__c.field-meta.xml
<CustomField>
    <fullName>IsRootCloneSchema__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Is Root Clone Schema</label>
    <type>Checkbox</type>
</CustomField>

quoting-CypressTK1/force-app/main/default/objects/CloneSchema__mdt/fields/TargetObjectApiName__c.field-meta.xml
<CustomField>
    <fullName>TargetObjectApiName__c</fullName>
    <label>Target Object Api Name</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

quoting-CypressTK1/force-app/main/default/objects/CloneSchemaField__mdt/CloneSchemaField__mdt.object-meta.xml
<CustomObject>
    <label>Clone Schema Field</label>
    <pluralLabel>Clone Schema Fields</pluralLabel>
</CustomObject>

quoting-CypressTK1/force-app/main/default/objects/CloneSchemaField__mdt/fields/CloneSchemaId__c.field-meta.xml
<CustomField>
    <fullName>CloneSchemaId__c</fullName>
    <label>Clone Schema</label>
    <referenceTo>CloneSchema__mdt</referenceTo>
    <relationshipLabel>Clone Schema Fields</relationshipLabel>
    <relationshipName>CloneSchemaFields</relationshipName>
    <required>true</required>
    <type>MetadataRelationship</type>
</CustomField>

quoting-CypressTK1/force-app/main/default/objects/CloneSchemaField__mdt/fields/FieldApiName__c.field-meta.xml
<CustomField>
    <fullName>FieldApiName__c</fullName>
    <label>Field Api Name</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

quoting-CypressTK1/force-app/main/default/objects/CloneSchemaField__mdt/fields/MergeValue__c.field-meta.xml
<CustomField>
    <fullName>MergeValue__c</fullName>
    <label>Merge Value</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

quoting-CypressTK1/force-app/main/default/objects/CloneSchemaParentChild__mdt/CloneSchemaParentChild__mdt.object-meta.xml
<CustomObject>
    <label>Clone Schema Parent/Child</label>
    <pluralLabel>Clone Schema Parent/Children</pluralLabel>
</CustomObject>

quoting-CypressTK1/force-app/main/default/objects/CloneSchemaParentChild__mdt/fields/ChildCloneSchemaId__c.field-meta.xml
<CustomField>
    <fullName>ChildCloneSchemaId__c</fullName>
    <label>Child Clone Schema</label>
    <referenceTo>CloneSchema__mdt</referenceTo>
    <relationshipLabel>Children Clone Schemas</relationshipLabel>
    <relationshipName>ChildrenCloneSchemas</relationshipName>
    <required>true</required>
    <type>MetadataRelationship</type>
</CustomField>

quoting-CypressTK1/force-app/main/default/objects/CloneSchemaParentChild__mdt/fields/ParentCloneSchemaId__c.field-meta.xml
<CustomField>
    <fullName>ParentCloneSchemaId__c</fullName>
    <label>Parent Clone Schema</label>
    <referenceTo>CloneSchema__mdt</referenceTo>
    <relationshipLabel>Children Clone Schemas</relationshipLabel>
    <relationshipName>CloneSchemas</relationshipName>
    <required>true</required>
    <type>MetadataRelationship</type>
</CustomField>

quoting-CypressTK1/force-app/main/default/objects/CloneSchemaParentChild__mdt/fields/Sequence__c.field-meta.xml
<CustomField>
    <fullName>Sequence__c</fullName>
    <label>Sequence</label>
    <precision>2</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

quoting-CypressTK1/force-app/customMetadataAPI/default/objects/MetadataDeployment__e/MetadataDeployment__e.object-meta.xml
<CustomObject>
    <label>MetadataDeployment</label>
    <pluralLabel>Metadata Deployment</pluralLabel>
</CustomObject>

quoting-CypressTK1/force-app/customMetadataAPI/default/objects/MetadataDeployment__e/fields/DeploymentId__c.field-meta.xml
<CustomField>
    <fullName>DeploymentId__c</fullName>
    <label>DeploymentId</label>
    <length>32</length>
    <type>Text</type>
</CustomField>

quoting-CypressTK1/force-app/customMetadataAPI/default/objects/MetadataDeployment__e/fields/Result__c.field-meta.xml
<CustomField>
    <fullName>Result__c</fullName>
    <label>Result</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

quoting-CypressTK1/force-app/main/default/classes/CloneSchemaService.cls
/*
 * Provus Services Quoting
 * Copyright (c) 2022 Provus Inc. All rights reserved.
 */
public with sharing class CloneSchemaService {
	public static Map<String, CloneSchemaField__mdt> getCloneSchemaFieldByName(String schemaName) {
		Map<String, CloneSchemaField__mdt> schemaFieldByName = new Map<String, CloneSchemaField__mdt>();
		CloneSchema__mdt parentSchema = [
			SELECT (SELECT FieldApiName__c, MergeValue__c FROM CloneSchemaFields__r)
			FROM CloneSchema__mdt
			WHERE DeveloperName = :schemaName
			WITH SECURITY_ENFORCED
		];

		for (CloneSchemaField__mdt schemaField : parentSchema.CloneSchemaFields__r) {
			schemaFieldByName.put(transformApiNames(schemaField.FieldApiName__c), schemaField);
		}

		return schemaFieldByName;
	}

	public static String transformApiNames(String api) {
		return api.replaceAll('PSQ__', SystemUtility.getNamespacePrefix());
	}

	public static CloneSchema__mdt getParentSchema(String schemaName) {
		CloneSchema__mdt parentSchema = [
			SELECT
				TargetObjectApiName__c,
				Criteria__c,
				(SELECT MergeValue__c FROM CloneSchemaFields__r),
				(
					SELECT Sequence__c, ChildCloneSchemaId__r.DeveloperName
					FROM CloneSchemas__r
					ORDER BY Sequence__c
				)
			FROM CloneSchema__mdt
			WHERE DeveloperName = :schemaName
			WITH SECURITY_ENFORCED
		];
		return parentSchema;
	}

	public static void createCloneSchema(String objectApiName, String objectLabel) {
		CustomMetadata.Operations
			.callback(
				// Platform event for deploy status
				MetadataDeployment__e.getSObjectType(),
				MetadataDeployment__e.DeploymentId__c,
				MetadataDeployment__e.Result__c
			)
			.enqueueUpsertRecords(
				// Custom Metadata object type
				CloneSchema__mdt.getSObjectType(),
				new List<Map<SObjectField, Object>>{
					// Custom Metadata record
					new Map<SObjectField, Object>{
						CloneSchema__mdt.DeveloperName => objectLabel,
						CloneSchema__mdt.TargetObjectApiName__c => 'PSQ__' + objectApiName,
						CloneSchema__mdt.Label => objectLabel,
						CloneSchema__mdt.IsRootCloneSchema__c => false
					}
				}
			);

		List<Map<SObjectField, Object>> schemaFields = new List<Map<SObjectField, Object>>();
		Set<String> fieldNames = SObjectUtility.getCustomFieldsForSObjectOriginalCasing(objectApiName);
		for (String fieldName : fieldNames) {
			if (fieldName.contains('__c')) {
				String label = fieldName.replace('__c', '');
				schemaFields.add(
					new Map<SObjectField, Object>{
						CloneSchemaField__mdt.DeveloperName => objectLabel +
						'_' +
						label,
						CloneSchemaField__mdt.CloneSchemaId__c => objectLabel,
						CloneSchemaField__mdt.Label => objectLabel +
						'_' +
						label,
						CloneSchemaField__mdt.FieldApiName__c => 'PSQ__' + fieldName
					}
				);
			}
		}

		CustomMetadata.Operations
			.callback(
				// Platform event for deploy status
				MetadataDeployment__e.getSObjectType(),
				MetadataDeployment__e.DeploymentId__c,
				MetadataDeployment__e.Result__c
			)
			.enqueueUpsertRecords(
				// Custom Metadata object type
				CloneSchemaField__mdt.getSObjectType(),
				schemaFields
			);
	}

	public static CloneSchemaDto createSchemaTree(String schemaName) {
		CloneSchema__mdt parentSchema = CloneSchemaService.getParentSchema(schemaName);
		CloneSchemaDto schemaDto = new CloneSchemaDto(parentSchema);
		schemaDto.setFields(CloneSchemaService.getCloneSchemaFieldByName(schemaName).values());

		for (CloneSchemaParentChild__mdt childSchemaJunction : parentSchema.CloneSchemas__r) {
			String childSchemaName = childSchemaJunction.ChildCloneSchemaId__r.DeveloperName;
			CloneSchema__mdt childSchema = CloneSchemaService.getParentSchema(childSchemaName);
			CloneSchemaDto childSchemaDto = new CloneSchemaDto(childSchema);
			childSchemaDto.setFields(
				CloneSchemaService.getCloneSchemaFieldByName(childSchemaName).values()
			);
			schemaDto.childSchemas.add(childSchemaDto);
		}
		return schemaDto;
	}
}