quoting-CypressTK1/force-app/main/default/objects/ApprovalRequestItem__c/ApprovalRequestItem__c.object-meta.xml
<CustomObject>
    <label>Approval Request Item</label>
    <nameField>
        <displayFormat>ARI-{00000}</displayFormat>
        <label>Approval Request Item</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Approval Request Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

quoting-CypressTK1/force-app/main/default/objects/ApprovalRequestItem__c/fields/ApprovalSubmissionComments__c.field-meta.xml
<CustomField>
    <fullName>ApprovalSubmissionComments__c</fullName>
    <label>Approval Submission Comments</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

quoting-CypressTK1/force-app/main/default/objects/ApprovalRequestItem__c/fields/IsPrimaryItem__c.field-meta.xml
<CustomField>
    <fullName>IsPrimaryItem__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Primary Item</label>
    <type>Checkbox</type>
</CustomField>

quoting-CypressTK1/force-app/main/default/objects/ApprovalRequestItem__c/fields/QuoteId__c.field-meta.xml
<CustomField>
    <fullName>QuoteId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quote</label>
    <referenceTo>Quote__c</referenceTo>
    <relationshipLabel>Approval Request Items</relationshipLabel>
    <relationshipName>ApprovalRequestItems</relationshipName>
    <type>Lookup</type>
</CustomField>

quoting-CypressTK1/force-app/main/default/objects/ApprovalRequestItem__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

quoting-CypressTK1/force-app/main/default/classes/ApprovalRequestItemDto.cls
public with sharing class ApprovalRequestItemDto {
	@AuraEnabled
	public String submittedComments { get; set; }
	@AuraEnabled
	public String quoteId { get; set; }
	@AuraEnabled
	public String status { get; set; }
	@AuraEnabled
	public Boolean isPrimaryItem { get; set; }

	public ApprovalRequestItemDto() {
		this.isPrimaryItem = false;
	}

	public ApprovalRequestItem__c newSO() {
		return new ApprovalRequestItem__c(
			ApprovalSubmissionComments__c = this.submittedComments,
			QuoteId__c = this.quoteId,
			Status__c = this.status,
			IsPrimaryItem__c = this.isPrimaryItem
		);
	}
}