quoting-CypressTK1/force-app/main/default/objects/VolumeDiscount__c/VolumeDiscount__c.object-meta.xml
<CustomObject>
    <description>Contains volume discount record</description>
    <label>Volume Discount</label>
    <nameField>
        <displayFormat>QVD-{00000}</displayFormat>
        <label>Volume Discount</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Volume Discounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

quoting-CypressTK1/force-app/main/default/objects/VolumeDiscount__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <description>Picklist of available category selections for quote volume discount</description>
    <inlineHelpText>Choose your quote volume discount category</inlineHelpText>
    <label>Category</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Headcount</fullName>
                <label>Headcount Discount</label>
            </value>
            <value>
                <fullName>Labor Revenue</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

quoting-CypressTK1/force-app/main/default/objects/VolumeDiscount__c/fields/TotalBy__c.field-meta.xml
<CustomField>
    <fullName>TotalBy__c</fullName>
    <description
	>Selection indicating at what level to apply tier discount details to total whether at the overall quote level, quote period or period group level.</description>
    <inlineHelpText>Choose which level to apply the volume discount</inlineHelpText>
    <label>Total by</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Quote</fullName>
            </value>
            <value>
                <fullName>Period</fullName>
            </value>
            <value>
                <fullName>Period Group</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

quoting-CypressTK1/force-app/main/default/classes/VolumeDiscountSummaryDto.cls
/**
 *  Provus Services Quoting
 *  VolumeDiscountSummary
 *  @2022 Provus Inc. All rights reserved.
 */
public with sharing class VolumeDiscountSummaryDto {
	public VolumeDiscountSummaryDto() {
		this.appliedTierSummaries = new List<VolumeDiscountAppliedTierSummaryDto>();
	}

	public VolumeDiscountSummaryDto(
		VolumeDiscount__c volumeDiscountSO,
		Map<String, String> categoryPicklistOptions
	) {
		this.appliedTierSummaries = new List<VolumeDiscountAppliedTierSummaryDto>();
		this.categoryValue = volumeDiscountSO.Category__c;
		// get category label by value from category picklist options
		this.categoryLabel = categoryPicklistOptions.get(volumeDiscountSO.Category__c);
		this.totalBy = volumeDiscountSO.TotalBy__c;
	}

	@AuraEnabled
	public String basedOn { get; set; }

	@AuraEnabled
	public String categoryValue { get; set; }

	@AuraEnabled
	public String categoryLabel { get; set; }

	@AuraEnabled
	public String totalBy { get; set; }

	@AuraEnabled
	public List<VolumeDiscountAppliedTierSummaryDto> appliedTierSummaries { get; set; }
}