quoting-CypressTK1/force-app/main/default/objects/VolumeDiscount__c/VolumeDiscount__c.object-meta.xml
<CustomObject>
    <description>Contains volume discount record</description>
    <label>Volume Discount</label>
    <nameField>
        <displayFormat>QVD-{00000}</displayFormat>
        <label>Volume Discount</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Volume Discounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

quoting-CypressTK1/force-app/main/default/objects/VolumeDiscount__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <description>Picklist of available category selections for quote volume discount</description>
    <inlineHelpText>Choose your quote volume discount category</inlineHelpText>
    <label>Category</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Headcount</fullName>
                <label>Headcount Discount</label>
            </value>
            <value>
                <fullName>Labor Revenue</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

quoting-CypressTK1/force-app/main/default/objects/VolumeDiscount__c/fields/QuoteId__c.field-meta.xml
<CustomField>
    <fullName>QuoteId__c</fullName>
    <description>Relationship to parent Quote record</description>
    <inlineHelpText>Relationship to parent Quote record</inlineHelpText>
    <label>Quote</label>
    <referenceTo>Quote__c</referenceTo>
    <relationshipLabel>Volume Discounts</relationshipLabel>
    <relationshipName>VolumeDiscounts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

quoting-CypressTK1/force-app/main/default/objects/VolumeDiscount__c/fields/TotalBy__c.field-meta.xml
<CustomField>
    <fullName>TotalBy__c</fullName>
    <description
	>Selection indicating at what level to apply tier discount details to total whether at the overall quote level, quote period or period group level.</description>
    <inlineHelpText>Choose which level to apply the volume discount</inlineHelpText>
    <label>Total by</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Quote</fullName>
            </value>
            <value>
                <fullName>Period</fullName>
            </value>
            <value>
                <fullName>Period Group</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

quoting-CypressTK1/force-app/main/default/classes/VolumeDiscountDto.cls
/**
 *  Provus Services Quoting
 *  VolumeDiscountDTO
 *  @2022 Provus Inc. All rights reserved.
 */
public with sharing class VolumeDiscountDto extends BaseDTO {
	public VolumeDiscountDto() {
		this.tiers = new List<VolumeDiscountTierDto>();
	}

	public VolumeDiscountDto(VolumeDiscount__c volumeDiscountSO) {
		this.id = volumeDiscountSO.Id;
		this.quoteId = volumeDiscountSO.QuoteId__c;
		this.category = volumeDiscountSO.Category__c;
		this.totalBy = volumeDiscountSO.TotalBy__c;
		this.tiers = new List<VolumeDiscountTierDto>();
	}

	@AuraEnabled
	public Id quoteId { get; set; }

	@AuraEnabled
	public String category { get; set; }

	@AuraEnabled
	public String totalBy { get; set; }

	@AuraEnabled
	public List<VolumeDiscountTierDto> tiers { get; set; }

	public override SObject refreshSo() {
		this.sObj = new VolumeDiscount__c(
			QuoteId__c = this.quoteId,
			Id = this.id,
			Category__c = this.category,
			TotalBy__c = this.totalBy
		);

		return this.sObj;
	}
}