quoting-CypressTK1/force-app/main/default/objects/COLARateSheet__c/fields/QuoteId__c.field-meta.xml
<CustomField>
    <fullName>QuoteId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quote</label>
    <referenceTo>Quote__c</referenceTo>
    <relationshipLabel>Cola Rate Sheets</relationshipLabel>
    <relationshipName>ColaRateSheets</relationshipName>
    <type>Lookup</type>
</CustomField>

quoting-CypressTK1/force-app/main/default/objects/COLARateSheet__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Quote</fullName>
                <default>true</default>
                <label>Quote</label>
            </value>
            <value>
                <fullName>Global</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

quoting-CypressTK1/force-app/main/default/classes/AdjustColaRatesController.cls
/*
 * Provus Services Quoting
 * Copyright (c) 2022 Provus Inc. All rights reserved.
 */

public with sharing class AdjustColaRatesController {
	@AuraEnabled
	public static List<ColaRateDto> getColaRatesForQuote(Id quoteId) {
		ColaRateSheet__c quoteRateSheet = ColaRateSheetService.getRateSheetForQuote(quoteId);
		if (quoteRateSheet != null) {
			return ColaRateService.getColaRates(quoteRateSheet.Id);
		}
		return new List<ColaRateDto>();
	}

	@AuraEnabled
	public static List<ColaRateDto> saveColaRateForQuote(
		List<ColaRateDto> rateDtos,
		List<Id> colaRatesToDelete,
		Id quoteId
	) {
		ColaRateSheet__c quoteRateSheet = ColaRateSheetService.getRateSheetForQuote(quoteId);
		if (quoteRateSheet == null) {
			quoteRateSheet = new ColaRateSheet__c(
				QuoteId__c = quoteId,
				Type__c = ColaRateSheet.TYPE_QUOTE
			);
			CRUDUtility.insertRecords(quoteRateSheet);
		}
		for (ColaRateDto colaRateDto : rateDtos) {
			colaRateDto.rateSheetId = quoteRateSheet.Id;
		}

		ColaRateService.saveColaRates(rateDtos);
		ColaRateService.deleteColaRates(colaRatesToDelete);
		return getColaRatesForQuote(quoteId);
	}
}