quoting-CypressTK1/force-app/main/default/objects/COLARateSheet__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Quote</fullName>
                <default>true</default>
                <label>Quote</label>
            </value>
            <value>
                <fullName>Global</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

quoting-CypressTK1/force-app/main/default/classes/GlobalColaRateAdminController.cls
/*
 * Provus Services Quoting
 * Copyright (c) 2022 Provus Inc. All rights reserved.
 */

public with sharing class GlobalColaRateAdminController {
	@AuraEnabled
	public static List<ColaRateDto> getActiveGlobalColaRates() {
		ColaRateSheet__c globalRateSheet = ColaRateSheetService.getActiveGlobalRateSheet();
		if (globalRateSheet != null) {
			return ColaRateService.getColaRates(globalRateSheet.Id);
		}

		return new List<ColaRateDto>();
	}

	@AuraEnabled
	public static List<ColaRateDto> saveGlobalColaRates(List<ColaRateDto> rateDtos) {
		ColaRateSheet__c globalRateSheet = ColaRateSheetService.getActiveGlobalRateSheet();
		if (globalRateSheet == null) {
			globalRateSheet = new ColaRateSheet__c(
				Name = ColaRateSheet.TYPE_GLOBAL,
				Type__c = ColaRateSheet.TYPE_GLOBAL
			);
			CRUDUtility.insertRecords(globalRateSheet);
		}

		for (ColaRateDto colaRateDto : rateDtos) {
			colaRateDto.rateSheetId = globalRateSheet.Id;
		}

		ColaRateService.saveColaRates(rateDtos);
		return getActiveGlobalColaRates();
	}

	@AuraEnabled
	public static void deleteGlobalColaRates(List<Id> rateIds) {
		ColaRateService.deleteColaRates(rateIds);
	}
}